### ISSUE TITLE
TCA breaks update of UI when toggleStyle is used on Toggle when wrapped in custom view which computes its body from function.

### ISSUE THREAD

**Issue by Sajjon** [pointfreeco/swift-composable-architecture#1022]
**Describe the bug**
Under some very niched constraints, TCA breaks UI, Toggle's `isOn` state gets updated by TCA, but not UI.

I managed to fix this bug in my own code, by not storing and calling ViewBuilder function from body of custom `ForceFullScreen` view, but rather actually just storing the content in init.

The update of UI is only broken using TCA, when using vanilla SwiftUI `@State` and a binding it works.

My discovery, and especially the fix for it might both be interesting and helpful to you at Pointfree but also other developers using TCA. [`SettingsForm` in Isowords](https://github.com/pointfreeco/isowords/blob/fcff52ccf176f40db55951d5897def7cd9b879cf/Sources/Styleguide/SettingsForm.swift) might benefit from my discover? E.g. change

```swift
public struct SettingsForm<Content>: View where Content: View {
...
  let content: () -> Content

  public init(@ViewBuilder content: @escaping () -> Content) {
    self.content = content
  }

  public var body: some View {
...
      self.content()
      ...
  }
}
```

to 

```swift
public struct SettingsForm<Content>: View where Content: View {
...
  let content: Content

  public init(@ViewBuilder content: @escaping () -> Content) {
    self.content = content()
  }

  public var body: some View {
...
      self.content
...
  }
}
```

Actually you do exactly this [in Isowords View `Preview`](https://github.com/pointfreeco/isowords/blob/fcff52ccf176f40db55951d5897def7cd9b879cf/Sources/SwiftUIHelpers/Preview.swift). _**So maybe you can inform me of the difference?**_

**To Reproduce**
[Here is my example repo demonstrating the issue](https://github.com/Sajjon/ToggleBroken), it uses TCA version 0.33.1

It looks like this:
<img width="612" alt="toggleBrokenTCA" src="https://user-images.githubusercontent.com/864410/158352872-51d3b087-a8ad-4bd0-a447-b2d33cb1b7d5.png">

Run the app and with `Wrap in ForceFullScreen` setting is on, the Toggle in the bottom ``"Loves Street Fighter" which uses TCA updates state, but not UI! The Togge "Loves StarFox" above, however,  does work, because it does not use `toggleStyle(CheckboxStyle())`. Turn off Wrap in `ForceFullScreen` an all TCA toggles works as expected, even when using `toggleStyle(CheckboxStyle())`

`CheckboxStyle` is a custom ToggleStyle implemented like so:

```swift
public struct CheckboxToggleStyle: ToggleStyle {
	public init() {}
	public func makeBody(configuration: Configuration) -> some View {
		HStack(alignment: .center, spacing: 16) {
			Image(
				systemName: configuration.isOn ? "checkmark.square" : "square"
			)
			.resizable()
			.frame(width: 22, height: 22)
			.foregroundColor(Color.teal)
			.onTapGesture {
				withAnimation { // removing this animation call does not change anything.
					configuration.isOn.toggle()
				}
			}
			
			configuration.label
			Spacer()
		}
	}
}
```

All Vanilla SwiftUI Toggles, even when using custom `toggleStyle(CheckboxStyle())` works. So TCA behaves differently.

**Expected behavior**
I expect "the TCA toggles" (Toggles which `isOn` binding is created using `viewstore.binding(get:set:)`) to behave like SwiftUI's and updates it UI, even when using a custom toggleStyle and when wrapped in a custom container view `ForceFullScreen` view.

Clearly TCA affects the behaviour of the Toggle. 

I got same behaviour when using local ViewState and ViewAction with a scoped store as input to WithViewStore.

**Environment**
  - swift-composable-architecture version 0.33.1
  - Xcode 13.3 (13E113) (Release Candidate)
  - Swift 5.6
  - iPhone 7 with iOS 15.3 also broken in Simulator (iPhone 14 Simulator, running iOS 15.4)

**Additional context**
Really important take of away here might be _**how SHOULD be store ViewBuilder functions in custom views? As functions? Or as values, which get from calling ViewBuilder function in init of custom view? What implications that this difference have?**_

**Comment by tgrapperon** [comment]
Hi @Sajjon!
Your problem is probably related to #1015, and caused by `WithViewStore`. The fix is on `main`, so you can maybe quickly update your dependencies to point to this branch to check if it solves the issue. Alternatively, you can forego `WithViewStore` and check if the issue is fixed when you install the `ViewStore` instance  yourself as `@ObservedObject var viewStore` (you can do this in the `init` of the view. If this fixes the problem, then the next update of TCA will most likely do too.

Nothing is engraved in stone, but I would say that in general, if you can evaluate the closure in the `init`, you should probably do it immediately and not escape it. If your closure accepts an argument that is not already accessible (like the `GeometryProxy` of `GeometryReader` for example), you will need to escape the closure and evaluate it in `body`. This prescription comes from the observation that the vast majority of `@ViewBuilder` closures are not escaping and evaluated immediately. Of course, you can adapt on the case by case basis if needed.

**Comment by Sajjon** [comment]
@tgrapperon ACK, the #1015 PR fixed it! 🎉

And thank you very much for the guideline regarding storing ViewBuilder closures or evaluating them in init, I appreciate it! I'm kind of new to SwiftUI and very new to TCA.
