### ISSUE TITLE
Error when including in a framework and app target

### ISSUE THREAD

**Issue by klaaspieter** [pointfreeco/swift-composable-architecture#103]
**Describe the bug**

⚠️ Edit: looks like this started failing with 0.1.3.

After upgrading to 0.1.4 build started to fail with:

```
Showing Recent Messages

Prepare build
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description


Build system information
error: Swift package product 'ComposableArchitecture' is linked as a static library by 'all-the-targets' and 'Core'. This will result in duplication of library code.

Build system information
error: Swift package product 'CasePaths' is linked as a static library by 'all-the-targets' and 'Core'. This will result in duplication of library code.



Build failed    15/05/2020, 15:45    1.1 seconds
```

**To Reproduce**

[all-the-targets.zip](https://github.com/pointfreeco/swift-composable-architecture/files/4634718/all-the-targets.zip)

Build the app scheme

**Expected behavior**
☝️ to build

**Environment**
 - Xcode [e.g. 11.4.1]

**Additional context**

It looks like a [related issue was fixed in 11.4.1](https://forums.developer.apple.com/thread/128806). Not sure if this is a similar issue or if I'm truly holding it wrong 😄

**Comment by stephencelis** [comment]
Hi @klaaspieter! This is a gotcha of how SPM libraries work that we try to document in the [installation](https://github.com/pointfreeco/swift-composable-architecture#installation) section of the README and the [0.1.3 release notes](https://github.com/pointfreeco/swift-composable-architecture/releases/tag/0.1.3), but if you have any ideas on how to make the messaging clearer, please let us know!

In order to integrate static SPM dependencies in a modularized application you must put all of them in a single, dynamic framework. Then this framework is what you share among your app, framework, and test targets..

**Comment by klaaspieter** [comment]
Oops. I read the release notes when it was released but didn't read them again while trying to upgrade 🤦 

I _just_ read them again though and they didn't make it immediately clear what to do. Whereas this does:

> In order to integrate static SPM dependencies in a modularized application you must put all of them in a single, dynamic framework. Then this framework is what you share among your app, framework, and test targets..

Perhaps put this with a ⚠️ and some bold text in the release notes?

**Comment by stephencelis** [comment]
@klaaspieter How's this look? https://github.com/pointfreeco/swift-composable-architecture/releases/tag/0.1.3

**Comment by tarjamorgado** [comment]
If I may, 

The [reply](https://forums.swift.org/t/how-to-integrate-tca-framework-as-of-0-1-3/36443/2?u=tarjamorgado) from @stephencelis in the [Swift Forums](https://forums.swift.org/c/related-projects/swift-composable-architecture) was helpfull to me:

> Can you check out the Tic-Tac-Toe demo app and try to figure out what's different? We've updated it to work with this style of "shared" framework since it is heavily modularized. It uses a TicTacToeCommon framework to share the static ComposableArchitecture library. I wonder if the build failure has anything to do with if/which/where/how frameworks/libraries are embedded in your tree of dependencies.

**Comment by stephencelis** [comment]
@klaaspieter did that help get you in building order again? Or are you seeing more issues?

**Comment by klaaspieter** [comment]
@stephencelis yes perfect. Thank you! ComposableArchitectureTestSupport was the final missing piece but I managed to figure it out by looking at the PR. I see it's also in the release notes now 👍 

Thank you!
