### ISSUE TITLE
FocusState not working, in first intention

### ISSUE THREAD

**Issue by jtouzy** [pointfreeco/swift-composable-architecture#1070]
**Describe the bug**
In your `FocusDemo` in case study, all works perfectly. If you setup your `FocusDemoState` with a default focused field, it will not be focused when the view appears. SwiftUI didn't catch any change so the `synchronize` method (double onChange) does nothing.
And, even if you trigger an onAppear event in the `FocusDemoView`, and you change the focusedField in the reducer at this time (for example, with password), nothing will be updated. I think it's a bit early for SwiftUI and the `@FocusState` mechanism.
Didn't find any good solution for now. Except, maybe, a weird delay.

**To Reproduce**
Just take the CaseStudies in main branch, and init the `FocusDemoState` with a default `focusedField`.

**Expected behavior**
The focused field should be focused when the view appears.

**Environment**
  - swift-composable-architecture 0.34.0
  - Xcode 13.3
  - Swift 5.6
  - OS: iOS 15.4

**Comment by rhysm94** [comment]
If you look at a cut-down SwiftUI example of this, there's not actually a way to make `@FocusState` work with a default value, other than with an indeterminate delay.

```swift
import SwiftUI

struct ContentView: View {
    @State var text = ""
    @FocusState var focused: Bool
    
    var body: some View {
        TextField("Placeholder", text: $text)
            .focused($focused)
            .onAppear {
                focused = true
            }
    }
}
```

This doesn't actually assign focus to the text field like it should. There's also no way to initialise `@FocusState` with a value, as it doesn't have an initialiser which takes an initial value.

This is just yet another unfortunate SwiftUI error/bug, and not specific to Composable Architecture.

**Comment by mbrandonw** [comment]
Thanks for investigating @rhysm94! I'm going to close this since it's not an issue with the library, but @jtouzy do feel free to open a discussion if you wanna talk about workarounds!
