### ISSUE TITLE
xcode hangs when adding @ObservedObject to ViewStore

### ISSUE THREAD

**Issue by Shivam412** [pointfreeco/swift-composable-architecture#109]
When I am adding

` @ObservedObject var viewStore: ViewStore<State, Action>
`

my Xcode hangs and I have to force quit it.

is there anything I am missing ?.

**Comment by stephencelis** [comment]
Hi @Shivam412! Can you please use our GitHub issue template so that we have enough information to help? I've pasted it again below:

    **Describe the bug**
    Give a clear and concise description of what the bug is.

    **To Reproduce**
    Zip up a project that reproduces the behavior and attach it by dragging it here.

    ```swift
    // And/or enter code that reproduces the behavior here.

    ```

    **Expected behavior**
    Give a clear and concise description of what you expected to happen.

    **Screenshots**
    If applicable, add screenshots to help explain your problem.

    **Environment**
     - Xcode [e.g. 11.4.1]
     - Swift [e.g. 5.2.2]
     - OS (if applicable): [e.g. iOS 13]

    **Additional context**
    Add any more context about the problem here.

**Comment by stephencelis** [comment]
One thing that comes to mind, though, is that there seems to be a bug around dynamic member lookup (which `ViewStore` uses) and complex view builders, such that if you have a typo on the `viewStore`, it can hang builds indefinitely. You can usually zero in on the typo by either commenting out portions of the view that call to `viewStore`, or by explicitly accessing state through `viewStore.state`.

**Comment by Shivam412** [comment]
Thanks @stephencelis, I will update issue template after implementing your last point.

**Comment by Shivam412** [comment]
**Describe the bug**

I have two state one is AppState which contains another state DashboardState, Which also have separate reducers and I combine both reducers using Reduce.combine.

```
// so I need to pass following code to Dashboard's child view
ViewStore<DashBoardState, DashBoardAction>
```
```
// at its child view, I am using it by 
@ObservedObject var dashBoard: ViewStore<DashBoardState, DashBoardAction>
```

but adding above point hangs my Xcode after which I need to force quit it.

```swift
// And/or enter code that reproduces the behaviour here.

public struct AppState: Equatable {
    var dashBoardState: DashBoardState? = DashBoardState()
}

public struct DashBoardState: Equatable {
    var someState: SomeState? = SomeState()
}

reducer is 

let dashBoardReducer: Reducer<DashBoardState, DashBoardAction, DashBoardEnvironment> = Reducer.combine(
    _dashBoardReducer,
     somereducer
   )

let appReducer: Reducer<AppState, AppAction, AppEnvironment> = Reducer.combine(
    _appReducer,
    
    dashBoardReducer.optional.pullback(state: \.dashBoardState,
                                       action: /AppAction.dashboard,
                                       environment: { DashBoardEnvironment()  }),
)

IfLetStore(store.scope(state: \.dashBoardState, action: AppAction.dashboard)) { viewStore  in
      WithViewStore(viewStore) { dashBoardStore in 
            ChildView(viewStore: dashBoardStore)
    }
}

struct ChildView {
     @ObservedObject var dashBoard: ViewStore<DashBoardState, DashBoardAction>
     var body:  some View { ... }
}

```

**Environment**
 - Xcode [e.g. 11.4.1]
 - Swift [e.g. 5.2.2]

**Comment by stephencelis** [comment]
> ```swift
>      var body:  some View { ... }
> ```

Can you post a full, compiling example? The culprit is likely in this `body`, but without a case that we can reproduce we're not going to be able to help.

**Comment by boudavid** [comment]
I had a similar issue where I also had to comment some code in order to pin point what was wrong. Also, in some UIViewControllerRepresentable, I was still using ‘value’ on the ViewStore (that was when I was still using the code from the PrimeTime app) so I just needed to remove them in order to compile.

**Comment by Shivam412** [comment]
> > ```swift
> >      var body:  some View { ... }
> > ```
> 
> Can you post a full, compiling example? The culprit is likely in this `body`, but without a case that we can reproduce we're not going to be able to help.

Even in a simple call like sending an action causes this behaviour.

**Comment by stephencelis** [comment]
@Shivam412 We still need a full example that we can try to compile to help. Can you zip up your project and post it here?

**Comment by stephencelis** [comment]
@Shivam412 Were you able to resolve this?

**Comment by Shivam412** [comment]
@stephencelis give me some time, I will check it send you to update. Thanks

**Comment by mathieutozer** [comment]
I've been experiencing this, also a few times a day my considerably juiced up iMac runs out of application memory and I have to reboot (I suspect it is this issue).

**Comment by stephencelis** [comment]
@mathieutozer It's definitely annoying, but almost always seems to be related to typos on the `viewStore`, right? Wish we could fix this but we'll have to wait on Apple for this one. When you encounter the issue it doesn't hurt to file a report at https://bugs.swift.org

One thing to save you a reboot in the future is to open Activity Monitor, go to the Memory tab, and kill any "swift" and "SourceKit" processes that are spiking in memory.

**Comment by mathieutozer** [comment]
Yes I figured it was an apple bug so have been sitting tight.

Thanks for the Activity Monitor tip! Coincidentally I ran out of memory reading this and It looks like it saved me a reboot.

**Comment by pcolton** [comment]
I'd like to add that one thing that helped me a lot is to move small sections out of the main body into their own functions/properties. It both helps with debugging and Xcode has an easier time figuring out what to do.

**Comment by Shivam412** [comment]
[Xcode Hangs.zip](https://github.com/pointfreeco/swift-composable-architecture/files/4673701/Xcode.Hangs.zip)

Here is the project in zip file.

Below image show activity monitor's top processes 

![Screenshot 2020-05-24 at 8 01 03 PM](https://user-images.githubusercontent.com/23121789/82756757-bb1ed900-9df9-11ea-9f39-43a6acc4e20a.png)

**Comment by pcolton** [comment]
@Shivam412 On line 37 you are missing a `self.` in front of the `viewStore.state.text`. With that change it runs for me.

**Comment by Shivam412** [comment]
> @Shivam412 On line 37 you are missing a `self.` in front of the `viewStore.state.text`. With that change it runs for me.

you write one cmd + z basically remove that line, but the point is here that it hangs my Xcode, after some time mac os too. above SS showing some CPU usage, As @stephencelis told we can close it using an activity monitor.

**Comment by stephencelis** [comment]
@Shivam412 This is an Apple bug and not something we can fix, unfortunately. It's helpful to know a couple things, though:

* You can _usually_ find/replace `viewStore` with `viewStore.state` to track the issue down.
* You can open ActivityMonitor.app and force quit any `swift` and `SourceKit` processes if they take over your CPU.

If you can, please submit your project to https://bugs.swift.org and https://feedbackassistant.apple.com if you have time and want to see this fixed!

**Comment by stephencelis** [comment]
@Shivam412 Since it looks like we all agree that this is an Apple bug and not a Composable Architecture bug, is it OK to close this? We also plan on documenting some of these "gotchas" better in the future.

**Comment by Shivam412** [comment]
> @Shivam412 Since it looks like we all agree that this is an Apple bug and not a Composable Architecture bug, is it OK to close this? We also plan on documenting some of these "gotchas" better in the future.

sure and thanks @stephencelis
