### ISSUE TITLE
Undefined symbol trying to build a test.

### ISSUE THREAD

**Issue by pcolton** [pointfreeco/swift-composable-architecture#110]
This is all I have so far and I'm getting the compiler error. Am I missing something obvious?

```swift
   func testPodcastFavoriteToggle() {
        let store = TestStore(
            initialState: TopShowsState(topPodcasts: self.topPodcasts),
            reducer: topShowsReducer,
            environment: SystemEnvironment.live(environment:
                TopShowsEnvironment(dataClient: DataClient.mock())
            )
        )
    }

```

and my reducer's type:

```swift
public let topShowsReducer: Reducer<TopShowsState, TopShowsAction, SystemEnvironment<TopShowsEnvironment>> =
```

the error...

<img width="566" alt="image" src="https://user-images.githubusercontent.com/92073/82219804-a5c61e00-98d2-11ea-94d9-665727ea7318.png">

thanks.

**Comment by stephencelis** [comment]
Hey @pcolton! This kind of error usually means build settings need to be tweaked, but we'll need more information to troubleshoot. Can you please use our GitHub issue template and attach a project that reproduces the error? I've pasted the template in again below:

    **Describe the bug**
    Give a clear and concise description of what the bug is.

    **To Reproduce**
    Zip up a project that reproduces the behavior and attach it by dragging it here.

    ```swift
    // And/or enter code that reproduces the behavior here.

    ```

    **Expected behavior**
    Give a clear and concise description of what you expected to happen.

    **Screenshots**
    If applicable, add screenshots to help explain your problem.

    **Environment**
     - Xcode [e.g. 11.4.1]
     - Swift [e.g. 5.2.2]
     - OS (if applicable): [e.g. iOS 13]

    **Additional context**
    Add any more context about the problem here.

**Comment by pcolton** [comment]
**Describe the bug**
Cannot build project which includes a test, get error.

**To Reproduce**
Created a simple test project, added TCA as a framework. Then added a test case target, test won't compile properly.

**Screenshots**

![](https://user-images.githubusercontent.com/92073/82219804-a5c61e00-98d2-11ea-94d9-665727ea7318.png)

**Environment**
 - Xcode 11.4.1

[TestTCA.zip](https://github.com/pointfreeco/swift-composable-architecture/files/4644558/TestTCA.zip)

**Comment by mbrandonw** [comment]
Hey @pcolton, looks like TCA isn't being linked in the test target:

<img width="838" alt="image" src="https://user-images.githubusercontent.com/135203/82223031-f17ac680-98d6-11ea-9c44-48f894ece8d2.png">

That'll fix it.

**Comment by pcolton** [comment]
Yes, thank you. Too bad that's a bit buried in settings for tests. I've been using TCA for many months now, but just now getting to tests (I know, bad) - but that error was a bit obscure to me and I didn't consider the obvious. 

I think adding a TCA FAQ to your site or as a pinned item in the forums might be nice, and covering this specific error would be nice as well ;-).

Thanks!
