### ISSUE TITLE
Modifying state during view update, this will cause undefined behavior.

### ISSUE THREAD

**Issue by nashysolutions** [pointfreeco/swift-composable-architecture#1111]
**Describe the bug**
2022-05-30 10:15:07.466884+0100 TicTacToe[27079:549918] [SwiftUI] Modifying state during view update, this will cause undefined behavior.

**To Reproduce**
On the first launch of the TicTacToe example implementation, attempt login using invalid credentials.

**Environment**
  - swift-composable-architecture version - the tip of the main branch at time of writing - which is commit fb0d371e142f64110e72a944d14c53cf2b4c1a2f
  - Xcode 13.3
  - swift-driver version: 1.45.2 Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
Target: arm64-apple-macosx12.0
  - OS: 12.3.1

**Comment by mbrandonw** [comment]
Hi @nashysolutions, thanks for bringing this up. I just merged #1114 which fixes the issue in the demo app.

Note that this is actually an issue with SwiftUI, not TCA, but still good to fix!
