### ISSUE TITLE
Sometime actions doesn't received from async throws Effect.task

### ISSUE THREAD

**Issue by rock88** [pointfreeco/swift-composable-architecture#1130]
**Describe the bug**
Hi! I use async throws Effect.task and encountered with a bug:

**To Reproduce**
Minimum example:
[Effect-Task-Bug.zip](https://github.com/pointfreeco/swift-composable-architecture/files/8835713/Effect-Task-Bug.zip)

```swift
struct State: Equatable {
    var first = 0
    var second = 0
}

enum Action {
    case first
    case second
}

let reducer = Reducer<State, Action, Void> { state, action, _ in
    switch action {
    case .first:
        state.first += 1
        return Effect.task {
            _ = try anyThrowFunc()
            return .second
        }
        .catch { _ in Empty() }
        .receive(on: DispatchQueue.main)
        .eraseToEffect()
    case .second:
        state.second += 1
        return .none
    }
}

private func anyThrowFunc() throws {
    //
}
```

If remove `_ = try anyThrowFunc()` and `.catch { _ in Empty() }` all fine.

In my project case more complex, for example:

```swift
case .someAction:
    return Effect.task {        
        guard let someRequiredField = state.field else {
            return .someRequiredFieldNotFound
        }
        
        if await environment.shouldDoSomething(someRequiredField) {
            throw CancellationError()
        }

        do {
            let result = try await environment.doSomething(someRequiredField)
            return .done(result)
        } catch {
            return .failure(error)
        }
    }
    .catch { _ in Empty() }
    .receive(on: DispatchQueue.main)
    .eraseToEffect()
```

I think problem with `PassthroughSubject`, value send before `sink`. I tried to replace it with `CurrentValueSubject`, but bug still appear, anyway this subjects not a thread safe...

One possible solution:

```swift
private extension CurrentValueSubject {
    @MainActor func safeSend(_ input: Output)  {
        send(input)
    }
}

extension Effect {
    public static func task(
        priority: TaskPriority? = nil,
        operation: @escaping @Sendable () async throws -> Output
    ) -> Self where Failure == Error {
        Deferred<Publishers.HandleEvents<CurrentValueSubject<Output?, Failure>>> {
            let subject = CurrentValueSubject<Output?, Failure>(nil)
            let task = Task(priority: priority) {
                do {
                    try Task.checkCancellation()
                    let output = try await operation()
                    try Task.checkCancellation()
                    await subject.safeSend(output)
                    // subject.send(output)
                    subject.send(completion: .finished)
                } catch is CancellationError {
                    subject.send(completion: .finished)
                } catch {
                    subject.send(completion: .failure(error))
                }
            }
            return subject.handleEvents(receiveCancel: task.cancel)
        }
        .compactMap { $0 }
        .eraseToEffect()
    }
}
```

**Expected behavior**
After first action should sending second.

**Screenshots**
<img width="361" alt="Screenshot 2022-06-03 at 23 38 22" src="https://user-images.githubusercontent.com/323908/171948841-eb7f2066-0cb1-40b8-a535-b6e3962dc12d.png">

**Environment**
  - swift-composable-architecture version [0.35.0]
  - Xcode [13.4]
  - Swift [5.6]
  - OS: [iOS 15/MacOS 12]

**Comment by mbrandonw** [comment]
@rock88 Nice find! Can you re-run your project with it pointing to PR #1131 to see if it fixes the issue? It seems to fix it for me, but then again maybe I'm not tapping fast enough 😅.

**Comment by rock88** [comment]
@mbrandonw yep, https://github.com/pointfreeco/swift-composable-architecture/pull/1131 works, but now it's block UI thread:

```swift
...
return Effect.task {
    _ = try anyThrowFunc()
    sleep(1)
    return .second
}
...
```

**Comment by mbrandonw** [comment]
Hi @rock88, I think that's just a coincidence. There is no guarantee that it will be called on the main thread. If you mix in some real asynchronous work in the task you will see that it does not stay on the main thread:

```swift
return Effect._task {
  print(Thread.current)
  _ = try? await URLSession.shared.data(from: .init(string: "http://ipv4.download.thinkbroadband.com/1MB.zip")!)
  print(Thread.current)
  return .second
}
```

That shows the thread definitely changes.

You can see the same if you use `Task.sleep` instead of `sleep`, which is what you should be using anyway:

```swift
return Effect._task {
  print(Thread.current)
  try await Task.sleep(nanoseconds: NSEC_PER_SEC)
  print(Thread.current)
  return .second
}
```

Can you confirm that's the case for you?

**Comment by rock88** [comment]
Hi, @mbrandonw! Sorry for delay, I checked fix on a real project and seems to all works fine! Many thanks!
