### ISSUE TITLE
protocol-navigation branch isn't building

### ISSUE THREAD

**Issue by kgrigsby59** [pointfreeco/swift-composable-architecture#1260]
### Description

protocol-navigation branch fails to build

### Checklist

- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues).

### Actual behavior

Build fails with error:
```
error: Filename "NavigationID.swift" used twice: '/Users/kgrigsby/Library/Developer/Xcode/DerivedData/Quarters-apffnnqxdtfbytgkhqvdmnnzyxiz/SourcePackages/checkouts/swift-composable-architecture/Sources/ComposableArchitecture/Dependencies/NavigationID.swift' and '/Users/kgrigsby/Library/Developer/Xcode/DerivedData/Quarters-apffnnqxdtfbytgkhqvdmnnzyxiz/SourcePackages/checkouts/swift-composable-architecture/Sources/ComposableArchitecture/Internal/NavigationID.swift' (in target 'ComposableArchitecture' from project 'swift-composable-architecture')
note: Filenames are used to distinguish private declarations with the same name (in target 'ComposableArchitecture' from project 'swift-composable-architecture')
```

### The Composable Architecture version information

branch 'protocol-navigation'

### Destination operating system

iOS 16

### Xcode version information

Version 14.0 beta 5 (14A5294e)

### Swift Compiler version information

```shell
swift-driver version: 1.62.3 Apple Swift version 5.7 (swiftlang-5.7.0.123.8 clang-1400.0.29.50)
Target: arm64-apple-macosx12.0
```

**Comment by stephencelis** [comment]
@kgrigsby59 Looks like a merge between branches broke things, but it's fixed now. Please note, though, that experimental branches like these will be breaking and changing often, and are still a way of from landing in any form. We try to keep issues reserved for bugs in the library that is shipping, so going to close this out.
