### ISSUE TITLE
Getting started example issues compiler error

### ISSUE THREAD

**Issue by tkunst891** [pointfreeco/swift-composable-architecture#1329]
### Description

I created an app with the code shown in the "Readme" of the repository and the "Getting started" section of the documentation and got  compilation error at this part of the reducer:
```swift
case .numberFactButtonTapped:
  return .task {
    await .numberFactResponse(TaskResult { try await environment.numberFact(state.count) })
  }
```
The compiler error is: 
> Reference to captured parameter 'state' in concurrently-executing code
The solution is to capture the state.count in a local constant:
```swift
case .numberFactButtonTapped:
  return .task { [count = state.count] in
    await .numberFactResponse(TaskResult { try await environment.numberFact(count) })
  }
```
It took me a while to find this solution, so it may be worth to correct this in the documentation.

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues).

### Xcode version information

13.4

**Comment by tgrapperon** [comment]
Indeed, the capture was missing. The `state` is an `inout` parameter that you can modify freely, and for this reason, it can't enter as it into async context. You can indeed use an explicit capture like you did (the preferred/dedicated approach), or assign the value to a `let` constant, which has the same effect:
```swift
case .numberFactButtonTapped:
  let count = state.count
  return .task { 
    await .numberFactResponse(TaskResult { try await environment.numberFact(count) })
  }
```
In both cases, this creates a snapshot of the `count` value at the time the `Effect.task` is emitted/returned by the reducer. This value is then used at a later time when the effect is evaluated and the `.task` closure executed. You can use either method depending on what is the most convenient in a given context.

I created a Pull-Request with the fix[^1]. 

[^1]: As an aside, and this is not a reproach at all, submitting a pull-request is something you could have done by yourself, as it would have been less work for you than opening/filing a bug report. For simple edits like this one, you can do this relatively straightforwardly directly from GitHub, by editing the document, and following the proposed steps.

Thanks for reporting it!
