### ISSUE TITLE
"Cannot find type 'Duration' in scope" error in Xcode 14 Release Candidate when targeting macOS

### ISSUE THREAD

**Issue by Jeehut** [pointfreeco/swift-composable-architecture#1349]
### Description

I just upgraded to the Xcode 14 Release Candidate and my project no longer builds. I've even setup a new project an only included TCA as a dependency, pointing to the latest stable release, with the same result:
![Screen Shot 2022-09-08 at 10 29 35](https://user-images.githubusercontent.com/6942160/189074513-c48eb274-20ec-4d70-8f75-06113c242a58.png)

I already tried the latest `main` branch, same issue there.

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues).

### Expected behavior

My project builds without errors.

### Actual behavior

I'm getting an error stating `Sources/ComposableArchitecture/TestStore.swift:277:27: error build: Cannot find type 'Duration' in scope`.

### Steps to reproduce

1. Create a new multiplatform project in Xcode 14 Release Candidate
2. Include TCA as a dependency (using SwiftPM)
3. Set your build target to "Your Mac"
4. Build the project

### The Composable Architecture version information

0.39.1

### Destination operating system

macOS

### Xcode version information

14.0 Release Candidate

### Swift Compiler version information

```shell
swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
Target: arm64-apple-macosx12.0
```

**Comment by Jeehut** [comment]
Interestingly, I can build without problems when I set an iOS target, e.g. "iPhone 14". My best guess is that `Duration` is a new type introduced with Swift 5.7, but when I target "My Mac" which is currently running the latest release `macOS 12.5.1`, my macOS system has an older version of Swift and somehow Xcode gets confused and still goes inside the `#if swift(>=5.7)` checks which don't work on a macOS 12 target though. Maybe we have to add a macOS availability check additionally.

**Comment by Jeehut** [comment]
I just opened the TCA project and tried to build itself, which also resulted in the same error. It's confusing to see that there is already a macOS version availability check in this code, but it seems to still fail.

![Screen Shot 2022-09-08 at 10 48 59](https://user-images.githubusercontent.com/6942160/189078639-0bc25977-455c-4758-8a50-6d9600ed1c1d.png)

**Comment by Jeehut** [comment]
For anyone coming across this issue, you can _temporarily_ use my PR #1350's branch which fixes it:
```
.package(url: "https://github.com/Jeehut/swift-composable-architecture", branch: "xcode14-macos"),
```

**Comment by Jeehut** [comment]
I just [read here](https://twitter.com/trozware/status/1567675357234606082?s=21&t=cjl0aIFJ8xhG3e33tYog7g) that Xcode 14 Release Candidate doesn't seem to ship with macOS Ventura and that might actually be the reason why the build fails.

**Comment by jshier** [comment]
Yes, Xcode 14 on macOS 12 uses the Swift 5.6 standard library, which doesn't include `Duration`.

**Comment by Jeehut** [comment]
This issue was fixed in https://github.com/pointfreeco/swift-composable-architecture/pull/1351 and currently available in the `main` branch and part of the next release. Closing. Thanks to @mbrandonw for the quick fix!
