### ISSUE TITLE
Nested BindableAction is not recognized for pattern matching in Xcode 14

### ISSUE THREAD

**Issue by ylorn** [pointfreeco/swift-composable-architecture#1356]
### Description

This is issue is not reproducible with Xcode 13, only on Xcode 14. I am not sure if this is an Xcode bug, so feel free to remove the bug label if it is not caused by TCA.

The following code throws a compiler error on `mainReducer`:

> ❗️ Type of expression is ambiguous without more context

```swift
import ComposableArchitecture

struct TestState: Equatable {
    @BindableState var value: Int = 0
}

enum TestAction: Equatable, BindableAction {
    case binding(BindingAction<TestState>)
}

struct TestEnvironment { }

let testReducer = Reducer<TestState, TestAction, TestEnvironment> { _, _, _ in  .none }



struct MainState: Equatable {
    var testState: TestState = .init()
}

enum MainAction: Equatable {
    case testAction(TestAction)
}

struct MainEnvironment {
    var testEnvironment: TestEnvironment = .init()
}

let mainReducer = Reducer<MainState, MainAction, MainEnvironment> { state, action, environment in
    switch action {
        /// Trigger effect if the value is set to 0
        case .testAction(.set(\.$value, 0)):  // <- comment out this case eliminate the compiler error
            return .none

        /// Trigger effect if the value is set to something other than 0
        case .testAction(.binding(\.$value)):
            return .none

        case .testAction:
            return .none
    }
}

```

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues).

### Expected behavior

The code should compile

### Actual behavior

<img width="1113" alt="Screen Shot 2022-09-08 at 4 42 57 PM" src="https://user-images.githubusercontent.com/1502810/189222058-ac209f02-e5e6-4540-9841-85a2ec3e6ec1.png">

### The Composable Architecture version information

0.40.0

### Destination operating system

iOS 16

### Xcode version information

14.0 (14A309)

### Swift Compiler version information

```shell
swift-driver version: 1.45.2 Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
Target: arm64-apple-macosx12.0
```

**Comment by ylorn** [comment]
I guess we have to explicitly call the `.set` on concrete `BindableAction` type with Xcode 14.

```diff
- case .testAction(.set(\.$value, 0)):
+ case .testAction(TestAction.set(\.$value, 0)):
```

**Comment by stephencelis** [comment]
@ylorn This also appears to be a Swift regression. Mind filing a bug with Apple if possible?

For what it's worth, the [Protocol Beta](https://github.com/pointfreeco/swift-composable-architecture/discussions/1282) appears to address this issue, and your example code compiles when the reducer is defined as a type conforming to `ReducerProtocol`.

**Comment by ylorn** [comment]
@stephencelis I am actually waiting for the `Reducer Protocol` episodes to complete so that I can watch the whole series in one go. 😄
