### ISSUE TITLE
SwiftUICaseStudies app crashes

### ISSUE THREAD

**Issue by Coffeemate** [pointfreeco/swift-composable-architecture#136]
**Describe the bug**
The culprit is the `cleanup` function in Effects > Cancellation

**To Reproduce**
1. Navigate to Elm-like Subscriptions
2. Turn on the clock
3. Navigate back to the root view

**Screenshot**
<img width="827" alt="Screenshot 2020-05-26 at 23 18 48" src="https://user-images.githubusercontent.com/4212685/82947681-1511d100-9fa9-11ea-8c64-5d6cc3fd667c.png">

**Environment**
 - Xcode 11.5
 - Swift 5.1
 - iOS 13.5

**Comment by stephencelis** [comment]
Good find! We just started tearing down demos when you pop the nav stack in #130, which surfaced this bug. Turns out we can clean up a bunch of this cancellation logic and avoid the simultaneous access crash, which we've done in #137.
