### ISSUE TITLE
withTaskCancellation retains tasks

### ISSUE THREAD

**Issue by rcarver** [pointfreeco/swift-composable-architecture#1373]
### Description

Using the Swift Concurrency tool in Instruments I noticed that my app was retaining tasks. I tracked it down to using `cancellable` and further to `withTaskCancellation`.

It looks like the `AnyCancellable` retains the Task, so perhaps it should clean up the cancellable when the operation completes?

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues).

### Expected behavior

When any task-based effect ends it should not be counted as 'alive'.

### Actual behavior

Effects using `withTaskCancellation` or `cancellable` remain in an 'alive' state after their operation has completed.

### Base Case

1. Run the SpeechRecognition demo in Instruments with the Swift Concurrency template 
2. Tap the 'Start Recording' button in the SpeechRecognition app to start recording
3. Let it run for a few seconds
4. Tap the 'Stop Recording' button in the SpeechRecognition app to stop recording
5. Stop recording in Instruments

Notice that the the 'Alive Tasks' row increased while recording, then returned to zero when stopped

<img width="644" alt="Screen Shot 2022-09-10 at 9 32 37 PM" src="https://user-images.githubusercontent.com/2343/189512727-fdf1a299-6baf-41dc-bf9d-56c3ed3deadb.png">

### Test Case

1. Apply this diff to `Examples/SpeechRecognition/SpeechRecognition/SpeechRecognition.swift`

```diff
-      let request = SFSpeechAudioBufferRecognitionRequest()
-      for try await result in await environment.speechClient.startTask(request) {
-        await send(.speech(.success(result.bestTranscription.formattedString)), animation: .linear)
+
+      try await withTaskCancellation(id: 0, cancelInFlight: false) {
+        let request = SFSpeechAudioBufferRecognitionRequest()
+        for try await result in await environment.speechClient.startTask(request) {
+          await send(.speech(.success(result.bestTranscription.formattedString)), animation: .linear)
+        }
```

2. Run the same steps

Notice that the 'Alive Tasks' is at 1 instead of zero

 <img width="675" alt="Screen Shot 2022-09-10 at 9 30 51 PM" src="https://user-images.githubusercontent.com/2343/189512763-346c5716-fdc0-4018-a5b6-3799d60ab815.png">

### The Composable Architecture version information

95cc28a0ded8ed9b530266c080c5675f053c69bc

### Destination operating system

iOS 16.0

### Xcode version information

Version 14.0 (14A309)

### Swift Compiler version information

```shell
swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
Target: x86_64-apple-macosx12.0
```

**Comment by mbrandonw** [comment]
Hey @rcarver, sorry I didn't see this when it came in. We will take a look soon. Thanks for filing it!

**Comment by mbrandonw** [comment]
I was able to reproduce the leak and write a test for it, and I think I've got a fix [here](https://github.com/pointfreeco/swift-composable-architecture/compare/cancellation-leak?expand=1). I want to chat about this with Stephen, but hopefully can get a fix into main somewhat soon.

**Comment by rcarver** [comment]
🙌 I'll do some more profiling in my app when this hits `protocol-beta`

**Comment by rcarver** [comment]
@mbrandonw confirmed fixed in SpeechRecognition and improved in my app. But the app still leaks tasks like crazy, I'll do some more digging.
