### ISSUE TITLE
Build Issue with TestStore after Updating to Swift 5.7, Xcode 14

### ISSUE THREAD

**Issue by ajdali** [pointfreeco/swift-composable-architecture#1382]
### Description

I updated Xcode to Xcode 14, and the TestStore file in the Composable architecture dependency is not pulling the extension duration. My machine requires that I run on macOS 12 until 13 is officially supported. What should I do in this case?

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues).

### Expected behavior

Expected to build my project successfully

### The Composable Architecture version information

main

### Destination operating system

macOS 12.5.1

### Xcode version information

Xcode 14

### Swift Compiler version information

```shell
swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
Target: x86_64-apple-macosx12.0
```

**Comment by stephencelis** [comment]
@ajdali This should be fixed on `main` already from this PR 5 days ago:

https://github.com/pointfreeco/swift-composable-architecture/pull/1351

We've also done a release since then.

Can you let us know what specific commit SHA your `main` is pointed to?

**Comment by ajdali** [comment]
Hey @stephencelis i updated the dependency to the latest and this resolved the issue. thanks for the prompt response
