### ISSUE TITLE
Weird animation when dismissing optional bottom sheet from parent

### ISSUE THREAD

**Issue by tyler927** [pointfreeco/swift-composable-architecture#1383]
### Description

I am wanting to use the new iOS 16 `presentationDetents` to show a bottom sheet, and then when the user taps on a button inside it, to dismiss it, and then run some actions in the parent. 

But doing this using TCA results in some weird animations when dismissing it. Almost like it goes full screen, then dismisses. 

[Screen capture.](https://user-images.githubusercontent.com/10719676/189963256-f9d62516-c81d-455b-8df6-487106b47a50.mp4)

Definitely possible I am doing this wrong and it's not an actual issue, but I couldn't find any case studies or examples of programmatically dismissing a modal from a parent reducer. 

This bug also only seems to affect the new "bottom sheet" modals, and not regular full screen modals, so also possible it's a SwiftUI bug.

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues).

### Expected behavior

Dismiss animation matches "vanilla" SwiftUI.

### Actual behavior

Weird animation while dismissing bottom sheet. 

### Steps to reproduce

Copy and paste this into a new iOS 16 project with TCA on the `protocol-beta` branch (also tested on `main`)

```swift
import SwiftUI
import ComposableArchitecture

struct Content: ReducerProtocol {
  struct State: Equatable {
    var optionalSheet: ContentSheet.State?
    
    var isSheetPresented: Bool { self.optionalSheet != nil }
  }
  
  enum Action {
    case optionalSheet(ContentSheet.Action)
    case setSheet(isPresented: Bool)
  }
  
  var body: some ReducerProtocol<State, Action> {
    Reduce { state, action in
      switch action {
      case .setSheet(isPresented: true):
        state.optionalSheet = ContentSheet.State()
        return .none
        
      case .setSheet(isPresented: false):
        state.optionalSheet = nil
        return .none
        
      case .optionalSheet(.saveAndDismiss):
        // Would like to run some other things here
        return .task {
          .setSheet(isPresented: false)
        }
        
      case .optionalSheet:
        return .none
      }
    }
    .ifLet(\.optionalSheet, action: /Action.optionalSheet) {
      ContentSheet()
    }
  }
}

struct ContentView: View {
  let store: StoreOf<Content>
                
  var body: some View {
    WithViewStore(store) { viewStore in
      ZStack {
        Color.red
        Button("Open") {
          viewStore.send(.setSheet(isPresented: true))
        }
      }
      .sheet(
        isPresented: viewStore.binding(
          get: \.isSheetPresented,
          send: Content.Action.setSheet(isPresented:)
        )
      ) {
        IfLetStore(
          self.store.scope(
            state: \.optionalSheet,
            action: Content.Action.optionalSheet
          )
        ) {
          ContentSheetView(store: $0)
        }
      }
    }
  }
}

struct ContentSheet: ReducerProtocol {
  struct State: Equatable {
    
  }
  
  enum Action {
    case saveAndDismiss
  }
  
  func reduce(into state: inout State, action: Action) -> Effect<Action, Never> {
    switch action {
    case .saveAndDismiss:
      return .none
    }
  }
}

struct ContentSheetView: View {
  let store: StoreOf<ContentSheet>
  
  var body: some View {
    WithViewStore(store) { viewStore in
      ZStack {
        Color.purple
        Button("Close") {
          viewStore.send(.saveAndDismiss)
        }
      }
      .presentationDetents([.medium])
      .presentationDragIndicator(.visible)
    }
  }
}

```

Full test project with "vanilla" version working as expected: 
[EmptyTCA.zip](https://github.com/pointfreeco/swift-composable-architecture/files/9559291/EmptyTCA.zip)

### The Composable Architecture version information

protocol-beta

### Destination operating system

iOS 16

### Xcode version information

Xcode 14 RC

**Comment by tgrapperon** [comment]
When you dismiss, it sets `state.optionalSheet` to `nil`, and as a result, the presented view is dismissed, but the presented `IfLetStore` also disappears. The sheet being dismissed is then empty and it lose `presentationDetents`, which translates into what you're likely experiencing (I can't play you video for some reason, but I imagine that this is what happens).

The trick is to keep the last non-nil value `IfLetStore` has seen a default to this value if its state becomes `nil`.

The upcoming presentation and navigation updates will likely handle this automatically.

**Comment by tyler927** [comment]
Okay yep that definitely sounds like what is happening, and that does fix it! 
Thanks for linking that discussion and fix to me @tgrapperon 
I'll close this, and can't wait to see the new navigation updates 🙂

**Comment by florianldt** [comment]
I allow myself to reopen this issue instead of recreating a new one as I am still experiencing the issue. Using the same code provided by @tyler927 with the `v0.49.1`.

Am I wrong to be using the extension provided like?

```swift
IfLetStore(
    self.store.scope(
        state: { state in Optional.lastWrappedValue(state.optionalSheet) },
        action: Content.Action.optionalSheet
     )
 ) {
    ContentSheetView(store: $0)
 }
```

**Comment by iampatbrown** [comment]
@florianldt The reason it's not working is because `Optional.lastWrappedValue(state.optionalSheet)` is getting recreated every time `toChildState` gets called, so it is unable to store the `lastWrapped` value.

The following would work:
```swift
self.store.scope(
  state: \.optionalSheet,
  action: Content.Action.optionalSheet
)
.scope(state: Optional.lastWrappedValue)
```

Though I'd probably to use this helper from the `navigation` branch: https://github.com/pointfreeco/swift-composable-architecture/blob/d69fc4b03d509b9df26ebc52e5e0c3f8d0df6456/Sources/ComposableArchitecture/Internal/OptionalCache.swift#L5-L11

Which would look like this:
```swift
self.store.scope(
  state: returningLastNonNilValue(\.optionalSheet),
  action: Content.Action.optionalSheet
)
```

**Comment by florianldt** [comment]
Awesome thank you for providing the solution.
