### ISSUE TITLE
WithAnimation Compilation Error

### ISSUE THREAD

**Issue by barksten** [pointfreeco/swift-composable-architecture#1387]
### Description

Compiler error ```Conflicting arguments to generic parameter 'Result' ('Void' vs. 'ViewStoreTask')``` when using withAnimation block.

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues).

### Expected behavior

The code should compile

### Actual behavior

Compiler error ```Conflicting arguments to generic parameter 'Result' ('Void' vs. 'ViewStoreTask')``` when using withAnimation block.

Workaround is to get result from send as:
```
_ = viewStore.send(.buttonTapped)
```

### Steps to reproduce

```swift
import ComposableArchitecture
import SwiftUI

struct AppState: Equatable {}
enum AppAction {
    case buttonTapped
}
struct AppEnvironment {}

let reducer = Reducer<AppState, AppAction, AppEnvironment> { _, _, _ in return .none }

struct SwiftUIView: View {
    let store: Store<AppState, AppAction> = Store(initialState: .init(), reducer: reducer, environment: .init())
    var body: some View {
        WithViewStore(self.store, observe: { $0 }) { viewStore in
            Button("Test") {
                withAnimation {
                    viewStore.send(.buttonTapped)
                }
            }
        }
    }
}

struct SwiftUIView_Previews: PreviewProvider {
    static var previews: some View {
        SwiftUIView()
    }
}

```

### The Composable Architecture version information

works with versions up to 0.38. Errors from 0.39 and up to main

### Destination operating system

verified with iOS 15 and above

### Xcode version information

Version 14.0 (14A309)

### Swift Compiler version information

```shell
swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
Target: arm64-apple-macosx12.0
```

**Comment by stephencelis** [comment]
@barksten This API change was for Swift concurrency, but is related to Swift's inability to ignore unused variables through continuations:

https://github.com/apple/swift/issues/57477

So this is a general error you will come across with using continuation-style functions like `withAnimation`.

The fix is to explicitly ignore the result:

```diff
-withAnimation {
+_ = withAnimation {
   viewStore.send(.buttonTapped)
 }
```

Or:

```diff
 withAnimation {
-  viewStore.send(.buttonTapped)
+  _ = viewStore.send(.buttonTapped)
 }
```

Or better yet, use the `animation` parameter of `ViewStore.send`, to flatten things:

```diff
-withAnimation {
-  viewStore.send(.buttonTapped)
-}
+viewStore.send(.buttonTapped, animation: .default)
```
