### ISSUE TITLE
OpenURL on protocol branch has issues with catalyst

### ISSUE THREAD

**Issue by PorterHoskins** [pointfreeco/swift-composable-architecture#1428]
### Description

The new additions to openURL for the protocol branch don’t build on Mac Catalyst. 

`'shared' is unavailable in Mac Catalyst`
`'NSWorkspace' is unavailable in Mac Catalyst `
`'open(_:configuration:completionHandler:)' is unavailable in Mac Catalyst `

### Checklist

- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues).

### The Composable Architecture version information

protocol

### Destination operating system

Mac Catalyst

**Comment by tgrapperon** [comment]
Indeed, Catalyst apps can import a subset of `AppKit`, so this check should probably performed after `UIKit`, or one can use the more discriminant `targetEnvironment(macCatalyst)`

**Comment by stephencelis** [comment]
Thanks for the heads-up! We should probably have had Catalyst CI already.
