### ISSUE TITLE
Test fails on device but not in simulator

### ISSUE THREAD

**Issue by pcolton** [pointfreeco/swift-composable-architecture#148]
**Describe the bug**
I'm using the VoiceMemo tests in my own version of a voice recorder. The tests are failing on device but not in simulator. Seems related to receiving actions before they were expected.

**To Reproduce**
Here is the VoiceMemo app in its own project and fails tests on device. The screenshot as a hint to what might be going on?

[device-test.zip](https://github.com/pointfreeco/swift-composable-architecture/files/4696866/device-test.zip)

**Screenshots**

<img width="607" alt="Screen Shot 2020-05-28 at 9 44 52 AM" src="https://user-images.githubusercontent.com/92073/83169474-f0604b00-a0c7-11ea-9aa2-0aca6d289ff7.png">

**Environment**
 - Xcode 11.5
 - iOS 13.5
 - TCA 0.2 and 0.3

**Comment by stephencelis** [comment]
@pcolton You ever manage to repro with our repo?

**Comment by pcolton** [comment]
I reproduced with the TCA VoiceMemo app unmodified. It’s the zip I included. 

-Paul

**Comment by pcolton** [comment]
It seems I can't test the actual TCA repo directly as there's no way for me to sign the library when testing the specific VoiceMemos app, but as I mentioned, I just extracted that demo as its own app and it fails in the exact same way my own app is failing on-device testing. Note that other tests are fine, it's something specific to these tests, and it seems it might be related to the `DispatchQueue.testScheduler`.

FYI, this is the Xcode error when I try to test TCA VoiceMemos on my device:

`
Showing All Messages
VoiceMemos.app (2763) encountered an error (Failed to load the test bundle. (Underlying error: The bundle “VoiceMemosTests.xctest” couldn’t be loaded because it is damaged or missing necessary resources. The bundle is damaged or missing necessary resources. dlopen_preflight(/var/containers/Bundle/Application/515DF2D4-D817-4C4A-B4C2-64385BF9BE50/VoiceMemos.app/PlugIns/VoiceMemosTests.xctest/VoiceMemosTests): no suitable image found.  

Did find:
	/var/containers/Bundle/Application/515DF2D4-D817-4C4A-B4C2-64385BF9BE50/VoiceMemos.app/PlugIns/VoiceMemosTests.xctest/VoiceMemosTests: code signature in (/var/containers/Bundle/Application/515DF2D4-D817-4C4A-B4C2-64385BF9BE50/VoiceMemos.app/PlugIns/VoiceMemosTests.xctest/VoiceMemosTests) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.))
`

**Comment by pcolton** [comment]
Ok, I was able to open the TCA VoiceMemos project directly, I just had to add a Plist.info file to the Tests so it wold properly sign, then I could run tests on my device. They fail again:

<img width="333" alt="image" src="https://user-images.githubusercontent.com/92073/83316173-4375f300-a1d9-11ea-972e-2a8b8cd0e50f.png">

For the `testPlayMemoHappyPath`, the error was:

<img width="409" alt="image" src="https://user-images.githubusercontent.com/92073/83316208-73bd9180-a1d9-11ea-8710-3b188220af92.png">

**Comment by pcolton** [comment]
And stack trace on the first `self.scheduler.advance(by: 1)` in that test...

<img width="400" alt="image" src="https://user-images.githubusercontent.com/92073/83316420-74a2f300-a1da-11ea-9401-71c6baee8a45.png">

**Comment by pcolton** [comment]
Seems like `stride` is way off?

<img width="615" alt="image" src="https://user-images.githubusercontent.com/92073/83316469-cb103180-a1da-11ea-999f-6164e3a2ec62.png">

**Comment by pcolton** [comment]
I printed out stride and delta for simulator and device, hope some of this helps.

simulator:

> Stride(magnitude: 1000000000) Stride(magnitude: 500000000)
> Stride(magnitude: 500000000) Stride(magnitude: 500000000)

device:

Stride(mag

> Stride(magnitude: 1000000000) Stride(magnitude: 12000000)
> Stride(magnitude: 988000000) Stride(magnitude: 12000000)
> Stride(magnitude: 976000000) Stride(magnitude: 12000000)
> Stride(magnitude: 964000000) Stride(magnitude: 12000000)
> Stride(magnitude: 952000000) Stride(magnitude: 12000000)
> Stride(magnitude: 940000000) Stride(magnitude: 12000000)
> Stride(magnitude: 928000000) Stride(magnitude: 12000000)
> Stride(magnitude: 916000000) Stride(magnitude: 12000000)
> Stride(magnitude: 904000000) Stride(magnitude: 12000000)
> Stride(magnitude: 892000000) Stride(magnitude: 12000000)
> Stride(magnitude: 880000000) Stride(magnitude: 12000000)
> Stride(magnitude: 868000000) Stride(magnitude: 12000000)
> Stride(magnitude: 856000000) Stride(magnitude: 12000000)
> Stride(magnitude: 844000000) Stride(magnitude: 12000000)
> Stride(magnitude: 832000000) Stride(magnitude: 12000000)
> Stride(magnitude: 820000000) Stride(magnitude: 12000000)
> Stride(magnitude: 808000000) Stride(magnitude: 12000000)
> Stride(magnitude: 796000000) Stride(magnitude: 12000000)
> Stride(magnitude: 784000000) Stride(magnitude: 12000000)
> Stride(magnitude: 772000000) Stride(magnitude: 12000000)
> Stride(magnitude: 760000000) Stride(magnitude: 12000000)
> Stride(magnitude: 748000000) Stride(magnitude: 12000000)
> Stride(magnitude: 736000000) Stride(magnitude: 12000000)
> Stride(magnitude: 724000000) Stride(magnitude: 12000000)
> Stride(magnitude: 712000000) Stride(magnitude: 12000000)
> Stride(magnitude: 700000000) Stride(magnitude: 12000000)
> Stride(magnitude: 688000000) Stride(magnitude: 12000000)
> Stride(magnitude: 676000000) Stride(magnitude: 12000000)
> Stride(magnitude: 664000000) Stride(magnitude: 12000000)
> Stride(magnitude: 652000000) Stride(magnitude: 12000000)
> Stride(magnitude: 640000000) Stride(magnitude: 12000000)
> Stride(magnitude: 628000000) Stride(magnitude: 12000000)
> Stride(magnitude: 616000000) Stride(magnitude: 12000000)
> Stride(magnitude: 604000000) Stride(magnitude: 12000000)
> Stride(magnitude: 592000000) Stride(magnitude: 12000000)
> Stride(magnitude: 580000000) Stride(magnitude: 12000000)
> Stride(magnitude: 568000000) Stride(magnitude: 12000000)
> Stride(magnitude: 556000000) Stride(magnitude: 12000000)
> Stride(magnitude: 544000000) Stride(magnitude: 12000000)
> Stride(magnitude: 532000000) Stride(magnitude: 12000000)
> Stride(magnitude: 520000000) Stride(magnitude: 12000000)
> Stride(magnitude: 508000000) Stride(magnitude: 12000000)

**Comment by pcolton** [comment]
Testing with the latest master (as of June 4, 2020), this issue seems to have been fixed. 👍

**Comment by pcolton** [comment]
Since I the fix is on master and I assume this will be part of 0.4.0, I'll close this ticket. Thanks.
