### ISSUE TITLE
Todos delete bug

### ISSUE THREAD

**Issue by kaandedeoglu** [pointfreeco/swift-composable-architecture#150]
Not sure if this is SwiftUI bug or a CA one. 

- Complete a todo while in edit mode
- Before the sorting kicks in, swipe to reveal the `Delete` button
- After the sorting, hit delete
- The item in the old position gets deleted

**Screenshots**
![bug](https://user-images.githubusercontent.com/1566836/83198703-04479380-a140-11ea-9c55-e7c51d22f85a.gif)

**Environment**
 - Xcode 11.5
 - Swift 5.3
- Catalina

**Comment by stephencelis** [comment]
The sorting/editing behavior of SwiftUI definitely has some quirks we've noticed. This bug would likely exist in vanilla SwiftUI, too, in which case we think we should probably leave it as is. What do you think?

**Comment by kaandedeoglu** [comment]
It definitely makes sense, let’s close this for the time being then. If i ever find the motivation to try to reproduce this is Vanilla swift and observe that it’s CA specific, I’ll re-open 😀

**Comment by stephencelis** [comment]
Gonna label with "apple bug" just in case anyone is curious to dig deeper 😆
