### ISSUE TITLE
Behavior variance of ReducerProtocol Effects

### ISSUE THREAD

**Issue by JacksonUtsch** [pointfreeco/swift-composable-architecture#1508]
### Description

It seems using `ReducerProtocol` has changed the behavior of `Effect`. I am quite confused, am I missing something silly, perhaps on how to use `@Dependency`? It may be isolated to using the function requirement rather than `body` but I have not tested.

I have asserted the `liveValue` is being used. We should expect effects here.

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

I expect to receive effects from the client.

### Actual behavior

Only in using the `ReducerProtocol` I do not receive effects.

### Steps to reproduce

This code below can be run as an independent application. The first `@main` uses the traditional TCA usage while the second uses the `ReducerProtocol` Notice the behavior of the apps are different. The subscription to the publisher on the second is not being received.

```swift
import Combine
import ComposableArchitecture
import Foundation
import SwiftUI

// MARK: Traditional

@main
struct TestApp: App {
  var body: some Scene {
    WindowGroup {
      ContentView(
        viewStore: .init(.init(initialState: .init(count: 0), reducer: Main().reducer, environment: AClient.liveValue), removeDuplicates: { _,_ in false }))
    }
  }
}

struct ContentView: View {
  @ObservedObject var viewStore: ViewStore<Main.State, Main.Action>

  var body: some View {
    VStack {
      Text("Count: \(viewStore.state.count)")

      Button("Send") {
        viewStore.send(.send)
      }
    }
    .padding()
    .onAppear {
      viewStore.send(.subscribe)
    }
  }
}

struct Main {
  struct State {
    var count: Int
  }

  enum Action {
    case subscribe
    case incr
    case send
  }

  @Dependency(\.aclient) var aclient

  let reducer = Reducer<State, Action, AClient> { state, action, environment  in
    switch action {
    case .subscribe:
      return environment.subscribe()
        .map { _ in Action.incr }
        .eraseToEffect()
    case .incr:
      state.count += 1
    case .send:
      environment.send()
    }
    return .none
  }
}

struct AClient {
  var subscribe: () -> AnyPublisher<Void, Never>
  var send: () -> Void
}

extension AClient {
  static var testValue: AClient {
    .liveValue
  }
}

extension AClient {
  static var liveValue: AClient {
    let publisher = PassthroughSubject<Void, Never>()
    return Self(
      subscribe: { publisher.eraseToAnyPublisher() },
      send: { publisher.send(()) }
    )
  }
}

// MARK: ReducerProtocol Implementation

extension AClient: TestDependencyKey {}
extension AClient: DependencyKey {}

extension DependencyValues {
  var aclient: AClient {
    get { self[AClient.self] }
    set { self[AClient.self] = newValue }
  }
}

extension Main: ReducerProtocol {
  func reduce(into state: inout State, action: Action) -> Effect<Action, Never> {
    switch action {
    case .subscribe:
      return aclient.subscribe()
        .map { _ in Action.incr }
        .eraseToEffect()
    case .incr:
      state.count += 1
    case .send:
      aclient.send()
    }
    return .none

  }
}

@main
struct TestApp: App {
  var body: some Scene {
    WindowGroup {
      ContentView(viewStore: .init(.init(initialState: .init(count: 0), reducer: Main()), removeDuplicates: { _,_ in false }))
    }
  }
}
```

### The Composable Architecture version information

0.42.0

### Destination operating system

macOS

### Xcode version information

Xcode 14.0.1

### Swift Compiler version information

```shell
1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
Target: x86_64-apple-macosx12.0
```

**Comment by tgrapperon** [comment]
Hey @JacksonUtsch.
This is because each time you're accessing `AClient.liveValue`, you're creating a new value with a new `PassThroughSubject`, so you end-up messaging the wrong instance. In the first case, you did capture one value when you created your `ContentView`.
You can fix this by storing the `liveValue` instance:
```swift
extension AClient {
  static var liveValue: AClient = {  // add `=`
    let publisher = PassthroughSubject<Void, Never>()
    return Self(
      subscribe: { publisher.eraseToAnyPublisher() },
      send: { publisher.send(()) }
    )
  }()                                // add `()` 
}
```

**Comment by JacksonUtsch** [comment]
Ah that is great it was just a silly mistake on my part! I appreciate the help. Thought it might be something small.

**Comment by stephencelis** [comment]
This is an easy enough mistake that we should probably think about it more... I think @tgrapperon pointed out that SwiftUI caches environment values on first access, so we should maybe do the same.

**Comment by tgrapperon** [comment]
@stephencelis I think this is what I deduced when I spotted `@Environment` accessing `Equatable` conformance of one of my `Environment` value, which makes sense only if you have two values to compare. So I think that `@Environment` keeps one value around, not to return it, but to compare it with the new one it extracts from `EnvironmentValues` an decide if it needs to invalidate the `View`.
Given the way TCA works, I think the safest would probably to save the default on first access in `DependenciesValue` if no explicit value was found. I feel it should work as expected regarding `.tranformDependencies` and `.dependencies`. I also think that this is what SwiftUI does, but I don't have any direct proof of that yet. I think this is required if they want to correctly diff callable dependencies like `dismiss` for example. Wrapping functions in structs with `callAsFunction` is not something we're currently doing, but this is only required if diffing is involved, which is not the case yet for TCA.
I can prepare a PR where dependencies values are cached at the `DependenciesValue`'s level on first access.

**Comment by tgrapperon** [comment]
@stephencelis Well, it is not as straightforward as I initially though, as you effectively need to be able to mutate `DependencyValue` on `get` and from any task.

**Comment by stephencelis** [comment]
@tgrapperon I think to support this we'd need to break "out" of the safety of the task local to some fallback mutable store.

**Comment by tgrapperon** [comment]
I'm slightly worried about introducing a necessary lock. But performance may not be impacted that much. I'll prepare a PR and we'll check.

**Comment by stephencelis** [comment]
@tgrapperon I think worst case we could detect the problem in debug builds and runtime warn instead.

**Comment by tgrapperon** [comment]
@stephencelis This is something that I envisaged, but I don't think it can work without wrapping closures dependencies in structs to compare successive values (nor drilling down into dependencies using nested `KeyPath`). And for this to work, we need some fallback storage anyway. I'll sketch something and we'll probably see more clearly what are the edge cases/limitations.

**Comment by iampatbrown** [comment]
@tgrapperon I've been using a version of `DependenciesValues` that works with a lock so I can use it in a non TCA project. Haven't checked performance though but it seems fine so far.

**Comment by JacksonUtsch** [comment]
@stephencelis Good to know I'm not the only one, I've sadly made this mistake before this occurrence as well 🙈

**Comment by tgrapperon** [comment]
I've submitted #1510. Let me know what you think.
