### ISSUE TITLE
Broken Dependency list link

### ISSUE THREAD

**Issue by Muhammed9991** [pointfreeco/swift-composable-architecture#1522]
### Description

Just a heads up. The dependency list link is broken. I’ve only checked the documentation for main. See https://pointfreeco.github.io/swift-composable-architecture/main/documentation/composablearchitecture/dependencymanagement#Registering-your-own-dependencies

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

**Comment by mbrandonw** [comment]
This may have been an intermittent problem because it seems fine right now. Can you double check that it works for you?

**Comment by Muhammed9991** [comment]
![image](https://user-images.githubusercontent.com/80204376/196286537-911aeed8-f369-4139-b1ed-bb888d8a7ac1.png)

**Comment by Muhammed9991** [comment]
It's been like since reducer protocol was released. Didn't get chance to report it until now.

**Comment by mbrandonw** [comment]
Hi @Muhammed9991, Stephen explains why that link is broken and why we just decided to remove it in this PR: #1523

**Comment by Muhammed9991** [comment]
Ahh fair enough. Hopefully there's a fix soon.
