### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by pteasima** [pointfreeco/swift-composable-architecture#16]
Continuing a discussion from the private repo between @opsb, @stephencelis and myself. I still think that adding explicit support for something like Elm's subscriptions is desirable.

Context (using the MotionManager example):
 - Subscriptions are long running effects whose lifecycle is determined purely based on the **latest state**. They are evaluated after each state change, diffing against the old subscriptions and cancelling old ones /  subscribing new ones as appropriate. Think: whenever the latest call to `subscriptions` returns `environment.motionManager.deviceMotionUpdates()`, we are sure to be observing motion updates.
 - This is more powerful than the current way of doing long running effects. Currently, the lifecycle of long running effects depends on the **history of sent Actions**. Think: we are observing motion updates if in the past there was an Action (e.g. `.onAppear`) that caused reducer to return `environment.motionManager.create()` and an Action that caused reducer to return `environment.motionManager.startDeviceMotionUpdates` and there was no subsequent actions that caused reducer to return `environment.motionManager.stopDeviceMotionUpdates()`. In some usecases, there could also be a subsequent action that ended up cancelling some of those effects.
- An app that properly uses subscriptions can recover from **time-travel**, i.e. jumping to any state.
- Time-travel is the strongest but not the only argument. Deriving more of an app's behavior from the latest state as opposed to the whole history of execution greatly reduces complexity and is ideologically in-line with the latest trends (SwiftUI vs. UIKit, realtime databases like Firestore vs. polling a database) and the philosophy of Elm/composable-architecture.
- `subscriptions` can be an optional part of the Reducer type and can support all of the same composability features. Most of the time, adopting subscriptions will result in less client code.
- explicit support for subscriptions is more powerful than anything that can be achieved with higher-order reducers (since those still rely on at least a single "bootstrap" action making it through the particular child reducer)
- Cons include:
   - larger footprint for the composable-architecture framework
   - another concept to explain to new users
   - a naming conundrum, where `Reducer` is no longer "just a Reducer"
   - sometimes its more practical to use regular Effects (think GET request in `onAppear`), so some apps may still not be time-travel-proof

Ive copied my prototype implementation from the old private repo to https://github.com/pteasima/swift-composable-architecture/pull/1 . This doesnt yet have all the required functionality, especially the part around diffing old and new subscriptions. Its there to show that the changes required to the library arent that big, impact on existing client code can be 0, and to start a discussion on future steps.

Thoughts?

**Comment by stephencelis** [comment]
Hey @pteasima! Thanks for getting the conversation going.

Those new to the conversation can note that an approximation is Elm-like subscriptions is included as a case study in the demo app here: https://github.com/pointfreeco/swift-composable-architecture/blob/4d4809faf386b0cacf73e62e699352576d8dadb8/Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-ElmLikeSubscriptions.swift#L13-L34

It has the limitation that subscriptions require at least one action is sent to the reducer to "kick things off," which you note above.

A nice thing about time travel in general is that in implementations like @finestructure's State Surfing, playback from history can still allow for powerful debugging. It's definitely a bummer that "rewind" can become a bit broken for long-running effects, but replaying again from a fresh store isn't such a terrible trade-off for now.

I think our main concerns are the cons you covered above, but we'll let folks discuss a bit and see if anyone has ideas on how to address! 😄

One thing I wonder is what would it take to define such a feature in its own opt-in library? This would be one way to address the first two cons. What kinds of changes would need to be made for this to work, though? A more flexible `Store` API? It might not be possible, but it's an angle that should be explored.

**Comment by pteasima** [comment]
> replaying again from a fresh store isn't such a terrible trade-off for now 
You mean that when exiting time-travel in a particular state, we should replay all actions that got us from up startup to there? Im struggling to picture this working in the general case. Elm doesnt run Commands when time-traveling, and probably for good reasons. If you replay all actions and re-run all commands it could cause havoc in your environment. Think: a server increments a counter on every request, Firestore updates ServerTimestamp value to current server time, ... Plus doing so very fast may also produce unexpected results. Definitelly down to explore this, since I agree that the current minimal API without subscriptions is better.

Afaik subscriptions weren't part of Elm since version 1. Can anybody link to the reasoning for introducing subscriptions to Elm? A quick google didnt find anything :(

> what would it take to define such a feature in its own opt-in library?

Its already "opt-in" in the sense that `subscriptions` has a default value. But at least in my example, the implementation is baked deeply into `Reducer` and `Store` types.

An opt-in library could in theory provide a new `ReducerWithSubscriptions` type. This type could maintain separate `reduce` and `subscriptions` private vars for use when composing. Its unclear how this would interact with the Store.
Best-case scenario it could just have a  `public var reducer: Reducer` which would do the trick from the Subscriptions case study. Think: while composing, use `ReducerWithSubscriptions`, but then hand it to a `Store` as a plain `Reducer`. My worry here is that any additional tooling using higher order reducers (like a time-travel debugger) would have to be duplicated to support this `ReducerWithSubscriptions` type (since we only want to turn it into a plain `Reducer` at the very top of the chain).  This may not be a bad thing though, since theres probably special considerations on how to handle subscriptions in this tooling anyway (in case of TimeTravelDebugger, all subscriptions should be cancelled when entering time-travel, so that they get resubscribed when leaving time-travel, and thus can send any initial values again).

I feel like my thinking is limited by what I already tried. Hopefully someone can bring a breath of fresh air.

**Comment by stephencelis** [comment]
> Hopefully someone can bring a breath of fresh air.

Sounds good!

One thing we wanna think about is how conversations like this should be managed in an open source library. Open issues can sometimes cast a repository as having a lot of...issues 😄 Using issues for both bugs and conversations can muddy things a bit. For now I think we'll tag these kinds of threads with "Discussion," keep them open for a lil while, and then close them where the conversation can continue but doesn't overtake actual issues coming in. We're open to any suggestions here, as well!

**Comment by pteasima** [comment]
Sounds good, dont let this become a nuisance. Im not one to be offended if you close my issue 😀

Was actually gonna label this issue but I think you need to predefine some labels.

**Comment by finestructure** [comment]
@pteasima I haven't had a chance to follow this interesting discussion in depth so I just wanted to ask if I my understanding is correct: In the motion manager example as it is you wouldn't really be able to time travel/state surf in the way Historian does it by sending state snapshots because the subscription isn't actually recorded in the state.

That's actually a bit like network requests with Historian, where you don't really get to replay the sending of the event - unless you argue there's no difference if you send an effect or if you simply time travel to the response.

What you're proposing is encoding the subscription in the state such that time travel to times where the subscription is active/inactive would depend entirely on that state, right?

I think that's kind of how I would have imagined it working, although I have yet to try adding state surfing to the motion manager example or something similar.

Re discussing: @stephencelis have you considered opening a section in the Swift forums under [Related Projects](https://forums.swift.org/c/related-projects/25)? That might be a nice place for discussions.

**Comment by stephencelis** [comment]
> Re discussing: @stephencelis have you considered opening a section in the Swift forums under [Related Projects](https://forums.swift.org/c/related-projects/25)? That might be a nice place for discussions.

Ha we looked at that, though it's a bit of a ghost town in there for the most part. Will definitely keep it in mind as an option, thought!

**Comment by pteasima** [comment]
@finestructure I re-read (all 3 of 😄) your repos and am pretty confident that I understand it now. Still, if you can please review this much simpler (and less powerful) setup that enables time-travel locally using a slider without the need to conform to any protocols etc. 

```
import Foundation
import ComposableArchitecture
import SwiftUI

struct TimeTravelState<AppState> {
  init(_ state: AppState) {
    self.stack = [state]
  }
  var stack: [AppState] //nonempty
  var isTimeTraveling: Bool = false
  var currentIndex: Int = 0
  var currentState: AppState {
    return stack[currentIndex]
  }
  mutating func append(_ state: AppState) {
    assert(!isTimeTraveling)
    stack.append(state)
    currentIndex += 1
  }
}

enum TimeTravelAction<AppAction> {
  case app(AppAction)
  case toggleIsTimeTraveling
  case setIndex(Double) //Double because Slider uses floats
}

extension Reducer {
  static func timeTravel<AppState, AppAction, AppEnvironment>(
    appReducer: Reducer<AppState, AppAction, AppEnvironment>
  ) -> Reducer<TimeTravelState<AppState>, TimeTravelAction<AppAction>, AppEnvironment> {
    .init { state, action, environment in
      switch action {
      case .app(let appAction):
        guard !state.isTimeTraveling else { return .none }
        var newAppState = state.currentState
        let appEffect = appReducer(&newAppState, appAction, environment)
        state.append(newAppState)
        return appEffect.map(TimeTravelAction.app)
      case .toggleIsTimeTraveling:
        if state.isTimeTraveling { //commit changes
          state.stack = Array(state.stack[0...state.currentIndex])
        }
        state.isTimeTraveling.toggle()
        return .none
      case .setIndex(let index):
        state.currentIndex = min(state.stack.count - 1, max(0, Int(round(index))))
        return .none
      }
     }
  }
}

fileprivate struct TimeTravelDebuggerViewState: Equatable {
  var isTimeTraveling: Bool
  var currentIndex: Int
  var maxIndex: Double
}
struct TimeTravelDebugger<AppState: Equatable, AppAction, AppView: View>: View {
  let store: Store<TimeTravelState<AppState>, TimeTravelAction<AppAction>>
  let appView: (Store<AppState, AppAction>) -> AppView
  init<AppEnvironment>(
    initialAppState: AppState,
    appReducer: Reducer<AppState, AppAction, AppEnvironment>,
    environment: AppEnvironment,
    appView: @escaping (Store<AppState, AppAction>) -> AppView
  ) {
    self.store = .init(initialState: TimeTravelState(initialAppState), reducer: .timeTravel(appReducer: appReducer), environment: environment)
    self.appView = appView
  }
  
  var body: some View {
    func content(with viewStore: ViewStore<TimeTravelDebuggerViewState, TimeTravelAction<AppAction>>) -> some View {
      func debuggerView() -> some View {
        Slider(value: viewStore.binding(get: { Double($0.currentIndex) }, send: TimeTravelAction.setIndex), in: 0...viewStore.maxIndex)
      }
      return appView(store.scope(state: \.currentState, action: TimeTravelAction.app))
        .onTapGesture(count: 3) {
          viewStore.send(.toggleIsTimeTraveling)
      }
      .overlay(
        viewStore.isTimeTraveling ? AnyView(debuggerView().padding()) : AnyView(EmptyView()),
        alignment: .top
      )
    }
    return WithViewStore(store.scope(state: \TimeTravelState.view), content: content)
  }
}

extension TimeTravelState {
  fileprivate var view: TimeTravelDebuggerViewState {
    return .init(
      isTimeTraveling: isTimeTraveling,
      currentIndex: currentIndex,
      maxIndex: Double(stack.endIndex - 1))
  }
}
```

I wonder if the considerations change in any way when going to something fancy like Historian. In particular, with my solution, theres two very distinct states depending on `isTimeTraveling`. When `isTimeTraveling == false`, app runs as normal. When `isTimeTraveling == true` any actions from app are ignored. This is done in order to not fire any Effects from things like `onAppear` as the user is scrubbing the slider like crazy (consistent with how Elm used to do it, although Im not sure how it is now). However, this also means that you miss some intermediate actions (`.onAppear`, `.recordingButtonTapped`), so your long running Effects arent set up correctly 

Afaik with Historian you jump straight to some state, and you dont ignore anything (so you will still get an `onAppear`, but will still miss the `.recordingButtonTapped`).

> What you're proposing is encoding the subscription in the state 

What Im proposing is using `state.isRecording` to entirely determine whether that Effect should or shouldnt be running: https://github.com/pteasima/swift-composable-architecture/blob/d4acf05762eb43198525c701277fea7b0c23ab9d/Examples/MotionManager/MotionManager/MotionManagerView.swift#L25
This requires adding a new concept modelled after Elm's subscriptions - a mechanisms that derives long running Effects from state after each state change. Not sure if thats what you were asking, so let me know if I need to say more about what subscriptions are.

**Comment by finestructure** [comment]
3 Repos? I thought there were only the generic viewer (Historian) and `HistoryTransceiver` - the thing you integrate in your app 😅 

Anyway, looking through your version is definitely on my todo list! From a quick glance I think it's quite similar. BTW, the protocols only exist to make integration easier and to support adding `HistoryTransceiver` as a library. But I'll definitely need to try out your version in earnest to fully understand what's going on!

**Comment by pteasima** [comment]
those 2 + the example app 😅

I thought Historian and this were similar, so perhaps considerations for subscriptions are the same (jumping to arbitrary states, app needs to get going from there)

**Comment by opsb** [comment]
Hey, just wanted to chime in to say I'm still very interested in this topic. I'm planning on doing a proper exploration but it'll most likely be next week now (I'm currently having a play with approaches around ViewStore). 

> Afaik subscriptions weren't part of Elm since version 1. Can anybody link to the reasoning for introducing subscriptions to Elm? A quick google didnt find anything :(

@pteasima I started using Elm just after this transition, the following is my understanding but may not be 100% accurate. I believe the intent was to move away from Combine style reactive approach and keep side effects/streams closer to the edges of the system. Instead of full FRP style streams subscriptions were introduced as a simpler integration with long running side effects. The main difference being that stream state was entirely eliminated so you can't do things like dedupe, debounce and throttle. The intention was to force more logic into the model/state machine so that less state was hidden in streams.

**Comment by pteasima** [comment]
Interesting. I wasnt around for the FRP days of Elm either 🙁 Might be worth exploring how things were done back then (if an FRP based solution exists, Swift community can take it 😀)

**Comment by klop** [comment]
It seems that what I've described in #20 could be subsumed by this issue. If anyone could confirm that's the case, I'll go ahead in close it. Thanks!

**Comment by opsb** [comment]
@klop having read through #20 I think you're looking at a different case, how to deal with various strategies for the same side effect being triggered repeatedly by user actions. Subscriptions are for listening to a stream of side effects, e.g.  a period of time passing(e.g. every 5 secs) or messages being received on a websocket.

**Comment by finestructure** [comment]
> Ha we looked at that, though it's a bit of a ghost town in there for the most part. Will definitely keep it in mind as an option, thought!

Hah: https://twitter.com/github/status/1258067199379595265

**Comment by stephencelis** [comment]
How timely! We just contacted the Swift Forums admins this morning about setting up a discussion forum there, too.

**Comment by stephencelis** [comment]
> Re discussing: @stephencelis have you considered opening a section in the Swift forums under [Related Projects](https://forums.swift.org/c/related-projects/25)? That might be a nice place for discussions.

We finally got a forum added here: https://forums.swift.org/c/related-projects/swift-composable-architecture/61

We'll also play with GitHub discussions when it's available.

These outlets should serve better for longer-form discussions like this. @pteasima Cool to move discussion there and close this out?

**Comment by pteasima** [comment]
Moved https://forums.swift.org/t/subscriptions/36417
