### ISSUE TITLE
using OpenURLEffect results with the compiler error: Ambiguous use of 'callAsFunction'

### ISSUE THREAD

**Issue by rurza** [pointfreeco/swift-composable-architecture#1619]
### Description

It seems that the compiler doesn't know which version of the `public func callAsFunction(_ url: URL) async` to use.

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [x] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

I'd expect that calling my dependency:
```
return .fireAndForget {
  Task {
    await openURL(URL(string: "https://pointfree.co")!)
  }
}
```
will compile

### Actual behavior

Getting the `Ambiguous use of 'callAsFunction'` error

### Steps to reproduce

<img width="944" alt="Screenshot 2022-11-04 at 13 43 16" src="https://user-images.githubusercontent.com/2467137/199975287-d7db04bc-97cd-4555-98bf-7790b01329bb.png">

### The Composable Architecture version information

0.45.0

### Destination operating system

macOS 12

### Xcode version information

14.1 (14B47)

### Swift Compiler version information

```shell
swift-driver version: 1.62.15 Apple Swift version 5.7.1 (swiftlang-5.7.1.135.2 clang-1400.0.29.51)
Target: arm64-apple-macosx12.0
```

**Comment by mbrandonw** [comment]
The `fireAndForget` function gives you an async context so there's no need to create a `Task`:

```swift
return .fireAndForget {
  await openURL(URL(string: "https://pointfree.co")!)
}
```

Does that work?

**Comment by stephencelis** [comment]
While removing `Task` should help, I think we can also fix, so pushed #1621.

**Comment by rurza** [comment]
Indeed, removing Task helped! My bad 🤦‍♂️And thanks for the commit :)

**Comment by lukeredpath** [comment]
Thanks for the fix - FWIW, I have found, prior to this fix that this compiles:

```swift
.fireAndForget { 
  await openURL(...) 
}
```

But this fails with the same error as the original report:

```swift
.fireAndForget { 
  await openURL(...) 
  await someOtherAsyncFunc()
}
```
