### ISSUE TITLE
Crash when removing element from an array that is paired with a "forEach" reducer

### ISSUE THREAD

**Issue by tvongerlach** [pointfreeco/swift-composable-architecture#165]
**Describe the bug**
My app crashes when removing an element from an array that is combined with a "forEach"  despite the "forEach" reducer occurring before the reducer that removes any elements from the array (this is what the error message tells me to do).

In my case the elements represent timers and this only seems to occur when the timers are active. 

The assertion failure reads `Index out of range. This can happen when a reducer that can remove the last element from an array is then combined with a "forEach" from that array. ...`

**To Reproduce**
[TimerSampleApp.zip](https://github.com/pointfreeco/swift-composable-architecture/files/4721061/TimerSampleApp.zip)

Steps to reproduce: 
1. Run the app
2. Add a couple of timers using the add button in the top right corner
3. Cancel the first timer

This remove is where the crash occurs:
```swift
case .timer(index: let index, action: .cancelTimer):
            state.timers.remove(at: index)
            return .none
```

**Expected behavior**
I'd expect the element to be deleted without the app crashing.

**Screenshots**
![remove-timer-crash](https://user-images.githubusercontent.com/18754377/83596708-30855a80-a51a-11ea-9bbe-5bf4617f51e2.gif)
(This is a gif)

**Other notes**
Given that this only occurs when the timer is active I assume the issue is related to the timer object mutating its own state every second. If this is not a bug, I'd be curious about what I'm doing wrong in my implementation.

**Comment by stephencelis** [comment]
@tvongerlach Using the index-based `forEach` and `ForEachStore` is going to come with complications for any long-living effects that feed actions back into the store when the list can have elements moved or removed. You should be able to get things working by using an `IdentifiedArray` and id-based action instead.

There's an example of this in the Todos demo:

https://github.com/pointfreeco/swift-composable-architecture/blob/648ac98ceccc3476bd63f9628644147af2bc6854/Examples/Todos/Todos/Todos.swift

To better understand the crash, let's say you have timers running at index 0 and index 1:

- Index 0 is canceled and element at 0 is removed
- Element previously at index 1 is now at 0, but its timer effect is still operating at index 1, so when that action is fed in at an interval, it still tries to access the element through index 1

I think we could probably beef up our assertion message to account for long-living effects, though. After the portion you pasted above, it currently has this to nudge folks in the `IdentifiedArray` direction:

> To avoid this and other index-related gotchas, consider using an "IdentifiedArray" of state instead. Or, combine your reducers so that the "forEach" comes before any reducer that can remove elements from its array.

I think "index-related gotchas" is maybe too soft and easy to ignore.

**Comment by stephencelis** [comment]
Updated the language here:

https://github.com/pointfreeco/swift-composable-architecture/pull/157/files#diff-1b51d31977d86442054d879bad6782c7L211-R246

But considering how unsafe index-based `forEach` reducers can be when elements can be moved or removed, we might wanna remove it entirely and _only_ support id-based lists of state...

**Comment by tvongerlach** [comment]
@stephencelis Great. Thanks for the explanation. I'll try out what you've suggested.

**Comment by tvongerlach** [comment]
Really appreciate the help @stephencelis. I'm now using an `IdentifiedArray` following the Todos example. Works beautifully.
