### ISSUE TITLE
ButtonState equality is broken in 0.47.0

### ISSUE THREAD

**Issue by konomae** [pointfreeco/swift-composable-architecture#1687]
### Description

- Checkout 0.47.0 (0a1958115c05978478139105a67a556871ed8e1a)
- Run `AlertsAndConfirmationDialogsTests`
- It fails

<img width="1414" alt="ss" src="https://user-images.githubusercontent.com/1920783/203195501-e4aab00c-8833-4c12-b07d-235257f9dc2c.png">

(This may be a problem on the swiftui-navigation repository side.)

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

It should pass as before 0.46.0

### Actual behavior

```
            // Not equal but no difference detected:
    −       [0]: ButtonState(…)
    +       [0]: ButtonState(…)
            // Not equal but no difference detected:
    −       [1]: ButtonState(…)
    +       [1]: ButtonState(…)
```

### The Composable Architecture version information

0.47.0

### Xcode version information

Version 14.1 (14B47b)

### Swift Compiler version information

```shell
swift-driver version: 1.62.15 Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)
Target: x86_64-apple-macosx13.0
```

**Comment by 3a4oT** [comment]
faced the same issue.

**Comment by mbrandonw** [comment]
Thanks for the issue! Just merged the fix and cut releases for SwiftUINavigation and TCA.
