### ISSUE TITLE
NavigationLink is executed multiple times

### ISSUE THREAD

**Issue by alexanderwe** [pointfreeco/swift-composable-architecture#172]
**Describe the bug**
I am not sure if this bug is exactly the same as described in #66. If so, please feel free to close this issue. 

I am trying to get a detail view navigation working. The view is pushed from a list of data entries. Unfortunately the navigation is executed multiple times and ultimately ending with the view being at the list of all entries again. My code follows the approach described in `Examples/CaseStudies/SwiftUICaseStudies/03-Navigation-LoadThenNavigate`

I do really hope that I did not oversaw something while implementing the behaviour. If so, I am sorry for producing noise in your issues tracker. 

**To Reproduce**
Here is a minimal example that suffers from the same issue as my project code. In my project code the detail view is pushed multiple times, in this examples the detail view is "only" pushed twice. 

```swift

import SwiftUI
import ComposableArchitecture

struct AppState: Equatable {
    var isNavigationActive: Bool = false
    var listData = ["Hello","World"]
}

enum AppAction: Equatable {
     case isNavigationActive(isActive: Bool)
}

struct AppEnvironment { }

let appReducer: Reducer<AppState, AppAction, AppEnvironment> = Reducer { state, action, environment in
    switch action {
    case .isNavigationActive(isActive: true):
        state.isNavigationActive = true
        return .none
        
    case .isNavigationActive(isActive: false):
        state.isNavigationActive = false
        return .none
    }
}

struct RootView: View {
    
    let store = Store(
           initialState: AppState(),
           reducer: appReducer.debug(),
           environment: AppEnvironment()
       )
    
    var body: some View {
        ListView(store: self.store)
    }
}

struct ListView: View {
    let store: Store<AppState, AppAction>
    init(store: Store<AppState, AppAction>) {
        self.store = store
    }
    
    var body: some View {
        WithViewStore(self.store) { viewStore in
            NavigationView {
                List {
                    ForEach(viewStore.listData, id: \.self) { data in
                        NavigationLink(
                            destination: DetailView(text: "This is my detail view"),
                            isActive: viewStore.binding(
                                get: { $0.isNavigationActive },
                                send: AppAction.isNavigationActive(isActive:)
                            )
                        ) {
                            Text(data)
                        }
                    }
                }.navigationBarTitle("Title")
            }
        }
    }
}

struct DetailView: View {
    
    var text: String
    
    var body: some View {
        Text(text)
    }
}
```

**Expected behavior**
I would expect the navigation to only happen once and stay at one of the detail views. 

**Screenshots**
![output](https://user-images.githubusercontent.com/12934015/83921451-a8ec5580-a77e-11ea-80d7-0e7765a9165f.gif)

**Environment**
 - Xcode [11.5]
 - Swift [5.2.2]
 - OS [iOS 13]

**Additional context**
I assume it has something to do with the issues mentioned in #66. But I am not sure about it because I can only see one level of navigation in my use case and not more 2 or more.

**Comment by mbrandonw** [comment]
Yep, sadly this is the same issue :(

If you put this on your view inside the `NavigationView` it will fix it for iPhones:

```swift
.navigationViewStyle(StackNavigationViewStyle())
```

But then iPad screens will be full screen.

Hopefully this bug is fixed in the next iOS!

**Comment by alexanderwe** [comment]
Sad to hear that - really hope that such kind of issues are going to be fixed in the next SwiftUI/iOS version, too.

Thanks a lot for your workaround but one thing I want to mention. I added the code snippet to my minimal working example, but the issue still stays. I don't know if it is worth digging deeper into it, since it seems to be an overall issue, but still wanted to mention it. 
```swift
List {
 ...
}
.navigationViewStyle(StackNavigationViewStyle())
```

**Comment by pcolton** [comment]
@alexanderwe I think there is a logic problem in your code, you are setting isNavigationActive regardless of which item is selected. I updated your code to work, and interestingly enough, for me, I don't see any issues even with `.navigationViewStyle(StackNavigationViewStyle())` commented out:

```swift
import SwiftUI
import ComposableArchitecture

struct Item: Equatable, Hashable, Identifiable {
    var id = UUID()
    var value: String = ""
}

struct AppState: Equatable {
    var selection: Item?
    var listData: IdentifiedArrayOf<Item>
}

enum AppAction: Equatable {
    case setNavigationItem(id: UUID?)
}

struct AppEnvironment { }

let appReducer: Reducer<AppState, AppAction, AppEnvironment> = Reducer { state, action, environment in
    switch action {
        case .setNavigationItem(.none):
            state.selection = nil
            return .none

        case let .setNavigationItem(id: .some(id)):
            state.selection = state.listData[id: id]
            return .none

    }
}

struct ContentView: View {
    
    let store = Store(
           initialState: AppState(listData: IdentifiedArray([Item(value: "Hello"), Item(value: "World")])),
           reducer: appReducer, //.debug(),
           environment: AppEnvironment()
       )
    
    var body: some View {
        ListView(store: self.store)
    }
}

struct ListView: View {
    let store: Store<AppState, AppAction>
    init(store: Store<AppState, AppAction>) {
        self.store = store
    }
    
    var body: some View {
        WithViewStore(self.store) { viewStore in
            NavigationView {
                List {
                    ForEach(viewStore.listData) { data in
                        NavigationLink(
                            destination: DetailView(text: "This is my detail view"),
                            tag: data.id,
                            selection: viewStore.binding(
                                get: { $0.selection?.id },
                                send: AppAction.setNavigationItem(id:)
                            ),
                            label: { Text(data.value) }
                        )
                    }
                }
//                .navigationViewStyle(StackNavigationViewStyle())
                .navigationBarTitle("Title")
            }
        }
    }
}

struct DetailView: View {
    
    var text: String
    
    var body: some View {
        Text(text)
    }
}
```

**Comment by alexanderwe** [comment]
@pcolton Thanks a lot for your fix - it does work in my minimal example here. I still need to check whether it works in my production code. Hope I have time today or tomorrow evening.

May I ask why my version was buggy in that case ? The only real difference I see in your fix is the `tag` in the `NavigationLink`. So you keep track of the selected item. 

Did bug  occurred because I was triggering the `NavigationLink` each time the view was rendered ? 
What I mean:
1. Click on cell
2. Set navigation active -> re-render screen and activate link
3. In the re-render I trigger the NavigationLink for each item because the state says that the navigation is active regardless of the currently rendered row

**Comment by stephencelis** [comment]
@alexanderwe You can add some debug code to `Binding` to get a better idea of what's happening:

```swift
extension Binding {
  func debug(_ prefix: String) -> Binding {
    Binding(
      get: {
        print("\(prefix): getting \(self.wrappedValue)")
        return self.wrappedValue
    },
      set: {
        print("\(prefix): setting \(self.wrappedValue) to \($0)")
        self.wrappedValue = $0
    })
  }
}
```
When you hit a list you'll see that the binding's `get` is called for each row and will be `false` for any row that is _not_ navigated to. This will trigger a pop if you've navigated into the stack. The problem with this is all of your navigation links share the same presentation state, but what you really want is independent presentation state per row, which is exactly what the `tag`/`selection` version gets you.

**Comment by alexanderwe** [comment]
So thank you all @stephencelis, @pcolton, @mbrandonw for your input. The solution by @pcolton works in my production code as well. I was totally unaware of the `(destination:tag:selection)` version of the `NavigationLink`. And thank you all for your explanations. So in the end it was just me making the errors.
