### ISSUE TITLE
Elegant way to bubble up state and error handling

### ISSUE THREAD

**Issue by nielstj** [pointfreeco/swift-composable-architecture#176]
Question regarding bubbling up action for a deep nested state, for example:

* Handling user authenticated  with state structured like this, app > landing> login > 2FA > 
A naive approach in app reducer will be :
```
case let .landing(.login(.twoFactor(.twoFactorResponse(.success(response))))),
         let .landing(.login(.loginResponse(.success(response)))) where !response.twoFactorRequired:
...
```

 * Globally handle 401 (unauthorized) response from remote server.
A naive approach will be handling this in every reducer or combine it to bubble it up to app state.

Is there an elegant solution for such scenarios?  One way i can think of is using long living effects with notification center and combine it with root/app reducer.

**Comment by mbrandonw** [comment]
Hi @nielstj, we are reserving GitHub issues for bug reports and ask that more open-ended discussions happen on the Swift forums: https://forums.swift.org/c/related-projects/swift-composable-architecture/61

Would you be willing to re-open your question there and closing this?

**Comment by nielstj** [comment]
Sure... sorry for the inconvenience.
