### ISSUE TITLE
Failed to build Deprecations.swift

### ISSUE THREAD

**Issue by ChaosCoder** [pointfreeco/swift-composable-architecture#1797]
### Description

My SwiftUI Previews are not rendering in Xcode 14.2, TCA `0.47.2` and `0.48.0` and I get the following Diagnostics:

```
'send' is inaccessible due to '@_spi' protection level

----------------------------------------

CompileDylibError: Failed to build Deprecations.swift

Compiling failed: 'send' is inaccessible due to '@_spi' protection level

/Users/Andreas/Library/Developer/Xcode/DerivedData/ProjectName-alwburtqniqfkmbqauydrqpjjdbp/SourcePackages/checkouts/swift-composable-architecture/Sources/ComposableArchitecture/Internal/Deprecations.swift:925:29: error: 'send' is inaccessible due to '@_spi' protection level
            let task = self.send(fromChildAction(childAction))
                            ^~~~
ComposableArchitecture.Store:6:17: note: 'send(_:originatingFrom:)' declared here
    public func send(_ action: Action, originatingFrom originatingAction: Action? = nil) -> Task<Void, Never>?
```

Building, archiving, etc. work fine. It's only the previews, that are not working anymore.

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

Previews get rendered

### Actual behavior

Diagnostics error (see above)

### The Composable Architecture version information

0.47.2 and 0.48.0

### Xcode version information

14.2

### Swift Compiler version information

```shell
swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0
```

**Comment by tgrapperon** [comment]
Hey @ChaosCoder!
From my experience, `Previews` are quite bad at spotting "metadata" changes like deprecations or files being moved. I usually solve the problem by clearing the build products. Ultimately, restarting Xcode could help. FWIW, I'm able to build previews using 48.0, so I feel this points toward some caching issue on your side.

**Comment by ChaosCoder** [comment]
Indeed, cleaning DerivedData did it for me. Thank you.
