### ISSUE TITLE
FeatureState and FeatureAction

### ISSUE THREAD

**Issue by boudavid** [pointfreeco/swift-composable-architecture#18]
Hey guys,

I've been following the evolution of the TCA from the beginning and using it in my own project by simply copy pasting the code in a framework. Since the library is now open source, I'm actually removing the custom framework in favor of the Swift package so there's a lot of stuff to update.

By looking at the examples provided in the repo, I noticed that the notion of `FeatureState` and `FeatureAction` don't seem to exist anymore and I couldn't find anything on PointFree or in the repo about this. State look to be much more lightweight now (there were a lot of boilerplate with FeatureState) so I was wondering how can I have achieve the same thing ?

**Comment by stephencelis** [comment]
Hi @boudavid!

The Tic tac toe demo in the repo is a multiscreen example that follows this kind of pattern. It also adapts its SwiftUI and UIKit views with more domain-appropriate state and actions in most views/controllers.

> State look to be much more lightweight now (there were a lot of boilerplate with FeatureState) so I was wondering how can I have achieve the same thing ?

Can you clarify your question here with an example? What kind of boilerplate were you dealing with? Does Tic tac toe have the same boilerplate?

**Comment by boudavid** [comment]
> Can you clarify your question here with an example? What kind of boilerplate were you dealing with? Does Tic tac toe have the same boilerplate?

From the PrimeTime app source code in Episode 97 :

```swift
public typealias CounterState = (
  alertNthPrime: PrimeAlert?,
  count: Int,
  isNthPrimeRequestInFlight: Bool,
  isPrimeDetailShown: Bool
)

public struct CounterFeatureState: Equatable {
  public var alertNthPrime: PrimeAlert?
  public var count: Int
  public var favoritePrimes: [Int]
//  public var isNthPrimeButtonDisabled: Bool
  public var isNthPrimeRequestInFlight: Bool
  public var isPrimeDetailShown: Bool
  
//  public var isLoadingIndicatorHidden: Bool

  public init(
    alertNthPrime: PrimeAlert? = nil,
    count: Int = 0,
    favoritePrimes: [Int] = [],
    isNthPrimeRequestInFlight: Bool = false,
    isPrimeDetailShown: Bool = false
  ) {
    self.alertNthPrime = alertNthPrime
    self.count = count
    self.favoritePrimes = favoritePrimes
    self.isNthPrimeRequestInFlight = isNthPrimeRequestInFlight
    self.isPrimeDetailShown = isPrimeDetailShown
  }

  var counter: CounterState {
    get { (self.alertNthPrime, self.count, self.isNthPrimeRequestInFlight, self.isPrimeDetailShown) }
    set { (self.alertNthPrime, self.count, self.isNthPrimeRequestInFlight, self.isPrimeDetailShown) = newValue }
  }

  var primeModal: PrimeModalState {
    get { (self.count, self.favoritePrimes) }
    set { (self.count, self.favoritePrimes) = newValue }
  }
}
```

I was following this pattern for every state in my app which could be huge for state that had sub states. It was also quite cumbersome to the add the getter and setter for the sub states 😅.

I think I'm going to take a better look at the TicTacToe demo to see how it's done. Thanks !

**Comment by stephencelis** [comment]
@boudavid Sadly the PrimeTime app grew into something that is not terribly well factored, state-wise 😅 Its state should ideally be normalized (maybe an exercise for a future episode).
