### ISSUE TITLE
Find better workaround for stale ForEach rows reading from bindings

### ISSUE THREAD

**Issue by mbrandonw** [pointfreeco/swift-composable-architecture#1800]
We recently got an issue #1783 of a crash in a pretty simple SwiftUI view using TCA. The problem is that stale, _removed_ rows from a ForEach will sometimes read from its binding, which means trying to read data from a row no longer in the collection, resulting in a crash.

A fix was attempted in #1784, as well as a refinement in #1785, but unfortunately those lead to a different, and even simpler crash, which was report in #1798. So, we reverted the change.

Fortunately the fix to the original issue is to just use `ForEachStore` because we have baked in [special logic][foreachstore-special-logic] to work around this issue, but it would be nice to come up with a more holistic solution.

[foreachstore-special-logic]: https://github.com/pointfreeco/swift-composable-architecture/blob/30015d13a3ca0988b4674a83eccebbea747fe1f8/Sources/ComposableArchitecture/SwiftUI/ForEachStore.swift#L113-L119

**Comment by stephencelis** [comment]
Re-opening this since we plan on merging #1845.

**Comment by stephencelis** [comment]
I believe this is addressed now!
