### ISSUE TITLE
Bug for binding state issue, 0.49.2

### ISSUE THREAD

**Issue by ACFancy** [pointfreeco/swift-composable-architecture#1821]
### Description

a binding state bool value for alert view visible
- 0.48.1 show and dismiss normally
- 0.49.2 show normally dismiss no working

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

a binding state bool value for alert view visible
- 0.48.1 show and dismiss normally
- 0.49.2 show and dismiss normally

### Actual behavior

a binding state bool value for alert view visible
- 0.48.1 show and dismiss normally
- 0.49.2 show normally dismiss no working

### The Composable Architecture version information

0.49.2

### Destination operating system

iOS 14, 16

### Xcode version information

Xcode 14.0.1

### Swift Compiler version information

```shell
swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
Target: x86_64-apple-macosx13.0
```

**Comment by tgrapperon** [comment]
Hey @ACFancy! It's rather difficult to know what's happening without more code, so it would be great if you could post a small reproduction. It seems to work as expected on the few sample cases I tried, with or without using TCA's alert stuff.

Furthermore, there was a few package dependencies that were updated recently, so I'd also make sure to go to "File>Packages>" and perform `Reset package cache` and then `Resolve packages` (or ideally `Update to latest package versions` which is more proactive than `Resolve packages`).

**Comment by ACFancy** [comment]
@tgrapperon 
- [A GitHub Demo for reproduce this unexpected behavior](https://github.com/ACFancy/DemoForTCA.git)

**Comment by tgrapperon** [comment]
Hey @ACFancy! Thanks for the repro!
Well, the problem is caused by a third party implementation of an alert, so I can't really say what has changed to cause that.
After a quick check, there are a few things that are not right with the way this wrapper is defined. I would recommend you to try to reimplement it as a `ViewModifier` (so you wouldn't have to carry the presenting view around). I would also try to clean up the bindings' path, so it is only passed from a parent to a child.
After checking out a view commits, this seems related to changes from #1802, but I'm not sure if this is a true regression, or something that was working by luck thanks to the previous binding implementation being backed by functions.
/cc @iampatbrown

**Comment by ACFancy** [comment]
@tgrapperon new commit I changed to ViewModify, buy not working, why defined a binding bool state value wasn't changed synchronously when parameter deliver from one view to another more view on 0.49.2

**Comment by tgrapperon** [comment]
Indeed, this a clearer now. To be honest, I'm not sure why it was working in the first place. If you look that them closely, almost your bindings are only reading, meaning that they could be replaced by a simple `Bool`. But once you make this simplification, you furthermore see that most of your `Bool` are always `true`, meaning that you can replace the arguments by argument-less closures and evaluate them in your inits. After that, I admit I have trouble to wrap my head around the what's going on, as many things are not exactly how I'd set things up in SwiftUI. If you rewrite the presentation layer in pure SwiftUI, it works as expected. For example, with the modifier:
```swift
extension View {
  func pseudoAlert<Content: View>(isPresented: Binding<Bool>, @ViewBuilder content: () -> Content)
    -> some View
  {
    self.modifier(PseudoAlert(isPresented: isPresented, alertContent: content))
  }
}

struct PseudoAlert<AlertContent: View>: ViewModifier {
  @Binding var isPresented: Bool
  var alertContent: AlertContent
  init(isPresented: Binding<Bool>, @ViewBuilder alertContent: () -> AlertContent) {
    self._isPresented = isPresented
    self.alertContent = alertContent()
  }
  func body(content: Content) -> some View {
    content
      .overlay(
        ZStack {
          if isPresented {
            alertContent
          }
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .animation(.default, value: isPresented)
      )
  }
}
```
and then:
```swift
…
.navigationBarHidden(true)
.navigationViewStyle(.stack)
.pseudoAlert(
  isPresented: viewStore.binding(\.$isAlertVisible)) {
    MessageAlertView(
      title: "Title",
      message: "Tip tip click",
      actions: [
        .init(style: .cancel, title: "Sure") {
          viewStore.send(.onAlertSure)
          viewStore.send(.set(\.$isAlertVisible, false))
        },
        .init(style: .default, title: "Cancel") {
          viewStore.send(.onAlertCancel)
          viewStore.send(.set(\.$isAlertVisible, false))
        }
      ]
    )
  }
```
It seems to work as expected. So this makes me think that there is probably a bug in your rather complex implementation. I sincerely don't know why it was working with the previous version, but it was likely over-rendering, and 1802 improved that, but "broke" your feature that was coincidentally relying on this.

Do you have a specific reason to use this approach and delegate almost everything to a representable that embeds a `UIHostingController`?

**Comment by ACFancy** [comment]
@tgrapperon [new commit](https://github.com/ACFancy/DemoForTCA.git). I tried using swiftUI a binging bool state value, it works. So It's some wrong in TCA implementation about a binging state value

**Comment by iampatbrown** [comment]
@ACFancy It's definitely related to the change in #1802 as @tgrapperon mentioned. 

I've had a quick look at some possible solutions but will need to run things by @stephencelis and @mbrandonw. Probably won't be able to until the weekend though. 

Thanks heaps for providing so much detail as well as a repo with the issue :)

**Comment by stephencelis** [comment]
@ACFancy We ended up re-reverting this, so I believe this issue is resolved, but we hope to fix the underlying binding bug without causing regressions like the one you experienced in the future! Thanks again for reporting it!
