### ISSUE TITLE
Branch prerelease/1.0 is not compiling 

### ISSUE THREAD

**Issue by Malauch** [pointfreeco/swift-composable-architecture#1924]
### Description

I noticed that commit recent commit 4d5cb6dc36d9e0955b0b205cce8826901a925788 on prerelease/1.0 branch is not compiling (Xcode 14.2). Error messages:

<img width="1139" alt="Zrzut ekranu 2023-02-18 o 10 36 56" src="https://user-images.githubusercontent.com/13001524/219853575-0862cb5c-de4a-4503-ae92-bb3bb4506201.png">

However earlier commit 8db9e20b0ad86ce6c4875e2f3928bc7b7c412bee compiles without any problem.
Main branch is also compiling without any error. 

I tried to clean build folder and compile from fresh start and compile error is persistent.

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

TCA package should compile without errors.

### Actual behavior

TCA doesn't compile.

### Steps to reproduce

1. Link TCA in your package/project using prerelease/1.0 branch or 4d5cb6dc36d9e0955b0b205cce8826901a925788 revision.
2. Try to compile project/package.

### The Composable Architecture version information

4d5cb6dc36d9e0955b0b205cce8826901a925788

### Xcode version information

14.2

### Swift Compiler version information

```shell
5.7.2
```

**Comment by ibrahimkteish** [comment]
I have the same problem

**Comment by tgrapperon** [comment]
Indeed, this is a collateral effect of #1911. A few "free" `Send` needed to be qualified to `Effect<Action>.Send`. I've submitted #1926 that should fix the issue.

**Comment by stephencelis** [comment]
Fixed by #1926. Thanks @tgrapperon!
