### ISSUE TITLE
Branch prerelease/1.0 is not compiling

### ISSUE THREAD

**Issue by Malauch** [pointfreeco/swift-composable-architecture#1965]
### Description

Branch prerelease/1.0 is not compiling because of some unresolved merge conflict (markers). Issue is here: https://github.com/pointfreeco/swift-composable-architecture/blob/34d47cd7c4c82f5954a7a53bbdb7be904cbe7b00/Sources/ComposableArchitecture/Effects/Publisher.swift#L90-L113

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

Should be compiling.

### Actual behavior

It's not compiling.

### Steps to reproduce

1. Link branch `prerelease/1.0` into the project
2. Try to build project.

### The Composable Architecture version information

34d47cd7c4c82f5954a7a53bbdb7be904cbe7b00

### Destination operating system

iOS 16.3.1

### Xcode version information

14.2

**Comment by mbrandonw** [comment]
Hi @Malauch, thanks for the heads up. I just pushed a fix!
