### ISSUE TITLE
@ViewedStore missing from UIKIt?

### ISSUE THREAD

**Issue by matadan** [pointfreeco/swift-composable-architecture#2]
I've been using a version with @ViewedStore for UIKit compatibility but this is not part of the release. Did I miss something where it was replaced with another mechanism?

**Comment by stephencelis** [comment]
That was one of many renditions riffs on the view store. After landing on our current SwiftUI solution we decided to consolidate concepts and encourage folks to instantiate view stores directly. A few examples can be seen in the UIKit Case Studies and Tic Tac Toe apps. For example:

https://github.com/pointfreeco/swift-composable-architecture/blob/d2240d0e76c1a758dbadbf737ceefc888b2e807c/Examples/CaseStudies/UIKitCaseStudies/CounterViewController.swift#L33

**Comment by stephencelis** [comment]
Cool to close this one out @matadan? Or do you have any other questions?

**Comment by matadan** [comment]
Got it.
