### ISSUE TITLE
Crash when binding path to NavigationStack

### ISSUE THREAD

**Issue by xiaogdgenuine** [pointfreeco/swift-composable-architecture#2058]
### Description

This crash isn't TCA's fall at all, I just think that it would be helpful to mention here in case it help someone.

Today I found a strange crash in `NavigationStackView`, reproduce steps:
1. Paste my sample code below into Xcode and run.
2. Navigate at least 2 level deep in the `NavigationStackView`.
3. Scroll the page content, and while the **scrolling animation is still running**, tap on back button
4. Tap on back button again to back to root view, the app crashed with message `Fatal error: Can't remove more items from a collection than it contains`

Sample code:
```swift
struct ContentView: View {
    @State var path: [Int] = []

    var body: some View {
        // Crash version: creat new binding instance everytime when body get called
        let pathBinding = Binding(get: { path }, set: { path = $0 })

        // Working fine version: just simply pass the wrapper value of @State
//        NavigationStack(path: $path) {
        NavigationStack(path: pathBinding) {
            PageView()
                .navigationDestination(for: Int.self) { _ in PageView() }
        }
    }
}

struct PageView: View {

    @Environment(\.dismiss) var dismiss

    var body: some View {
        ScrollView {
            VStack {
                // Create 100 items for scrolling
                ForEach(0..<100) { item in
                    NavigationLink(value: 1, label: {
                        Color.green
                            .padding(.vertical)
                            .overlay(Text("\(item)").font(.title).foregroundColor(.red))
                            .frame(maxWidth: .infinity)
                            .frame(height: 200)
                    })
                }
            }
        }
    }
}
```

If you don't scroll pages at all, it won't crash.

Also if you comment-out the `Working fine version`, the app won't crash even with scrolling animations!

From my point of view these two version of binding should both just work, but apparently not in this case, yet I still don't know what's happening under the hood....

# Demo videos:
Crash version:

https://user-images.githubusercontent.com/51731239/234332606-f05f1baa-ad33-4965-b779-ad99329857bc.mp4

Working fine version:

https://user-images.githubusercontent.com/51731239/234334531-1371e246-282e-43a1-98c5-c2de487614a6.mp4

# It's a SwiftUI bug, why bring it to TCA?
I don't know how other dev do their programatic navigation with TCA, but I do it in the most intuitive way:
1. Add a `path` property in State to drive the navigation.
2. Add a`updatePath` action to allow `NavigationStackView` update that property
3. Create new binding by `viewStore.binding(get: \.path, send: Reducer.Action.updatePath)`
4. Pass that binding to `NavigationStackView`

And you see the problem here, since in step 3 we are creating new binding everytime the view's body get called, we quickly run into this bug with TCA.

# Workaround
- Don't create custom new binding everytime, just use `$path`.
- Or disable back button when the scroll view is scrolling.

# Possible related issue
#1798 

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

The app don't crash

### Actual behavior

The app crashed

### Steps to reproduce

Copy the sample code and follow my demo video.

### Destination operating system

iOS 16.4

### Xcode version information

14.3

### Swift Compiler version information

```shell
swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
```

**Comment by mbrandonw** [comment]
Hi @xiaogdgenuine, this demo does not seem to be using TCA at all, so I am going to close this issue. If the problem really is related to creating the binding multiple times, then it does seem that even with TCA you can create the binding once and hold onto it.

Feel free to open a [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions) if you want to share more of your findings or discuss possible solutions.
