### ISSUE TITLE
TCA 0.54.0. Linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by larryonoff** [pointfreeco/swift-composable-architecture#2189]
### Description

Application doesn't compile for release configuration.

Please see the error on attachment.
<img width="929" alt="Screenshot 2023-06-09 at 17 27 31" src="https://github.com/pointfreeco/swift-composable-architecture/assets/372616/8dea0040-5e75-4d67-9ee2-f9d62fa03baf">

BTW. Release 0.54.0 has issue only with `navigationIDPath`, when `navigation-beta` branch had issue with `dismiss` and `navigationIDPath`.

The same issue happens for @ski-u

PS. I decided to create issue, since issue happens for 3 of my projects. And I still don't know how to resolve it

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

Application compiles in release configuration.

### Actual behavior

Application doesn't compile in release configuration.

### The Composable Architecture version information

0.42.0

### Xcode version information

14.3.1

### Swift Compiler version information

```shell
swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
```

**Comment by mbrandonw** [comment]
Hi @larryonoff, are you able to reproduce this in a simple project so that we can see what is going on?

And can you expand a bit more on what you mean here:

> BTW. Release 0.54.0 has issue only with navigationIDPath, when navigation-beta branch had issue with dismiss and navigationIDPath.

**Comment by larryonoff** [comment]
> Hi @larryonoff, are you able to reproduce this in a simple project so that we can see what is going on?
> 
> And can you expand a bit more on what you mean here:
> 
> > BTW. Release 0.54.0 has issue only with navigationIDPath, when navigation-beta branch had issue with dismiss and navigationIDPath.

I'll try to make simple project in a few days. If not, I'll give you access to one of my private projects.

> BTW. Release 0.54.0 has issue only with navigationIDPath, when navigation-beta branch had issue with dismiss and navigationIDPath.

I mean that previously (before release) there were two undefined symbols errors.

1. ```Undefined symbol: _$s 12Dependencies16DependencyValuesV22ComposableArchitectureE 16navigationIDPathAD010NavigationGOVACTKg``` the same as in release
2. ```Undefined symbol:  _$s12Dependencies16DependencyValuesV22ComposableArchitectureE7dismissAD13DismissEffectVpACTkq```. This's not present in release.

**Comment by dvosscricut** [comment]
Having same issue with private project when archiving (which I can't share) on TCA 0.54.0. But perhaps I'll try to replicate with a sample project as well.

**Comment by dvosscricut** [comment]
@larryonoff @mbrandonw 

I found an open source project that uses TCA and replicated the error! 

https://github.com/prose-im/prose-app-macos

Just update signing info and then run the "Release" target

get this similar error about nativationIDPath:

error: <unknown>:0: unsupported relocation with subtraction expression, symbol '_$s12Dependencies16DependencyValuesV22ComposableArchitectureE16navigationIDPathAD010NavigationG0VvpACTKq' can not be undefined in a subtraction expression

<img width="1796" alt="Screenshot 2023-06-09 at 7 31 24 PM" src="https://github.com/pointfreeco/swift-composable-architecture/assets/48807612/3c2b0627-fd5f-4ce1-b449-5f534c89791f">

**Comment by salmin-skelia** [comment]
@mbrandonw Any updated on this one?

**Comment by mbrandonw** [comment]
Hi everyone, thanks for the sample project! We were able to reproduce the problem. It appears to be a Swift bug related to inlining. Removing the inlineable from `NavigationID` makes it work again:

https://github.com/pointfreeco/swift-composable-architecture/blob/4f823d9341ab3ac99bfc0ac74c67fa12c31c8601/Sources/ComposableArchitecture/Internal/NavigationID.swift#L3C1-L9

We will get a fix out soon.

**Comment by larryonoff** [comment]
@mbrandonw thanks! looking forward to bugfix.

**Comment by larryonoff** [comment]
Version 0.54.1 works now! Thank you!
