### ISSUE TITLE
Custom TCA Dependency not compiling if the file has a macro style preview

### ISSUE THREAD

**Issue by patagoniacode** [pointfreeco/swift-composable-architecture#2228]
### Problem
Custom TCA Dependencies are not compiling if the file contains a new style macro preview.
This doesn't happen when using library dependencies (uuid, for example).

### Temporal solution
The file compiles again if the "#Preview" is removed or the old style preview is used.

### Branches having the issue
The issue can be reproduced using the latest main branch (0.54.1) and the prerelease/1.0 branch.

### Sample code
For simplicity, the example uses a SwiftUI view. However, the problem also happens using a TCA Feature.

```
import SwiftUI
import ComposableArchitecture

// MARK: - SimpleStringClient Dependency
struct SimpleStringClient: DependencyKey {
    var stringGenerator: @Sendable () -> String
    static var liveValue: Self { return SimpleStringClient(stringGenerator: { return "Hello, world (from dependency)!"}) }
}

extension DependencyValues {
    var stringClient: SimpleStringClient {
        get { self[SimpleStringClient.self] }
        set { self[SimpleStringClient.self] = newValue }
    }
}

// MARK: - SwiftUI View
struct ContentView: View {
    @Dependency(\.stringClient) var stringClient // The stringClient dependency is not found if the file has the new macro preview style. Error message: Value of type 'DependencyValues' has no member 'stringClient'.
    var body: some View {
        Text("\(stringClient.stringGenerator())")
    }
}

// MARK: - Preview with new macro: It makes the code not compile with the following error:
// "Value of type 'DependencyValues' has no member 'stringClient'".
// If the preview is commented or changed to the old style preview, the file compiles again.
#Preview {
    ContentView()
}

// MARK: - Preview with old style preview: The code compiles
struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}

```

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

Use a custom Dependency (in the example above, the "StringClientDependency").

### Actual behavior

Custom TCA Dependencies are not compiling if the file contains a new style macro preview.
Error message: "Value of type 'DependencyValues' has no member 'stringClient'."
The issue doesn't happen when using library dependencies (uuid, for example).

### Steps to reproduce

1.- Create a custom TCA dependency
2.- Use it in a TCA feature or a SwiftUI view
3.- Create a preview using the new style macro preview

### The Composable Architecture version information

0.54.1 and also prerelease/1.0

### Destination operating system

iOS 15.0 (1008)

### Xcode version information

Version 15.0 beta 2 (15A5161b)

### Swift Compiler version information

```shell
Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-darwin22.5.0
```

**Comment by mbrandonw** [comment]
Hi @patagoniacode, I believe this is a known issue in Xcode and don't think there is anything we can do about it in the library:

https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes

> #Preview can’t reference symbols in Swift type extensions when they are defined in the same module as the Preview (110671628)
**Workaround:** Revert to using PreviewProvider, or copy the implementation of the extension directly in to the #Preview itself or make it a global symbol

Hopefully it is fixed in the next Xcode beta.

**Comment by patagoniacode** [comment]
Hi @mbrandonw, thank you for you answer.
Best regards from Patagonia.
