### ISSUE TITLE
Issue using with Stepper

### ISSUE THREAD

**Issue by karthikgs7** [pointfreeco/swift-composable-architecture#224]
**Describe the bug**
After couple of actions, one of the buttons got disabled, and tapping on the other button sends the invalid action to the store.

**To Reproduce**
Try copy-pasting the code in SwiftUI file, run and do couple of actions with the stepper. 

```swift
import SwiftUI
import ComposableArchitecture

struct CounterState: Equatable {
    var title: String = ""
    var count: Int = 0
}

enum CounterAction: Equatable {
    case incrementCountTapped
    case decrementCountTapped
}

struct CounterEnvironment {}

let counterReducer = Reducer<CounterState, CounterAction, CounterEnvironment> { state, action, environment in
    switch action {
    case .incrementCountTapped:
        state.count += 1
        return .none
    case .decrementCountTapped:
        state.count -= 1
        return .none
    }
}

struct CounterView: View {
    
    let store: Store<CounterState, CounterAction>
    
    var body: some View {
        WithViewStore(self.store) { viewStore in
            HStack {
                Text("Count")
                Stepper(onIncrement: {
                    viewStore.send(.incrementCountTapped)
                }, onDecrement: {
                    viewStore.send(.decrementCountTapped)
                }, label: {
                    Text("\(viewStore.count)")
                })
            }
        }
    }
}

struct ContentView: View {
    var body: some View {
        CounterView(
            store: Store(
                initialState: CounterState(),
                reducer: counterReducer,
                environment: CounterEnvironment()
            )
        )
    }
}

```

**Expected behavior**
Tapping on the button should be changing the value without disabling the UI elements.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/4941940/87171463-58719600-c2f0-11ea-9200-5b12e75eaa6f.png)

**Environment**
 - Xcode 11.5
 - Swift 5

**Comment by mbrandonw** [comment]
Hey @karthikgs7, thanks for the report! 

We've actually stumbled upon this before, and we've gotten some confirmation from Apple that this is most likely a SwiftUI bug. We documented this on the `WithViewStore` type:

https://github.com/pointfreeco/swift-composable-architecture/blob/c9c1a9a50040408c436e496bac35007add327186/Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift#L15-L18

To work around can you use the version of `Stepper` that takes a binding instead? You will need to manually check the before and after value in the reducer to determine if the value was incremented or decremented.

**Comment by mbrandonw** [comment]
Gonna close this issue for now, but please feel free to reopen if you have more questions!
