### ISSUE TITLE
Compile error about ambiguous ViewStore when reducer uses BindingState/BindableAction

### ISSUE THREAD

**Issue by johankool** [pointfreeco/swift-composable-architecture#2275]
### Description

When a reducer contains BindingState/BindableAction but a SwiftUI view doesn't use this, the compiler complains about ambiguous init. (The use case for this may be that this SwiftUI view doesn't need the binding, but a child view does.)

I've written a test that shows this here:
https://github.com/johankool/swift-composable-architecture/tree/ambiguous_viewstore

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

It compiles just fine.

### Actual behavior

Ambiguous use of 'init(_:observe:content:file:line:)'

### Steps to reproduce

```swift
 struct BindableReducer: Reducer {
      struct State: Equatable {
        @BindingState var something: Int
      }
      
      enum Action: BindableAction {
        case binding(BindingAction<State>)
      }
      
      var body: some Reducer<State, Action> {
        BindingReducer()
      }
    }
    
    struct SomeView: View {
      let store: StoreOf<BindableReducer>
      
      struct ViewState: Equatable {
        
      }
      
      var body: some View {
        WithViewStore(store, observe: { _ in ViewState() }) { viewstore in // Ambiguous use of 'init(_:observe:content:file:line:)'
          EmptyView()
        }
      }
    }
```

### The Composable Architecture version information

a4d371e8adc9d081d616f988fb0f089b479e9553 (current prerelease/1.0 branch)

### Destination operating system

iOS 16.4

### Xcode version information

Version 14.3.1 (14E300c)

### Swift Compiler version information

```shell
> xcrun swiftc --version
swift-driver version: 1.82.2 Apple Swift version 5.9 (swiftlang-5.9.0.114.10 clang-1500.0.29.1)
Target: arm64-apple-macosx13.0
```

**Comment by stephencelis** [comment]
Thanks! I've cherry picked your test in and PR'd a fix: #2278.
