### ISSUE TITLE
Crash when using .debug 

### ISSUE THREAD

**Issue by ndistqt** [pointfreeco/swift-composable-architecture#230]
I'm sure it's an obvious mistake on my part and I had no problems before, but I wasn't able to identify the offending code that causes .debug() to result in following error: 
<img width="500" alt="crash@2x" src="https://user-images.githubusercontent.com/17615164/88118420-d4f05880-cbbd-11ea-9093-d73e781de744.png">

As soon as I remove .debug() everything works like charm.

**Comment by mbrandonw** [comment]
Hi @ndistqt, thanks for the report! This is a bummer, but we seen some weird behavior in Swift's mirror before, especially when dealing with types from some of Apple's frameworks.

I see the value here is an `AXUIElement`. Is that being held in your state or your action?

**Comment by mbrandonw** [comment]
I may need to see more of your state/actions that is causing this because locally it seems that `debugOutput` seems to run fine with an `AXUIElement`, just try out this test:

```swift
  func testAXUIElement() {
    let element = AXUIElementCreateApplication(1)

    XCTAssertEqual(
      debugOutput(element),
      """
      """
    )
  }
```

**Comment by ndistqt** [comment]
Both:
<img width="698" alt="slstate@2x" src="https://user-images.githubusercontent.com/17615164/88129348-2ad1fa00-cbd8-11ea-903b-bc353ced572c.png">

Item has a strong reference to a UIElement, which has a strong reference to AXUIElement
<img width="599" alt="itemclass@2x" src="https://user-images.githubusercontent.com/17615164/88129401-505f0380-cbd8-11ea-853a-79e908121558.png">

**Comment by ndistqt** [comment]
<img width="645" alt="item class@2x" src="https://user-images.githubusercontent.com/17615164/88252376-37288680-ccae-11ea-89e5-e5b7218195a8.png">
<img width="806" alt="CleanShot 2020-07-23 at 06 32 37@2x" src="https://user-images.githubusercontent.com/17615164/88252409-56271880-ccae-11ea-97ee-d0901f3a2be2.png">
The debugOut function is found although I have the ComposableArchitecture imported.

**Comment by mbrandonw** [comment]
Are you able to reproduce this problem in some code that I can run locally?

Also what is `UIElement`? It doesn't look like it's an Apple type.

**Comment by ndistqt** [comment]
"Are you able to reproduce this problem in some code that I can run locally?"
- I'll try and let you know.

UIElement is from the library AXSwift, which you can find here on github, it's just a wrapper around Apple's accessibility API for better ergonomics.

**Comment by stephencelis** [comment]
Hey @ndistqt we took a quick look at AXSwift and it looks like the `UIElement` custom string convertible conformance does some pretty side-effecty things, like accessing a process ID and calling out to `NSRunningApplication`:

https://github.com/tmandry/AXSwift/blob/b4db10b2c28583f5c51033166be60a572ff39dcb/Sources/UIElement.swift#L609

In general we think that state needs to consist of simple value types, and as soon as you introduce classes and objects you expose yourself to a lot of undefined behavior that will be difficult to test. If you need parts of these classes in your state we recommend defining structs that hold just the value-based data you care about. It can sometimes be a bit of a pain to add this boilerplate, but it will give you peace of mind that your system is working in a predictable manner.
