### ISSUE TITLE
View not updating when `WithViewStore` contains a `GeometryReader`

### ISSUE THREAD

**Issue by gkaimakas** [pointfreeco/swift-composable-architecture#235]
**Describe the bug**
I am experiencing some weird behaviour when I wrap a `GeometryReader` inside a `WithViewStore` view. Instead of the view being redrawn each time the state changes, the view is only updated once and never again.  

The issue first came up when I moved some `@State` variables to my `AppState`.
 
**To Reproduce**
The issue can be reproduced using this project

[CA-ViewStore-GeometryReader-Bug-master.zip](https://github.com/pointfreeco/swift-composable-architecture/files/4970929/CA-ViewStore-GeometryReader-Bug-master.zip)

**Expected behavior**
The view should update everytime the state changes.

**Environment**
 - Xcode [11.6 (11E708)]
 - Swift [5.2.4]
 - OS [iOS 13.6]

**Comment by boudavid** [comment]
Hello @gkaimakas,

This is a known bug and the workaround is to move the `GeometryReader` outside the `WithViewStore`. More information [here](https://github.com/pointfreeco/swift-composable-architecture/blob/339feec7db39f22466efcde5e71f60b609082064/Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift#L10). 😃

**Comment by gkaimakas** [comment]
Thank you @boudavid !
