### ISSUE TITLE
Localizable Alert and ActionSheet buttons

### ISSUE THREAD

**Issue by abrampers** [pointfreeco/swift-composable-architecture#237]
I am currently using `AlertState` and `ActionSheetState` TCA provided to display my Alert and ActionSheets. Unfortunately, both `AlertState<Action>.Button` and `ActionSheetState<Action>.Button` does not support localization since the function only accepts `String` as its argument and not `LocalizedStringKey`. Will there be any updates to support localization on both of these buttons?

**Comment by mbrandonw** [comment]
Hey @abrampers, thanks for the report!

You are right, ideally we would have the fields in `AlertState` and `ActionSheetState` be `LocalizedStringKey`, but unfortunately `LocalizedStringKey` has a really funky equatable conformance. It _is_ `Equatable`, but not in anyway that is predictable. I filed a [feedback](https://gist.github.com/mbrandonw/fd78446ec6e43fb316684f8a71c2bd34) about this, but the crux is that neither of this evaluate to true:

```swift
LocalizedStringKey("\(1)") == LocalizedStringKey("\(1)") // false

LocalizedStringKey("1") == LocalizedStringKey("\(1)") // false
```

This means that once you add these values to your state you can no longer write tests for them 😕. We would love to figure this out, but we haven't spent too much time thinking about it yet. If you (or anyone else) has ideas we'd love to hear it.

**Comment by mycroftcanner** [comment]
Why not use L10n strings generated by [SwiftGen](https://github.com/SwiftGen/SwiftGen#strings) for localization?

**Comment by barksten** [comment]
I have a similar struct in a codebase. I've implemented a custom Equatable for the whole alert like this:
```
struct AlertMessage: Identifiable, Equatable {
        var id: String { get { String(describing: message) } }
        let title: LocalizedStringKey?
        let message: LocalizedStringKey
        let buttonText: LocalizedStringKey?
        
        init(title: LocalizedStringKey? = nil,
             message: LocalizedStringKey,
             buttonText: LocalizedStringKey? = nil) {
            self.title = title
            self.message = message
            self.buttonText = buttonText
        }

        static func == (lhs: AlertMessage, rhs: AlertMessage) -> Bool {
            guard String(describing: lhs.title) == String(describing: rhs.title) else {
                return false
            }
            guard String(describing: lhs.message) == String(describing: rhs.message) else {
                return false
            }
            guard String(describing: lhs.buttonText) == String(describing: rhs.buttonText) else {
                return false
            }
            return true
        }
}
```
It's _kind of_ a hack to rely on String(describing:) for LocalizedStringKey

**Comment by mbrandonw** [comment]
@barksten That's very interesting, thanks for sharing!

Unfortunately that doesn't work when there are string interpolations:

```swift
String(describing: LocalizedStringKey("1")) == String(describing: LocalizedStringKey("\(1)")) // false
```

This would force test assertions to remember to interpolate values:

```swift
XCTAssertEqual(state.message, "Hello \("Blob")")
```

Which isn't the worse, but a bit of a gotcha.
