### ISSUE TITLE
WithViewStore or @ObservedObject var viewStore:.  doesn't update view [iOS 13.1]

### ISSUE THREAD

**Issue by romiroma** [pointfreeco/swift-composable-architecture#238]
**Describe the bug**
State updates, but view doesn't

**To Reproduce**
[Test.zip](https://github.com/pointfreeco/swift-composable-architecture/files/4993290/Test.zip)

**Expected behavior**
I expect view to be updated on state update inside WithViewStore

**Environment**
 - Xcode 11.6 (11E708)
 - Swift 5.2.4
 - iOS 13.1

** UPD:
- Doesn't work with TCA 0.6.0, but works fine with 0.5.0 version (If I set `Exact` version)

**Comment by mbrandonw** [comment]
Hey @romiroma, thanks for the report! I was able to reproduce this locally, and it's definitely a problem with iOS 13.1, and 13.2, and then due to some Combine/SwiftUI fixes in 13.3 it works correctly.

The bug you are seeing is due to this PR https://github.com/pointfreeco/swift-composable-architecture/pull/199 where we changed some internals of `ViewStore` in order to close up an escape hatch that was created in some of the new iOS 14 APIs. However, Apple has since fixed that escape hatch, and so maybe we should revert this now, especially since it breaks older iOS.

Stephen and I will discuss today and come up with a plan. Thanks again!

---

As an aside, I came across some other weird behavior in just iOS 13.1. Our `TestScheduler` crashes because it seems the mere act of comparing two scheduler times results in a crash in Combine 😬:

```swift
DispatchQueue.SchedulerTimeType(.init(uptimeNanoseconds: 1)) <= DispatchQueue.SchedulerTimeType(.init(uptimeNanoseconds: 2)) // 🛑 crash
```

So even once we fix the issue you reported you may wanna upgrade to iOS 13.2 so that you can use the test scheduler.

**Comment by romiroma** [comment]
Thank you, guys, for fast response! 💪👍

**Comment by manmal** [comment]
@stephencelis For me, the problem persists with the current release (0.8.0) on iOS 13.2.2. This can be verified by using the test project created by @romiroma ([Test.zip](https://github.com/pointfreeco/swift-composable-architecture/files/4993290/Test.zip)), updating the TCA package to the current release, and running it on an iOS 13.2.2 simulator. 
<img src="https://user-images.githubusercontent.com/142797/93663835-daa5d580-fa6a-11ea-963d-60490f70bd81.gif" width="300">

**Comment by malonehedges** [comment]
@manmal @mbrandonw @stephencelis I'm also running into this with iOS 13.2. 13.1 and 13.3 work for me but I can replicate this bug in the simulator and on device.

**Comment by apouche** [comment]
I confirm this is still happening on iOS 14. and release 0.8.0. 
As a workaround I did this
```
extension Publisher {
  // there seems to be an iOS 14 specific issue where sometimes
  // updating UI right after receiving events would fail.
  // adding an insignificant delay (postponing to next run loop) seems to fix it
  func jf_runLoopdelay(scheduler: RunLoop = RunLoop.main) -> AnyPublisher<Self.Output, Self.Failure> {
    if #available(iOS 13.2, *) {
      return delay(for: .milliseconds(1), scheduler: scheduler).eraseToAnyPublisher()
    } else {
      return eraseToAnyPublisher()
    }
  }
}
```

**Comment by stephencelis** [comment]
> I confirm this is still happening on iOS 14. and release 0.8.0.

@apouche Do you mean it's still happening on iOS 13.2? Your code seems to suggest that you target that specific OS for the workaround.

**Comment by apouche** [comment]
I put 13.2 because other users mentionned this still occuring to them and this would solve their problem as well. However to me this is really an iOS 14 specific issue.

**Comment by stephencelis** [comment]
@apouche And the code you shared fixes it? I'm not sure I understand, since wouldn't it be the same as calling `eraseToAnyPublisher()` on iOS 14?

If possible could you provide an example project that exhibits the behavior along with instructions to reproduce?

**Comment by nsillik** [comment]
I'm seeing this behavior in the 13.1 simulator when running the `Case Studies (SwiftUI)` after changing the deployment target:
`IPHONEOS_DEPLOYMENT_TARGET = 13.1`.

None of the case studies work though the reducers are firing. This is off of the `main` branch at `c1f88bd8608e8a26fd61ab46c9f11a63b0f4023d` with only the following diff:
```diff
diff --git a/Examples/CaseStudies/CaseStudies.xcodeproj/project.pbxproj b/Examples/CaseStudies/CaseStudies.xcodeproj/project.pbxproj
index d15751f..c3ef826 100644
--- a/Examples/CaseStudies/CaseStudies.xcodeproj/project.pbxproj
+++ b/Examples/CaseStudies/CaseStudies.xcodeproj/project.pbxproj
@@ -1099,6 +1099,7 @@
 				CODE_SIGN_STYLE = Automatic;
 				ENABLE_PREVIEWS = YES;
 				INFOPLIST_FILE = SwiftUICaseStudies/Info.plist;
+				IPHONEOS_DEPLOYMENT_TARGET = 13.1;
 				LD_RUNPATH_SEARCH_PATHS = (
 					"$(inherited)",
 					"@executable_path/Frameworks",
@@ -1117,6 +1118,7 @@
 				CODE_SIGN_STYLE = Automatic;
 				ENABLE_PREVIEWS = YES;
 				INFOPLIST_FILE = SwiftUICaseStudies/Info.plist;
+				IPHONEOS_DEPLOYMENT_TARGET = 13.1;
 				LD_RUNPATH_SEARCH_PATHS = (
 					"$(inherited)",
 					"@executable_path/Frameworks",
```

This issue should probably be re-opened

**Comment by nsillik** [comment]
Also happens on Simulator 13.2 in the `Case Studies (SwiftUI)`.

cc: @mbrandonw @stephencelis

**Comment by nsillik** [comment]
@mbrandonw @stephencelis  I'm happy to get this reproducible in a tiny app or cut a branch with a failing test-case. Also happy to open a new bug. Let me know what'd be the most useful to y'all

**Comment by manmal** [comment]
FWIW, the problem didn't occur for me on iOS 13.3 and higher. On 13.2.2, it's easily reproducible with my sample project above.

**Comment by eqwalker** [comment]
Hi has there been a fix for this issue? I'm seeing it running iPhone 12 Pro - 14.2 Sim

**Comment by eqwalker** [comment]
I figured out my problem. Be sure your state structs implement the Equatable protocol correctly. I had hard coded a return value of true and I suspect when you change state there is a comparison done to determine if a view update is warranted.

**Comment by manmal** [comment]
@eqwalker The Equatable conformance for the test project posted at the beginning of this thread is certainly not to blame:
```swift
struct State: Equatable {
    var count: Int = 0
}
```
So I suspect that your finding only fixes the problem for the 14.2 sim.
Would you mind checking whether the problem occurs on iOS <13.3 (e.g. 13.2.2) for you?

**Comment by eqwalker** [comment]
@manmal looks like you're right. It started happening for me again iOS 14.2 iPhone 12 Pro Sim. :-(. Doesn't seem to be related to Equatable....

**Comment by nsillik** [comment]
@mbrandonw @stephencelis can we re-open this, or would you like a new issue?

**Comment by nsillik** [comment]
I've opened a new issue: #334
cc: @eqwalker @manmal

**Comment by manmal** [comment]
Thanks so much @nsillik, this fixes the issue for us 🎉
