### ISSUE TITLE
Weird behavior and a crash in Case Studies -> Navigation -> Stack

### ISSUE THREAD

**Issue by filblue** [pointfreeco/swift-composable-architecture#2396]
### Description

I was attempting to study this Case Study today, and bumped into several issues:

1. When initially opening the screen, it jumps back, spitting "Update NavigationAuthority bound path tried to update multiple times per frame." message in console. Subsequent screen openings do not jump back, however the same message in the console is generated each time.
2. When following sequence of actions is performed: "Go to screen A" -> "Back" -> Back, the app crashes with this message in the console: "Swift/RangeReplaceableCollection.swift:902: Fatal error: Can't remove more items from a collection than it contains"

Reproduces in the `main` branch, in a simulator (iPhone 14 Pro, iOS 16.4) and on real device (iPhone SE, iOS 16.6).

Demo video:

https://github.com/pointfreeco/swift-composable-architecture/assets/2987944/db68f9cb-2c30-47ec-a592-44261b788227

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### The Composable Architecture version information

c8c7817014ddec7fd5392c76662f00826d39b91e

### Destination operating system

16.4

### Xcode version information

14.3.1

### Swift Compiler version information

```shell
swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
```

**Comment by stephencelis** [comment]
Good catch, thanks! Have a fix here: https://github.com/pointfreeco/swift-composable-architecture/pull/2397

**Comment by imfractured** [comment]
Wow, we're just experiencing the exact same thing looking to migrate to NavigationStack with the new TCA wrappers but we're unable to even get the navigation working correctly in the example app as above as well. Any help would be much appreciated
