### ISSUE TITLE
Binding textfield issue? 

### ISSUE THREAD

**Issue by donmcallister** [pointfreeco/swift-composable-architecture#24]
It seems binding doesn’t work with some of the other SwiftUI TextField overloads that use Value and formatting parameters.

**Comment by stephencelis** [comment]
Hey @donmcallister! Thanks for the report.

Can you flesh this issue about a bit more? In particular, can you provide some code that shows the issue, and can you explain what you expect to happen vs. what actually happens?

It can also help to try the same thing in a vanilla SwiftUI app to see if this is an issue with the library or just how SwiftUI behaves.

**Comment by donmcallister** [comment]
```
/*
 This doesn't work for me, no formatting, not binding and storing the value. I switch to another screen and when come back to this screen, the value entered doesn't store: 
                         
                         TextField(<#T##title: StringProtocol##StringProtocol#>, value: <#T##Binding<T>#>, formatter: <#T##Formatter#>) 
*/
                        
                        TextField(
                            "Enter Price",
                            value: viewStore.binding(get: \.purchasePrice, send: SharedStateAction.FundingAction.purchasePriceChange),
                            formatter: formatter
                        )
                            .keyboardType(.numberPad)
                        
// This does work, but don't have a way to use the formatter. And I'm probably overlooking something, but so far can't figure out how to get a currency format as the user enters in numbers into text field:
                        TextField(
                            "Enter Price",
                            text: viewStore.binding(get: \.purchasePrice, send: SharedStateAction.FundingAction.purchasePriceChange))
                            .keyboardType(.numberPad)`
```

my reducer:

```
let sharedStateFundingReducer = Reducer<SharedState.CalculatorState, SharedStateAction.FundingAction, Void> { state, action, _ in
    switch action {
        
    case let .purchasePriceChange(price):
        state.purchasePrice = price
        return .none
    case let .arvPriceChange(arvPrice):
        state.afterRepairValue = arvPrice
        return .none
    }
}
```

**Comment by stephencelis** [comment]
@donmcallister Can you paste in a full example or link to a project we can clone? That way we'll have something to play with or PR back to you. Formatter-based bindings only call when editing finishes (unlike every key stroke, like the non-formatted-based text field), so it works a bit differently. We could maybe add a case study for this soon.

**Comment by donmcallister** [comment]
Much appreciated! Here is the link to what I have so far. PropertyFundingView has the two textfields where the one doesn't store or format but the other does store the input but can't figure out how to format to a currency in real time: https://github.com/donmcallister/ClockworkCalculator

**Comment by stephencelis** [comment]
Thanks @donmcallister! I've pushed an example of using this API here: https://github.com/pointfreeco/swift-composable-architecture/pull/32

> Much appreciated! Here is the link to what I have so far. PropertyFundingView has the two textfields where the one doesn't store or format but the other does store the input but can't figure out how to format to a currency in real time: https://github.com/donmcallister/ClockworkCalculator

Am I correct in understanding that you expect state to update with each keystroke? `TextField`s that take formatters do not update their bindings in real time by design. They _only_ call `set` when editing ends (like when you hit enter or when the field loses focus). If you are looking for more nuanced behavior, I think you'll need to use the `TextField` that does _not_ take a formatter, hold this state as a `String`, and manually implement formatting behavior and any conversion to a `Double` on state in your reducer.

**Comment by donmcallister** [comment]
I was hoping to have it updated into a currency format with each keystroke but this makes sense now. I did try to convert it to currency format inside the reducer but was also running into some quirky issues, but I’ll try to work through that. Thanks again! Loving TCA!
