### ISSUE TITLE
ComposableCoreBluetooth

### ISSUE THREAD

**Issue by ph1ps** [pointfreeco/swift-composable-architecture#248]
I'm currently working on an app for which I use the CoreBluetooth framework. I wrote a wrapper around the framework for TCA and figured why not open-source it to this library. The CoreBluetooth framework might not be the most used framework but I think it has some pitfalls which might be worth sharing here.

### Considerations

- There are three "managers" in CoreBluetooth (`CBCentralManager`, `CBPeripheralManager`, `CBPeripheral`) and all of them use the delegate pattern. Both `CBCentralManager` and `CBPeripheralManager` can we wrapped in the same manner as the `CLLocationManager`.
- CoreBluetooth heavily relies on `[String: Any]` for passing options to specific methods like scanning for devices, connecting and initializations. Since `Any` does not conform to `Equatable` I had to wrap those dictionary into concrete types that do conform to the `Equatable` protocol.
- Like in `ComposableCoreLocation` I created a struct for every value type (like `CBService`, `CBCharacteristic` and `CBDescriptor`) to increase testability.

I've uploaded all of the files to a gist for now: https://gist.github.com/ph1ps/d2a276168b4fa3c1bcb5b91cfbe8a4c8

### Discussion

 - I've noticed that my implementation of `Peripheral`s could cause confusion. One the one hand it has properties of a dependency (all of the `Effect`s). On the other hand it has properties of a state (eg. binding a SwiftUI `List` to the array of `Service`). Is it a dependency or a state? I couldn't come up with a better implementation for now. Maybe someone else has an opinion on that.
 - A further downside of the CoreBluetooth implementation is that a `CBPeripheral` has no visible initializers. Therefore we can only wrap peripherals when they are given to us by the delegate methods. This forced me to create a `peripheral(Peripheral, Peripheral.Action)` case in the `BluetoothManager`'s action enum since the only way to get a subscriber for a live `Peripheral` is from the upstream `BluetoothManager`. 
 - I noticed that the `.debug` higher order reducer is quite verbose when being used on the reducer that implements the `didDiscover(Peripheral, AdvertismentData, NSNumber)` case as it is constantly being called when a new device was discovered. In addition it also prints the whole `Peripheral` struct which has so many properties that someone might lose track of other actions being printed. Maybe there is a way to suppress that a specific action is being printed or maybe redact long action bodies.

I'd like to state that the code in the gist is still a WIP and I haven't tested it thoroughly. Furthermore there are still some missing pieces I did not wrap yet. I just wanted to check if there is interest for me to continue this project in an open-source way. If there is no demand for this project being included in TCA I wouldn't mind either. I still need it for my personal project so I'm not going to stop working on it 🙂.

I'm looking forward to hearing your opinion.

**Comment by stephencelis** [comment]
@ph1ps This is so awesome! Thanks for sharing with us! Give us a lil time to play with it and digest, but we'd definitely like to get a PR going and make movement on merging this.

> * I noticed that the `.debug` higher order reducer is quite verbose when being used on the reducer that implements the `didDiscover(Peripheral, AdvertismentData, NSNumber)` case as it is constantly being called when a new device was discovered. In addition it also prints the whole `Peripheral` struct which has so many properties that someone might lose track of other actions being printed. Maybe there is a way to suppress that a specific action is being printed or maybe redact long action bodies.

It _is_ possible to filter certain actions from being debugged: https://github.com/pointfreeco/swift-composable-architecture/blob/7f482acbf4c108655ae269a6445831ce1890762e/Sources/ComposableArchitecture/Debugging/ReducerDebugging.swift#L87

**Comment by ph1ps** [comment]
@stephencelis Alright, thanks 👍

**Comment by FredrikAugust** [comment]
Great work! Haven't had the time to try it out yet, but I will be working _a lot_ with CB in the coming months, so looking forward to trying this out.

**Comment by FredrikAugust** [comment]
Is there a roadmap for the inclusion of this in the repository @ph1ps?

**Comment by ph1ps** [comment]
Hi @FredrikAugust, I'm currently struggling with some CoreBluetooth quirks. As soon as I have those sorted out I will create a pull request.

**Comment by andreyz** [comment]
@ph1ps need a hand? You can just fork it on your account and I can collaborate on shaping it, as I need TCA-friendly bluetooth library for my own project.

**Comment by ph1ps** [comment]
@andreyz I forked the repository and pushed everything I've done yet. I don't know how we will add my changes to this repository yet. I originally thought it will be added like ComposableCoreLocation and CoreMotion inside this repository. But it would be easy to extract it into a new repository if it is not wished.

**Comment by ph1ps** [comment]
I'll close this issue for now and I will create a WIP pull request.
