### ISSUE TITLE
Sendable warnings (Animation)

### ISSUE THREAD

**Issue by TosinAF** [pointfreeco/swift-composable-architecture#2539]
### Description

It seems that there a few sendable warnings in the Animation File when using Xcode 15.

ComposableArchitecture/Effects/Animation.swift:50:31: warning: capture of 'transaction' with non-sendable type 'Transaction' in a `@Sendable` closure
              withTransaction(transaction) {
              
SwiftUI.Transaction:2:23: note: struct 'Transaction' does not conform to the 'Sendable' protocol
@frozen public struct Transaction {

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [x] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### The Composable Architecture version information

1.2.0

### Destination operating system

iOS 16

### Xcode version information

Xcode 15

### Swift Compiler version information

```shell
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx13.0
```

**Comment by TosinAF** [comment]
<img width="1512" alt="Screenshot 2023-11-02 at 11 19 06 AM" src="https://github.com/pointfreeco/swift-composable-architecture/assets/2206858/85f0c649-0725-4186-814d-aa89d5113251">

**Comment by acosmicflamingo** [comment]
@TosinAF what color scheme is that? It's beautiful :)
