### ISSUE TITLE
Drop `Equatable` constraint for `Value` in `_OnChangeReducer`

### ISSUE THREAD

**Issue by lukaskubanek** [pointfreeco/swift-composable-architecture#2544]
### Description

I tried to utilize `Reducer.onChange(of:removeDuplicates:)` for comparing tuples extracted from the state, as shown [in the documentation of this method](https://pointfreeco.github.io/swift-composable-architecture/main/documentation/composablearchitecture/reducer/onchange(of:removeduplicates:_:)/#discussion). However, `_OnChangeReducer` maintained the `Equatable` constraint for its `Value` generic type after implemeting #2338, which is why the documented usage isn’t valid.

Here’s a minimal example for which Xcode isn’t even able to generate a diagnostic:

```swift
import ComposableArchitecture

internal struct MyReducer: Reducer {
    
    internal struct State: Equatable {
        internal let foo: String
        internal let bar: String
    }
    
    internal enum Action: Equatable {}
    
    internal var body: some ReducerOf<Self> {
        EmptyReducer()
            .onChange(
                of: { ($0.foo, $0.bar) },
                removeDuplicates: ==
            ) { oldValue, newValue in
                EmptyReducer()
            }
    }
    
}
```

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### The Composable Architecture version information

1.3.0

**Comment by stephencelis** [comment]
@lukaskubanek That was an oversight for sure. Would you like to tackle a PR to fix?
