### ISSUE TITLE
Local shared environment problem

### ISSUE THREAD

**Issue by maximkrouk** [pointfreeco/swift-composable-architecture#255]
Hello, I tried to find a solution at Swift forum, but I couldn't so I'm submitting an issue.

I'm using UIKit, AVFoundation & [ReactiveSwiftComposableArchitecture](https://github.com/trading-point/reactiveswift-composable-architecture) but the question is related to the architecture itself. I'd like to share the environment with a viewController and store. My VC has a [SZAVPlayer](https://github.com/eroscai/SZAVPlayer) (_UIView_), which is responsible for all the AV-stuff and I'd like to have a client for this object to put it in the environment, but the player object is created later than the viewController, which is initialized by the store.

As far as I understand - I don't have to keep SZAVPlayer object in a view hierarchy, but I have to handle CGImage output, which is not Equatable so it's not convenient to put it in State. I'm gonna try implementing the conformance myself. But maybe someone can give me an advice how to do it in a better way. 🙂

**Comment by stephencelis** [comment]
Hey @maximkrouk! We use GitHub issues for bugs and try to keep more general discussion on [the Swift forum](https://forums.swift.org/c/related-projects/swift-composable-architecture). This also makes it easier for folks to follow just general discussion or just issues. Wanna bring your question there?

As a potential answer, though, you may wanna wrap the image data in your own type that you can conform, and then you may be able to use `memcmp` for a quick implementation.

**Comment by maximkrouk** [comment]
Thank you for the reply, I migrated the topic to here https://forums.swift.org/t/local-shared-environment/39465
