### ISSUE TITLE
When using switch store onAppear method not being ran in child

### ISSUE THREAD

**Issue by Muhammed9991** [pointfreeco/swift-composable-architecture#2557]
### Description

I came across a similar issue as shown in the closed issue  #2403. I was getting a crash but it was solved using the solution provided by @stephencelis:

```swift
IfLetStore(store.scope(state: \.color, action: { .color($0) })) { colorStore in
  SwitchStore(colorStore) { state in
    switch state {
    case .red:
      CaseLet(
        /Feature.Color.State.red,
        action: Feature.Color.Action.red
      ) { store in
        RedView(store: store)
      }
    case .blue:
      CaseLet(
        /Feature.Color.State.blue,
        action: Feature.Color.Action.blue
      ) { store in
        BlueView(store: store)
      }
    }
  }
}
```

Issue I am having is that with this solution the project does compile and run but each view has its own `onAppear` inside it. None of these are being ran. I can put a breakpoint at the onAppear and it does get to that point but putting a break point on the underlying action inside the reducer. The action isn't being sent.

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

I would expect the underlying onAppear method to be ran every time the view appears i.e. becomes non-nil.

### The Composable Architecture version information

1.3.0

### Destination operating system

iOS 17.0.1

### Xcode version information

Xcode 15.0.1

### Swift Compiler version information

```shell
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx14.0
```

**Comment by mbrandonw** [comment]
Hi @Muhammed9991, I am going to close this because you have an existing conversation [here](https://github.com/pointfreeco/swift-composable-architecture/discussions/2404#discussioncomment-7520043), and I don't think this is an issue with the library itself.
