### ISSUE TITLE
Static dependencies

### ISSUE THREAD

**Issue by KostyaGitWoddi** [pointfreeco/swift-composable-architecture#2585]
### Description

Dynamic dependencies make issue and may broke some tools (Like codegen)

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

Make internal dependencies with static versions for possibility move to previous if something will broken

### Actual behavior

[
    .package(url: "https://github.com/apple/swift-collections", from: "1.0.2"),
    .package(url: "https://github.com/apple/swift-docc-plugin", from: "1.0.0"),
    .package(url: "https://github.com/google/swift-benchmark", from: "0.1.0"),
    .package(url: "https://github.com/pointfreeco/combine-schedulers", from: "1.0.0"),
    .package(url: "https://github.com/pointfreeco/swift-case-paths", from: "1.1.0"),
    .package(url: "https://github.com/pointfreeco/swift-concurrency-extras", from: "1.1.0"),
    .package(url: "https://github.com/pointfreeco/swift-custom-dump", from: "1.0.0"),
    .package(url: "https://github.com/pointfreeco/swift-dependencies", from: "1.0.0"),
    .package(url: "https://github.com/pointfreeco/swift-identified-collections", from: "1.0.0"),
    .package(url: "https://github.com/pointfreeco/swiftui-navigation", from: "1.1.0"),
    .package(url: "https://github.com/pointfreeco/xctest-dynamic-overlay", from: "1.0.0"),
  ]

### Steps to reproduce

setup project using [Tuist](https://github.com/tuist/tuist) and setup TCA dependency

### The Composable Architecture version information

1.2.0

### Xcode version information

15.0.1

**Comment by KostyaGitWoddi** [comment]
I agree with u, it's issue with Tuist, but I have no way to return to the working version because of the TCA dynamic dependencies (only override your dependencies locally...it doesn't best practice)

**Comment by mbrandonw** [comment]
TCA does not have any dynamic dependencies. How are you suggesting that this library could help your situation?
