### ISSUE TITLE
Extension for Reducer.State/Action causes a compilation error with the new @Reducer macros

### ISSUE THREAD

**Issue by rock88** [pointfreeco/swift-composable-architecture#2587]
### Description

Hello! I have updated to ComposableArchitecture 1.4.2 and am trying to use the new macros.
And if I use extensions for "Reducer.State/Action" I get compilation errors, you can see this in the Steps to reproduce section.

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

The code should compile without errors.

### Actual behavior

The code doesn't compile.

### Steps to reproduce

I have a few extensions for `Reducer.State` in my code like:

```swift
struct Test: Reducer {
    struct State {}
    struct Action {}

    func reduce(into state: inout State, action: Action) -> Effect<Action> {
        .none
    }
}

extension Test.State {
    static let initial: Self = ...
}
```

And if I replace the `Reducer` protocol with the `@Reducer` macro, I get the following compilation errors:

```swift
@Reducer                  // Error: Circular reference resolving attached macro 'Reducer'
struct Test {             // Error: Circular reference
    struct State {}
    struct Action {}

    func reduce(into state: inout State, action: Action) -> Effect<Action> {
        .none
    }
}

extension Test.State {    // Error: 'State' is not a member type of struct 'Test'
    static let initial: Self = ...
}
```

If move `static let Initial` to `struct State` everything is ok:

```swift
@Reducer
struct Test {
    struct State {
        static let initial: Self = ...
    }

    struct Action {}

    func reduce(into state: inout State, action: Action) -> Effect<Action> {
        .none
    }
}
```

### The Composable Architecture version information

1.4.2

### Destination operating system

macOS 13

### Xcode version information

Xcode 15.0.1

### Swift Compiler version information

```shell
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx14.0
```

**Comment by mbrandonw** [comment]
Hi @rock88, this is an issue with the Swift compiler unfortunately, not this library. We have documented this issue [here](https://pointfreeco.github.io/swift-composable-architecture/main/documentation/composablearchitecture/reducer()#Circular-reference-errors).

**Comment by rock88** [comment]
@mbrandonw Oh I missed this info, sorry
