### ISSUE TITLE
Circular reference error using @Reducer with an extension on reducer's State 

### ISSUE THREAD

**Issue by danthorpe** [pointfreeco/swift-composable-architecture#2589]
### Description

Following the migration to v1.4, dropping `Reducer` protocol and adding `@Reducer` macro can introduce compile time errors if you happen to have an extension on the reducer's State.

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

I would expect to be able to use common Swift language features such as creating an extensions on the Reducer's `State` or `Action` nested types.

Beyond a toy application, it is probably very common to add utility mutating functions, or computed properties etc to make code more readable and organised.

### Actual behavior

With each extension on the reducer's `State` nested type, the compiler gets a circular reference.

<img width="924" alt="Screenshot 2023-11-23 at 12 40 33" src="https://github.com/pointfreeco/swift-composable-architecture/assets/309420/bf303e8d-a34d-4302-886b-07f373df03ba">

### Steps to reproduce

Here is a minimum reproduction of the issue.

Here is a minimum reproduction:

```swift
import ComposableArchitecture

@Reducer
struct CounterFeature {
    struct State: Equatable {
        var count = 0
    }
    enum Action {
        case incrementButtonTapped
        case decrementButtonTapped
    }
    var body: some ReducerOf<Self> {
        Reduce { state, action in
            switch action {
            case .incrementButtonTapped:
                state.count += 1
                return .none
            case .decrementButtonTapped:
                state.count -= 1
                return .none
            }
        }
    }
}

/// Comment this out to get @Reducer building correctly
extension CounterFeature.State {
    // e.g. expose a computed property
}
```

### The Composable Architecture version information

1.4.2

### Destination operating system

iOS 17

### Xcode version information

Xcode 15.0

### Swift Compiler version information

```shell
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx13.0
```

**Comment by mbrandonw** [comment]
Hi @danthorpe, this is an issue with the Swift compiler unfortunately, not this library. It has been reported to us multiple times, but only Apple can fix this. 

We have documented the problem [here](https://pointfreeco.github.io/swift-composable-architecture/main/documentation/composablearchitecture/reducer()#Circular-reference-errors), and an [issue](https://github.com/apple/swift/issues/66450) has been filed with Apple. I highly recommend chiming in on that issue to make sure Apple understands how easy it is to run into this problem.

Since this is not an issue with this library I am closing this.

**Comment by danthorpe** [comment]
Thanks for the speedy response @mbrandonw
