### ISSUE TITLE
Doesn't work on Xcode 11.4.1

### ISSUE THREAD

**Issue by formacion-tyris** [pointfreeco/swift-composable-architecture#27]
I tried to use it, and if I build and run it all works, but SwiftUI previews are broken:

`warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'ComposableArchitecture' from project 'swift-composable-architecture')
warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'ComposableArchitecture' from project 'swift-composable-architecture')
warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'ComposableArchitecture' from project 'swift-composable-architecture')
<unknown>:0: error: unable to execute command: Abort trap: 6
<unknown>:0: error: compile command failed due to signal 6 (use -v to see invocation)`

I'm not sure if it's not prepared for this version or if it's some local config.

**Comment by stephencelis** [comment]
@formacion-tyris Can you attach a project that fails to build and provide more information for how to reproduce? Xcode previews are a bit finicky in general and sometimes you need to do some dance of build, clean, delete derived data, quit and reopen Xcode, etc., to get them working.

Also: have you cloned the repo and tried the example projects? They should all build and have working previews.

**Comment by stephencelis** [comment]
(This may be related to #22.)

**Comment by stephencelis** [comment]
@formacion-tyris Fixed this via #31! If you still encounter this issue with version 0.1.2 of the library, please let me know!
