### ISSUE TITLE
Tutorial documentation bug in TCA 1.5.6

### ISSUE THREAD

**Issue by randomeizer** [pointfreeco/swift-composable-architecture#2700]
### Description

I was working my way through the TCA tutorial docs [here](https://pointfreeco.github.io/swift-composable-architecture/main/tutorials/composablearchitecture/02-03-testingpresentation) and got jammed at the points where we are "Testing the add contact flow". It suggests adding the following to expect a 'receive' of the save contact action:

```swift
    await store.receive(
      \.destination.addContact.delegate.saveContact,
      Contact(id: UUID(0), name: "Blob Jr.")
    ) {
    }
```

I had to watch Vincent's walkthrough to get the correct syntax, which is:

```swift
    await store.receive(
        .destination(.presented(.addContact(.delegate(.saveContact(Contact(id: UUID(0), name: "Blob Jr."))))))
    ) {
    }
```

I'm guessing this is a half-done update to the new macro-based syntax?

It's also missing some steps to add `Equatable` to various `Action` types, which means I don't get much help from the compiler when just guessing the answer either.

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

Expected the sample code to compile.

### Actual behavior

Sample code did not compile.

### The Composable Architecture version information

1.5.6

**Comment by stephencelis** [comment]
@randomeizer That syntax is on `main` and is for 1.6, which hasn't been released yet. We'll have to correct that soon, sorry for the confusion!
