### ISSUE TITLE
.debug() not working in custom configurations

### ISSUE THREAD

**Issue by gkaimakas** [pointfreeco/swift-composable-architecture#274]
**Describe the bug**
Not sure if this an issue of CA or something I might have missed but I am facing the following:

I have created a new project, renamed debug scheme to dev and copied it to create another one called staging. 
I have also edited each scheme to use the correct configuration.
I did not edit/delete/create any new Custom Flags / Active compilation conditions.

When I call `.debug()` in one of my reducers it does not print anything to the console.
I have also tried to use `#if DEBUG` directly on my project, which surprisingly, works.

**To Reproduce**
The behaviour I am seeing can be reproduced here: 
[CADebugBug.zip](https://github.com/pointfreeco/swift-composable-architecture/files/5155131/CADebugBug.zip)

**Expected behavior**
`.debug()` should print on the console.

**Environment**
 - Xcode [Version 11.6 (11E708)]
 - Swift [5.2.2]
 - OS: [iOS 13.6]
 - CA version: 0.7.0

**Comment by mathieutozer** [comment]
I've been experiencing this too.

**Comment by kaishin** [comment]
I have noticed this too in a similar setup.

**Comment by AlexisQapa** [comment]
IIRC SPM doesn't support custom configurations for now (only debug and release) and Xcode tries to map your configuration name to either debug or release. If you rename your configuration to DevDebug Xcode might build your SPM dependencies with the debug configuration. You might want to differentiate configurations from schemes and use only two configurations and a scheme per environment.

**Comment by kaishin** [comment]
I solved by renaming the configuration to Debug for now. Thanks for the pointer @AlexisQapa!

**Comment by stephencelis** [comment]
This is a known issue being tracked by Apple

- https://forums.swift.org/t/swift-package-manager-and-custom-build-configurations/29181/5
- https://forums.swift.org/t/custom-build-configuration-names/29167/2

I'm going to convert this to a discussion in case folks would like to share their various workarounds.
