### ISSUE TITLE
`CaseStudy/SwiftUI/Alerts & ActionSheets` Exception on Increment

### ISSUE THREAD

**Issue by Mozahler** [pointfreeco/swift-composable-architecture#279]
This occurs using the zip downloaded from this site this week -- out of the box. 
On the device (iPhone XS Max iOS 13.6) and in simulator (iOS 13.6, iOS 13.7)
It also occurs using a zip downloaded at the beginning of August.

**To Reproduce**
Compile "Case Studies (SwiftUI)" scheme using the ComposableArchitecture.xcworkspace
run the example and select "Alert & ActionSheets"
Select Alert, click on the "Increment" button on the alert
This results in an exception.

**Expected behavior**
Alert to dismiss with counter incremented

This is called twice after tapping on "Increment", the exception occurs after the second .toSwiftUI(send:) call.
 ```
  WithViewStore(store, removeDuplicates: { $0?.id == $1?.id }) { viewStore in
      self.alert(item: viewStore.binding(send: dismiss)) { state in
        state.toSwiftUI(send: viewStore.send)
      }
    }
```
And these lines in the log stand out to me:

SwiftUI`SwiftUI.AlertBridge.preferencesDidChange(SwiftUI.PreferenceList) -> ():

; partial apply forwarder for closure #1 () -> () in SwiftUI.AlertBridge.preferencesDidChange(SwiftUI.PreferenceList) -> ()

` $defer #1 <A, B where A: SwiftUI.View, B: SwiftUI.AlertControllerConvertible, B.Key.Value == Swift.Optional<B>>() -> () in SwiftUI.AlertBridge.preferencesDidChange(SwiftUI.PreferenceList) -> ()

`**Screenshots**
<img width="130" alt="Screen Shot 2020-09-05 at 10 40 15 AM" src="https://user-images.githubusercontent.com/9641531/92307431-8677fd00-ef64-11ea-9a14-4765b697e927.png">

<img width="1402" alt="Screen Shot 2020-09-05 at 10 52 03 AM" src="https://user-images.githubusercontent.com/9641531/92307858-5e3dcd80-ef67-11ea-81c2-32250ea64723.png">

**Environment**
 - Xcode Version 11.7 (11E801a)
 - Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
Target: On the device (iPhone XS Max iOS 13.6) and in simulator (iPhone SE 2nd Generation, iOS 13.6, iOS 13.7)

 - OS: MacOS Catalina 10.15.6 (19G73)

I just applied the latest Catalina update and the problem remains.

**Comment by stephencelis** [comment]
Interesting. Xcode 11.6 and 12 do not appear to have this problem, which leads me to believe it's an Apple bug, especially with that stack trace. We'll file a feedback and think about potential workarounds.

**Comment by stephencelis** [comment]
Filed: https://gist.github.com/stephencelis/11746b8acb751d8b57f3528e0d3af603

It's easy to reproduce in vanilla SwiftUI so I don't think we can consider this a TCA bug. I think the workaround is to `nil` out the alert state and then fire off an effect that will later show the followup increment alert. I'm not sure we want to complicate the demo, though, just for a bug in one version of Xcode.

**Comment by Mozahler** [comment]
Thanks for the quick response. Closing.
