### ISSUE TITLE
Adding swift-composable-architecture to a swift package as a dependency 

### ISSUE THREAD

**Issue by mycroftcanner** [pointfreeco/swift-composable-architecture#280]
**Describe the bug**

**To Reproduce**

Create a blank Swift Package called Example.

`Packages.swift`:

```swift
// swift-tools-version:5.3
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "Example",
    platforms: [
      .iOS(.v13),
      .macOS(.v10_15),
    ],
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "Example",
            targets: ["Example"]),
    ],
    dependencies: [
      .package(
        url: "https://github.com/pointfreeco/swift-composable-architecture.git",
        from: "0.8.0"
      )
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .target(
            name: "Example",
            dependencies: ["swift-composable-architecture"]),
        .testTarget(
            name: "ExampleTests",
            dependencies: ["Example"]),
    ]
)
```

>error: product 'swift-composable-architecture' not found. It is required by target 'Example'.

Maybe I have to use the package name? let's try again:

> error: dependency 'ComposableArchitecture' in target 'Example' requires explicit declaration; reference the package in the target dependency with '.product(name: "ComposableArchitecture", package: "swift-composable-architecture")'

The following specification works:

```swift
    .target(
      name: "Example",
      dependencies: [
        .product(name: "ComposableArchitecture", package: "swift-composable-architecture")
      ]
    ),
```

**Expected behavior**

A simple `.package(url: "https://github.com/pointfreeco/swift-overture.git", from: "0.5.0")'` should just work. 

To add `QueryKit` or any other depencency I just need something like this :

```swift
  dependencies: [
    .package(url: "https://github.com/QueryKit/QueryKit.git", .branch("master"))
  ],
  targets: [
    .target(
      name: "Example",
      dependencies: [
        "QueryKit"
      ]
    ),
    .testTarget(name: "ExampleTests", dependencies: ["Example"]),
  ]
```

**Environment**
 - Xcode Version 12.0 beta 6 (12A8189n)
 - Apple Swift version 5.3 (swiftlang-1200.0.28.1 clang-1200.0.30.1)
 - Target: x86_64-apple-darwin20.0.0

**Additional context**

To add to the confusion Overture behaves completely differently:

```swift
  dependencies: [
    .package(url: "https://github.com/pointfreeco/swift-overture", from: "0.5.0")
  ],
  targets: [
    .target(
      name: "Example",
      dependencies: [
        "swift-overture"
      ]
    ),
    .testTarget(name: "ExampleTests", dependencies: ["Example"]),
  ]
```

> error: product 'swift-overture' not found. It is required by target 'Example'.
warning: dependency 'Overture' is not used by any target

Ok let's do the same we did with `ComposableArchitecture` and use `.product(name: "Overture", package: "swift-overture.git"),`

> error: unknown package 'swift-overture.git' in dependencies of target 'Example'

Ok, let's use only "Overture" then...

```swift
  dependencies: [
    .package(url: "https://github.com/pointfreeco/swift-overture", from: "0.5.0")
  ],
  targets: [
    .target(
      name: "Example",
      dependencies: [
        "Overture"
      ]
    ),
    .testTarget(name: "ExampleTests", dependencies: ["Example"]),
  ]
```

>error: dependency 'Overture' in target 'Example' requires explicit declaration; provide the name of the package dependency with '.package(name: "Overture", url: "https://github.com/pointfreeco/swift-overture.git", from: "0.5.0")'

The following `Packages.swift` finally works but lacks consistency and it took a long and confused while to figure out.

```swift
import PackageDescription

let package = Package(
  name: "Example",
  platforms: [
    .iOS(.v13),
    .macOS(.v10_15),
  ],
  products: [
    .library(name: "Example", targets: ["Example"]),
  ],
  dependencies: [
    .package(url: "https://github.com/pointfreeco/swift-composable-architecture.git", from: "0.8.0"),
    .package(name: "Overture", url: "https://github.com/pointfreeco/swift-overture.git", from: "0.5.0"),
    .package(url: "https://github.com/QueryKit/QueryKit.git", .branch("master"))
  ],
  targets: [
    .target(
      name: "Example",
      dependencies: [
        .product(name: "ComposableArchitecture", package: "swift-composable-architecture"),
        "Overture",
        "QueryKit"
      ]
    ),
    .testTarget(name: "ExampleTests", dependencies: ["Example"]),
  ]
)
```

**Comment by maximkrouk** [comment]
As far as I understand Swift Package Manager can't resolve packages with an inconsistency in URL/Name/Product names if u use `StringLiteral` representation. That's why SPM has explicit dependency management mechanisms. I would advise you to always use explicit declarations in SPM.

To @pointfreeco:
But to fix the inconsistency it may be nice to rename that package to `ComposableArchitecture` in `Package.swift` file, that should help 🙂

**Comment by stephencelis** [comment]
Hey @mycroftcanner! We've been trying to adopt the pattern used in Apple's libraries, like [swift-nio](https://github.com/apple/swift-nio/blob/98721c75b09fde85f549e5692653e09ba3837944/Package.swift#L85), but some of our early libraries like Overture have not been updated to be consistent with this pattern. Would you be up for opening up an issue (or even PR, if you have time time!) on Overture instead? We've updated some other libraries already, like Gen and Tagged, but haven't gotten around to Overture and some others quite yet.
