### ISSUE TITLE
Composable 1.8.1 - Destination with only AlertState generates empty body

### ISSUE THREAD

**Issue by jaanussiim** [pointfreeco/swift-composable-architecture#2829]
### Description

Following Destination will generate an empty reducer body that causes a compile failure

```import ComposableArchitecture

@Reducer
public struct Feature {
  @Reducer
  public enum Destination {
    case alert(AlertState<AlertAction>)
    
    public enum AlertAction {
      
    }
  }
}
```

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### The Composable Architecture version information

1.8.1

**Comment by mbrandonw** [comment]
This has been fixed in 1.8.2.
