### ISSUE TITLE
ForEachStore is not included in the documentation

### ISSUE THREAD

**Issue by MaxDesiatov** [pointfreeco/swift-composable-architecture#284]
**Describe the bug**
`ForEachStore` documentation is not available on [the documentation page](https://pointfreeco.github.io/swift-composable-architecture/)

**To Reproduce**
Navigate to the documentation page.

**Expected behavior**
`ForEachStore` is available on the documentation page.

**Screenshots**
N/A

**Environment**
Any environment.

**Additional context**
I wasn't able to find any documentation about `ForEachStore` in `README.md` either.

**Comment by mbrandonw** [comment]
Hey @MaxDesiatov, thanks for the heads up. However, I'm able to find the docs for `ForEachStore`:

https://pointfreeco.github.io/swift-composable-architecture/ForEachStore/

And it's listed on the homepage:

<img width="841" alt="image" src="https://user-images.githubusercontent.com/135203/92669279-15777300-f2df-11ea-95d1-be2458af1c44.png">

The docs are a little scant right now, we should probably improve that soon 😬.

**Comment by MaxDesiatov** [comment]
Thanks, for some reason it didn't come up on the docs page when I was doing a simple text search, maybe I made a typo.

**Comment by stephencelis** [comment]
Gonna close this out. Let us know if there's anything else!
