### ISSUE TITLE
TicTacToe Crash When Interrupting 2FA Login

### ISSUE THREAD

**Issue by nmccann** [pointfreeco/swift-composable-architecture#289]
**Describe the bug**
When running the TicTacToe application, it is possible to interrupt a long lived side effect on the Two Factor Authentication screen, which results in a crash due to an assertion:
`Fatal error: "LoginAction.twoFactorDismissed" was received by an optional reducer when its state was "nil".`

**To Reproduce**
* Run TicTacToe example project
* Select SwiftUI (though the same bug affects the UIKit version)
* Login with an email containing `2fa`
* Enter `1234` code
* Tap Submit
* Before request completes, press "< Login" in the top left corner
* App crashes due to fatal error

**Expected behavior**
App should return to login screen without crashing

**Environment**
- Xcode 11.7

**Additional context**
This sounds similar to #259 , but isn't quite the same error.
This also sounds similar to the issue [discussed in the forums here](https://forums.swift.org/t/ifletstore-and-effect-cancellation-on-view-disappear/38272), and might be able to be fixed by the solution described there.

This issue covers one of the biggest unknowns I have with this architecture - you're incentivized to break up your code into reducers that focus on a particular task and child reducers don't need to know about their parents, however if the parent has an optional child, then that child needs to expose some way of cancelling all active effects so that the parent can clean up after them (which, as a parent, that is pretty realistic but not super convenient). 

It'd be nice to see a canonical example of handling an optional child with long lived side effects that could get interrupted/cancelled. And if explicitly sending a "cancel" action to the child is the expected process, is there a better way to scale that? For example, if you have an optional child which itself has optional children with side effects that need to be canceled, it gets complicated.

**Comment by stephencelis** [comment]
Good find! That's definitely a bug! And it's one that was reproducible pretty quickly in a test. The fix (and test) are for your perusal here: https://github.com/pointfreeco/swift-composable-architecture/pull/291

**Comment by stephencelis** [comment]
> It'd be nice to see a canonical example of handling an optional child with long lived side effects that could get interrupted/cancelled. And if explicitly sending a "cancel" action to the child is the expected process, is there a better way to scale that? For example, if you have an optional child which itself has optional children with side effects that need to be canceled, it gets complicated.

Absolutely. We'll have a brainstorm on more complex examples like this. If you have any ideas feel free to chime in!

**Comment by nmccann** [comment]
Thank you for the quick response and solution!

**Comment by stephencelis** [comment]
Fixed the crash but will continue to explore more solutions to this common problem. We have a few ideas but wanna test them out to figure out and better understand the tools we should provide and their trade-offs.

**Comment by nmccann** [comment]
Should this be closed given that the fix has been merged? Or left open until a more general solution is available?

**Comment by stephencelis** [comment]
I think we can probably close it out. If we want to track a general solution we could open another issue. Feel free to in order to pester us if we lose track 😄
