### ISSUE TITLE
[Breaking change,  0.8.0] AlertState expects LocalizedStringKey instead of String values

### ISSUE THREAD

**Issue by ohitsdaniel** [pointfreeco/swift-composable-architecture#293]
#275 introduced the ability to localise values based on `LocalizedStringKey`s. We pass the localized values directly into our AlertStates as we're using SwiftGen to generate type-safe string accessors. 

@stephencelis asked directly in #275 if TCA should still offer an initialiser that accepts `S: StringProtocol`. Is there anything that would speak against that? If not, I'm happy to open a PR for it. 🙂

**Comment by stephencelis** [comment]
@ohitsdaniel Any chance you can use `LocalizedStringKey.init(verbatim:)` for this? We can definitely consider the overloads in the future, but this should get things working for you in the meantime.

**Comment by ohitsdaniel** [comment]
<img width="707" alt="Screenshot 2020-09-22 at 08 07 39" src="https://user-images.githubusercontent.com/9058860/93848885-19c26980-fcab-11ea-8b8d-e7b13f0a2f7b.png">

Unfortunately, the verbatim initialiser option is not available directly on LocalizedStringKey, but only the `Text` view offers that one. And all the string literal options exist to make the keys expressible as plain text strings in code.

https://developer.apple.com/documentation/swiftui/localizedstringkey

**Comment by Muhammad-Usman-Ali** [comment]
We're using swift-gen for type safe strings and running into the same problem. `LocalizedStringKey.init(verbatim:)` isn't available. Any chance we can get @ohitsdaniel's MR merged in for `StringProtocol` support?

**Comment by imfractured** [comment]
having the same issue on my project, any way we can get this looked at please?
