### ISSUE TITLE
testScheduling causes EXC_BAD_INSTRUCTION on iOS 13.1 (simulator)

### ISSUE THREAD

**Issue by andreyz** [pointfreeco/swift-composable-architecture#297]
**Describe the bug**
Running tests causes crash inside testScheduling test case.

**To Reproduce**
Run tests on iOS 13.1 simulator.

**Expected behavior**
Tests should pass.

**Screenshots**
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/205317/94448082-ce2c2600-01aa-11eb-9c6e-36440bd77f5b.png">

**Environment**
 - Xcode 12.0 (12A7209)
 - Swift 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)
 - OS 13.1 (Simulator)

**Additional context**
Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
```
#0	0x00007fff5114b575 in specialized static Strideable.< infix(_:_:) ()
#1	0x00007fff51149e02 in protocol witness for static Comparable.<= infix(_:_:) in conformance OS_dispatch_queue.SchedulerTimeType ()
#2	0x000000010befc697 in TestScheduler.advance(by:) at /Users/xxx/Library/Developer/Xcode/DerivedData/ComposableArchitecture-apscvllgqcqyyhehssbaablycmqr/SourcePackages/checkouts/combine-schedulers/Sources/CombineSchedulers/TestScheduler.swift:83
#3	0x000000010be91bf1 in closure #2 in ComposableArchitectureTests.testScheduling() at /Users/xxx/Projects/Sandbox/swift-composable-architecture/Tests/ComposableArchitectureTests/ComposableArchitectureTests.swift:50
#4	0x000000010bf743b7 in TestStore<>.assert(_:file:line:) at /Users/xxx/Projects/Sandbox/swift-composable-architecture/Sources/ComposableArchitecture/TestSupport/TestStore.swift:382
#5	0x000000010bf713a6 in TestStore<>.assert(_:file:line:) at /Users/xxx/Projects/Sandbox/swift-composable-architecture/Sources/ComposableArchitecture/TestSupport/TestStore.swift:214
#6	0x000000010be90909 in ComposableArchitectureTests.testScheduling() at /Users/xxx/Projects/Sandbox/swift-composable-architecture/Tests/ComposableArchitectureTests/ComposableArchitectureTests.swift:48
#7	0x000000010be91e4b in @objc ComposableArchitectureTests.testScheduling() ()
```

**Comment by andreyz** [comment]
Seems somehow related to [another Combine issue](https://forums.swift.org/t/exc-bad-instruction-with-combine-throttle/28850/3).

**Comment by stephencelis** [comment]
There have been a bunch of Combine bugs over the course of various versions of iOS, unfortunately 😞 In general we'd recommend running tests on a more recent version of iOS. We're definitely open to a workaround if anyone finds it, though it would need to be on the upstream dependency here: https://github.com/pointfreeco/combine-schedulers

Wanna close this and reopen the issue there if you think it's worth addressing?

**Comment by andreyz** [comment]
I understand. The reason I've posted this is that my recently TCA-migrated seems to behave very strange on iOS 13.1 devices I've tested.

The issue is with alerts and sheets not being displayed, but triggered by the view store publishers after the presenting view is dismissed, setting off the assert in TCA. 

I've tried investigating by first attempting to run the tests. Alas, that was crashing.

**Comment by andreyz** [comment]
Regarding your actual comment, if TCA to ever be considered a serious framework, it's a good idea to make sure that tests pass on all iOS versions the framework claims to support.

**Comment by stephencelis** [comment]
@andreyz We'd love to get this test passing for that outlier platform if you'd like to give it a try! The fix would belong in combine-schedulers, though, since that's where the test scheduler lives. Since this bug only affects the test scheduler on some older platforms (and so it shouldn't affect production applications), we haven't prioritized a fix over other things, but that doesn't mean we wouldn't love some help if you have time! Want to close this out and either open up an issue over at [combine-schedulers](https://github.com/pointfreeco/combine-schedulers) or, better yet, a PR? :smile:
