### ISSUE TITLE
[Question] Compatibility iOS versions < 13

### ISSUE THREAD

**Issue by pietrocaselani** [pointfreeco/swift-composable-architecture#3]
Hello!

First, thanks for making this open source, amazing work everyone!

Since I started watching the videos I was concerned about the use of Combine and how it would affect adoption for codebases that can't deploy to iOS >= 13.

I know we can achieve the same results using Rx/ReactiveSwift but a lot of change is necessary, and keeping forks with this doesn't sound like a good idea, so I would like to know what are your thoughts on this?

(If this is not the best place to ask this, let me know so we redirect)

Thanks again!

**Comment by stephencelis** [comment]
Hi @pietrocaselani!

Thanks for the question. The architecture is totally possible to implement in Rx/ReactiveSwift (or even a custom solution using your own Effect type), but for straightforwardness in the future of the Apple ecosystem we've tied ourselves to Combine for now.

We're definitely open to a plug-and-play solution with other reactive frameworks if it's possible! But for the foreseeable future Combine will be a requirement.

Other Point-Free viewers have built RxSwift versions of the Composable Architecture to support iOS 11 and 12, so we may be able to point you to their solutions should any of them open source it.

**Comment by pietrocaselani** [comment]
Thanks for your quick reply @stephencelis! 

> "Other Point-Free viewers have built RxSwift versions of the Composable Architecture to support iOS 11 and 12"

Yes, I saw other implementations and I already implement using Rx when TCA was in the early stage of development 😉 

Let me dig and explore more the library and examples during the week, then I can start thinking in a solution plug-and-play.

I will close this for now, and if the subject comes up again we can reopen it.

Thanks Stephen!

**Comment by yixe** [comment]
Please don't make the library cumbersome, keep it focused on the future.
