### ISSUE TITLE
Example issue with Todo

### ISSUE THREAD

**Issue by fatlazycat** [pointfreeco/swift-composable-architecture#300]
https://pointfreeco.github.io/swift-composable-architecture/Reducer/#reducer.foreach(state:action:environment:_:_:)

states 

Take care when combining forEach reducers into parent domains, as order matters. Always combine forEach reducers before parent reducers that can modify the collection

The example Todo reducer has parent first.

Thanks

**Comment by stephencelis** [comment]
Ah yes, thanks! Luckily in this case we weren't (yet) working with child effects that would be problematic, but it's a general rule to follow. Fix in #301!
