### ISSUE TITLE
Strange List Behavior

### ISSUE THREAD

**Issue by m-housh** [pointfreeco/swift-composable-architecture#302]
I'm getting strange behavior inside of List's using TCA.  I'm kind of guessing this is not a TCA problem as when you inspect the state using `debug` on a reducer the state appears to be correct.  I've created a sample repository https://github.com/m-housh/TCA_ListBug.git.
![TCA_ListBug_Example](https://user-images.githubusercontent.com/9305678/95090198-ffe54580-06f2-11eb-993c-838451ac7bf8.gif)

![TCA_ListBug_Example2](https://user-images.githubusercontent.com/9305678/95090202-01167280-06f3-11eb-8d33-287ba100aeae.gif)

**Comment by m-housh** [comment]
Sorry, I got rushed out of the office as I was submitting this issue... So to explain a little further, when moving rows in a list sometimes the row gets extra padding / spacing around it, which can be seen in the first example gif above.  The other problem that I have not been able to reproduce outside of my larger application (that I can't make public) is the second gif posted above where rows disappear sometimes when moving rows in a list, if you delete the visible row then the remaining list items will appear, both scenarios show the proper state changes when using `debug` on a reducer, which makes me wonder if this is an apple bug?

**Comment by stephencelis** [comment]
@m-housh Haven't encountered this particular issue yet. Have you tried reproducing in vanilla SwiftUI?

**Comment by m-housh** [comment]
@stephencelis Honestly, I had not... I played around with it using vanilla SwiftUI last night and the same thing happens, so I'm going to close this issue as it seems it is an apple bug.
