### ISSUE TITLE
Missing an expected key: 'NSPrivacyCollectedDataTypes'

### ISSUE THREAD

**Issue by OguzYuuksel** [pointfreeco/swift-composable-architecture#3021]
### Description

Missing an expected key: 'NSPrivacyCollectedDataTypes'
xxx.app/swift-composable-architecture_ComposableArchitecture.bundle/PrivacyInfo.xcprivacy

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Actual behavior

Error

### Steps to reproduce

- Open your project in Xcode.
- Choose Product > Archive. Xcode creates the archive and reveals it in the organizer.
- Control-click the archive in the organizer and choose Generate Privacy Report.
- Choose a location to save the privacy report.
- Switch to Finder.
- Navigate to the location where you saved the privacy report, and double-click to open the report in Preview.

### The Composable Architecture version information

1.10.0

### Xcode version information

15.3.0

### Swift Compiler version information

```shell
swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0
```

**Comment by mbrandonw** [comment]
Hi @OguzYuuksel, thanks for the report. Can you clarify whether or not this is preventing you from submitting your app to the App Store? Or is it just a warning?

@DandyLyons You added this file in #2930. Is there something missing from the plist that we need to add?

If we can't get this sorted in the next day or so we will have to remove the privacy file so that it does not cause issues for others.

**Comment by jshier** [comment]
Apple's latest update on the manifests seems to have removed the May 1st deadline, which hasn't passed yet. I'm not sure whether the lack of this key *would* be a blocking issue or whether it's just part of the PDF generation, but you can fix it by adding the proper empty root key.

```xml
<key>NSPrivacyCollectedDataTypes</key>
<array/>
```

**Comment by DandyLyons** [comment]
Thanks. I'll work on it now.

**Comment by OguzYuuksel** [comment]
Hello,
I was aiming to ensure compliance with Apple's updated privacy requirements for our app. Upon inspection, I noticed the reported issue. However, it seems that Apple has removed the May 1st deadline, so this issue is not currently blocker. 

@DandyLyons thank you for taking care of it.

**Comment by stephencelis** [comment]
@DandyLyons Don't want to step on your toes if you're in the middle of it, but if you can't get to the PR right now we can take care of it. We're about to merge a few other fixes and cut a patch release, so it'd be nice to get this into the fold :smile:

**Comment by DandyLyons** [comment]
Just posted it.
