### ISSUE TITLE
Dismiss more than one feature

### ISSUE THREAD

**Issue by nmalevich** [pointfreeco/swift-composable-architecture#3031]
### Description

I use tree-based navigation provided TCA. In some cases I need to dismiss to root feature. It works, but I see runtime warning about dismiss action that not handled because feature is nil.
I'm not sure that it's bug, but don't know how to remove this warning

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

You dismiss to root feature and not see runtime warning

### Actual behavior

You dismiss to root feature and see runtime warning

### Steps to reproduce

[LongDismissExample.zip](https://github.com/pointfreeco/swift-composable-architecture/files/15160333/LongDismissExample.zip)
1. You tap "Forward" button on the First screen and go to the Second
2. You tap "Forward" button on the Second screen and go to the Third
3. You tap "Back" button on the Third screen and return to the First
4. You see runtime warning

### The Composable Architecture version information

1.10.1

### Destination operating system

iOS 17.4

### Xcode version information

15.3

### Swift Compiler version information

```shell
swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
```

**Comment by stephencelis** [comment]
Thanks for the report! We'll be suppressing that warning in the next release, which should come later today.

I'll note that SwiftUI doesn't support nested navigation destinations like this very well, so you may want to consider stack navigation in the future, but if it works for you and the OSes you deploy to, at least you should be warning-free soon :smile:

**Comment by nmalevich** [comment]
Thank you too!
I will consider using stack navigation soon, thanks one more time
