### ISSUE TITLE
Nested enum reducer error: cannot be constructed because it has no accessible initializers

### ISSUE THREAD

**Issue by larryonoff** [pointfreeco/swift-composable-architecture#3047]
### Description

The case is pretty simple. The error occurs if you have nested macro-generated enum reducer (e.g. Feature1) in another macro-generated enum reducer (.e.g. Feature2).

Looks that issue occurs since Reducer macro doesn't take into account that macro-generated enum Reducers don't have inits.

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

No error occurs.

### Actual behavior

Compiler reports an error: `'Type' cannot be constructed because it has no accessible initializers`

### Steps to reproduce

See the code below.

```swift
@Reducer(state: .equatable)
enum Feature1 {
 case a
 case b
}

@Reducer(state: .equatable)
enum Feature2 {
 case feature1(Feature1)
}
```

### The Composable Architecture version information

1.10.2

### Xcode version information

Version 15.3 (15E204a)

### Swift Compiler version information

```shell
swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0
```

**Comment by larryonoff** [comment]
@stephencelis thank you! it works like a charm!

Is it in the docs already?

**Comment by stephencelis** [comment]
@larryonoff I don't believe it's documented yet, but we'll PR some later today!
