### ISSUE TITLE
Support for accuracyAuthorization API in ComposableCoreLocation

### ISSUE THREAD

**Issue by mackoj** [pointfreeco/swift-composable-architecture#306]
**Describe the bug**

Some part of `CLLocationManager` are not accessible in the the `LocationManager` like `accuracyAuthorization`.

**To Reproduce**

Try to call `accuracyAuthorization` on `LocationManager`.

**Expected behavior**

`LocationManager` should be a mirror of `CLLocationManager ` and propose the same feature.

**Environment**
 - Xcode 12
 - Swift 5.3
 - iOS 14

**Comment by stephencelis** [comment]
Thanks for the report, @mackoj! Did you wanna try to PR? If not we'll try to get to this sometime soon.

**Comment by mackoj** [comment]
I have a working patch I will submit a PR as soon as I can.
