### ISSUE TITLE
WithPerceptionTracking doesn't response on @AppStorage property change

### ISSUE THREAD

**Issue by artemkrachulov** [pointfreeco/swift-composable-architecture#3191]
### Description

I'm facing a problem when I have to update the interface when the property marked with the native `@AppStorage` property wrapper changes and UI-related code wrapped within `WithPerceptionTracking {}` view. But it doesn't respond. UI updates only when another source triggers a reload view. 

Here is an example:

```
struct SomeView: View {

  @Perception.Bindable var store: StoreOf<SomeState>

  @AppStorage("tapCount") 
  private var tapCount = 0

  var body: some View {
    WithPerceptionTracking {
      Button("Tap count: \(tapCount)") {
        tapCount += 1
      }
    }
  }
}
```

1. If replace  `@AppStorage("tapCount")` with `@State` it works. Only I have to use persistence
2. If remove `WithPerceptionTracking {}` also works, but **WithPerceptionTracking** error comes out.

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### The Composable Architecture version information

1.11.2

### Destination operating system

iOS 15

### Xcode version information

Version 15.4 (15F31d)

### Swift Compiler version information

```shell
Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: x86_64-apple-macosx14.0
```

**Comment by stephencelis** [comment]
This is an Apple bug, unfortunately. More here: https://github.com/pointfreeco/swift-perception/issues/68

**Comment by artemkrachulov** [comment]
Thank you
