### ISSUE TITLE
ForEachStore triggers unexpected redraws

### ISSUE THREAD

**Issue by ryanbooker** [pointfreeco/swift-composable-architecture#322]
I'm hoping I'm just doing something daft…

**Describe the bug**
When updating an Array state, and drawing via `ForEachStore`, e.g. new items added to the array, `ForEachStore` seems to redraw the original state, before drawing the new state.

If `ForEach` is used, only the new state is drawn.

**To Reproduce**
[TimelineUpdateTest.zip](https://github.com/pointfreeco/swift-composable-architecture/files/5544167/TimelineUpdateTest.zip)

**Expected behavior**
The old state is not redrawn before the new state.

**Environment**
 - Xcode [e.g. 12.2]
 - Swift [e.g. 5.3.x]
 - OS (if applicable): [e.g. iOS 14.2]

**Comment by mbrandonw** [comment]
Hi @ryanbooker, one thing that immediately jumps out at me with your code sample is that your are observing the entirety of the store in `ListView` even though you don't actually need any state from it. The only things you want to do with the `Store<[UUID], ListAction>` are send it an action (`.uuidsRequested`) and scope it for the `ForEachStore`. 

This is just something you have to think about when working with SwiftUI (and it applies to vanilla SwiftUI applications too). You have to keep in mind what state do you _actually_ need to observe, and are there opportunities to chisel it away to the bare essentials. Many times it doesn't matter if you observe a little more state than necessary, but if you really care about it then you have to be mindful.

So one thing you can do is simply not observe _any_ of the state:

```swift
WithViewStore(store.stateless) { viewStore in
```

That brings down the number of view computations. Does that get it closer to what you would expect?

**Comment by ryanbooker** [comment]
Brilliant. That's exactly what I expected to happen initially. As you may have surmised, I'm using SwiftUI as a vehicle to learn about TCA (working along with the videos was excellent by the way), and _vice versa_. Great tip. I'm glad it _was_ me doing something daft.

:)
