### ISSUE TITLE
View controller in navigation view is not popped even though binding is set accordingly

### ISSUE THREAD

**Issue by hanneskaeufler** [pointfreeco/swift-composable-architecture#323]
**Describe the bug**

The `NavigationLink` for the `"Navigate"` button doesn't pop the `ChildStateView` when contained inside a `List`, after tapping the `"Done!"` button.
I was able to distill the example such that the misbehaviour is shown when the following is true:
* There must be a second `NavigationLink`
* All of that must be enclosed in a `List`

**To Reproduce**
https://github.com/hanneskaeufler/tca-bug-repro
I have created the above sample repository, where I have tried to distill this down.
If you run this app (here's a screenrecording https://github.com/hanneskaeufler/tca-bug-repro/blob/main/bug.mp4) you will see that the ChildStateView doesn`t pop back, as it should (and does in the second part of the video).

You can comment/uncomment here in order to see the working and non-working states.
https://github.com/hanneskaeufler/tca-bug-repro/blob/main/popBugRepro/ContentView.swift#L75

**Expected behavior**
View controller is popped when `isActive` binding is set to false

**Screenshots**
https://github.com/hanneskaeufler/tca-bug-repro/blob/main/bug.mp4
**Environment**
 - Xcode [Version 12.2 beta 4 (12B5044c), but same in app store release version]
 - Swift [e.g. 5.2.2]
 - OS (if applicable): [e.g. iOS 14.2]

**Comment by hanneskaeufler** [comment]
Caveat: I realize this might just as well be a SwiftUI bug or something unrelated to TCA, but my "production" app is using TCA so I guess it might also be related. Any help would be appreciated!

**Comment by AlexisQapa** [comment]
I didn't look at your project but I had the same issue. I definitely think this is a bug into SwiftUI. Here is what I use to fix this when used with TCA:
`extension ViewStore {
	public func navigation(
		get: @escaping (State) -> Bool,
		action: Action
	) -> Binding<Bool> {
		var previous: Bool? = nil
		return .init(
			get: { get(self.state) },
			set: { newValue, transaction in
				guard newValue != previous else { return }
				previous = newValue
				guard !newValue else { return }
				withAnimation(transaction.disablesAnimations ? nil : transaction.animation) {
					self.send(action)
				}
			}
		)
	}

	public func navigation<S>(
		get: @escaping (State) -> S?,
		action: Action
	) -> Binding<Bool> {
		var previous: Bool? = nil
		return .init(
			get: { get(self.state) != nil },
			set: { newValue, transaction in
				guard newValue != previous else { return }
				previous = newValue
				guard !newValue else { return }
				withAnimation(transaction.disablesAnimations ? nil : transaction.animation) {
					self.send(action)
				}
			}
		)
	}
}
`
It basically skip back event that weren't supposed to fire.

**Comment by stephencelis** [comment]
@hanneskaeufler I'm going to close this since it's a SwiftUI bug. If you filed a feedback please do share the number here!
