### ISSUE TITLE
.debug() with only changed properties

### ISSUE THREAD

**Issue by LukasHromadnik** [pointfreeco/swift-composable-architecture#324]
Since it's very easy for the state to get really big in the app I would like to get only the changed keys in the log for clarity.

Is there some possibility to get only changed properties of the state with `.debug()`?

**Comment by stephencelis** [comment]
This is something we've thought about a lot but just haven't gotten to yet. In [swift-snapshot-testing](https://github.com/pointfreeco/swift-snapshot-testing) we collapse these diffs, and we'd like to do the same here in the future!

**Comment by andreyz** [comment]
This probably can be closed as recent release 0.25.0 addresses that with [CustomDump](https://www.pointfree.co/blog/posts/62-open-sourcing-custom-dump).

**Comment by stephencelis** [comment]
Ah yup! Good catch @andreyz :smile:
