### ISSUE TITLE
Swift Testing - Tests should fail with TestStore but aren't failing

### ISSUE THREAD

**Issue by omarzl** [pointfreeco/swift-composable-architecture#3241]
### Description

Running tests with TestStore using Swift Testing aren't failing.

Tested with latest `main` commit `a792049`

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

I am learning about the architecture using the tutorial:
https://pointfreeco.github.io/swift-composable-architecture/main/tutorials/meetcomposablearchitecture/

I took the opportunity to try writing the tests with Swift Testing in Xcode 16, but a failing test is not failing.

Code:
```
struct DemoTests {
    @Test func example() async {
        let store = TestStore(initialState: CounterFeature.State()) {
             CounterFeature()
           }
        await store.send(.incrementButtonTapped) {
           $0.count = 0
         }
         await store.send(.decrementButtonTapped) {
           $0.count = 0
         }
    }
}

@MainActor
final class CounterFeatureTests: XCTestCase {
  func testCounter() async {
        let store = TestStore(initialState: CounterFeature.State()) {
            CounterFeature()
        }
        await store.send(.incrementButtonTapped) {
            $0.count = 0
        }
        await store.send(.decrementButtonTapped) {
            $0.count = 0
        }
    }
    
}
```
Output:
<img width="1174" alt="image" src="https://github.com/user-attachments/assets/5a378972-7499-434f-8404-5122f9662093">

Expected behaviour: Both tests should fail

### Actual behavior

The test using Swift Testing is not failing

### The Composable Architecture version information

a792049

### Destination operating system

iOS 18

### Xcode version information

Version 16.0 beta 3 (16A5202i)

### Swift Compiler version information

```shell
swift-driver version: 1.111.2 Apple Swift version 6.0 (swiftlang-6.0.0.5.15 clang-1600.0.22.6)

Target: arm64-apple-macosx15.0
```

**Comment by Matejkob** [comment]
I believe running tests in `swift-testing` land is not supported yet. This PR adds support to it: #3229

**Comment by omarzl** [comment]
Oh great! I only looked at the issues, forgot the prs 😅

**Comment by mbrandonw** [comment]
Yep that's right, it's hopefully coming soon. There have been multiple complications and set backs while trying to support swift-testing in our libraries and so it has taken a little longer than we hoped. But we are still working on it. 🙂
