### ISSUE TITLE
Setter for 'subscript(dynamicMember:)' is unavailable

### ISSUE THREAD

**Issue by omarzl** [pointfreeco/swift-composable-architecture#3246]
### Description

Error presented when writing a line in a test:
`$0.destination?.addContact?.contact.name = "Blob Jr."`
after following the tutorial https://pointfreeco.github.io/swift-composable-architecture/main/tutorials/composablearchitecture/02-03-testingpresentation

Reproduced using Xcode 16 Beta 2 / Swift 6

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

That the code compiles

### Actual behavior

This code isn't compiling:
```
await store.send(\.destination.addContact.setName, "Blob Jr.") {
      $0.destination?.addContact?.contact.name = "Blob Jr."
}
```

Showing this error:
```
Setter for 'subscript(dynamicMember:)' is unavailable: Write 'enum = .case(value)', not 'enum.case = value'
```

### The Composable Architecture version information

54eb417

### Destination operating system

iOS 18

### Xcode version information

Version 16.0 beta 2 (16A5171r)

### Swift Compiler version information

```shell
swift-driver version: 1.110 Apple Swift version 6.0 (swiftlang-6.0.0.4.52 clang-1600.0.21.1.3)
Target: arm64-apple-macosx15.0
```

**Comment by jshier** [comment]
Yes, the subscript was always a bit of a hack, so they disabled in Swift 6 and now you should use `.modify`.

**Comment by omarzl** [comment]
Got it!
I changed to:
```
await store.send(\.destination.addContact.setName, "Blob Jr.") {
  $0.destination?.modify(\.addContact) { $0.contact.name = "Blob Jr." }
}
```
And added support in the enum to `CasePathable`:
```
extension ContactsFeature {
  @CasePathable
  @Reducer(state: .equatable)
  enum Destination {
    case addContact(AddContactFeature)
    case alert(AlertState<ContactsFeature.Action.Alert>)
  }
}
```

Thanks!

**Comment by m430** [comment]
Please update the documents.
