### ISSUE TITLE
Crash when writing to user defaults in background thread

### ISSUE THREAD

**Issue by lukeredpath** [pointfreeco/swift-composable-architecture#3247]
### Description

After updating a feature to use `@Shared` with the `.appStorage` persistence key, our app has started crashing when entering the background.

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

View updates are triggered on the main actor and the app does not crash.

### Actual behavior

The app crashes when user defaults are updated from a background thread.

### Steps to reproduce

I have traced this back to a custom view property wrapper that implements `DynamicProperty` - its `update()` method is marked as `nonisolated` to fix a concurrency warning but uses `MainActor.assumeIsolated` in this function because this should only be called on the main actor as part of a view update, however because the view is updating on a background thread it crashes.

The background view update is being triggered by a third party SDK that writes to the user defaults when the app enters the background. This in turns triggers the `NotificationCenter` observer in the app storage property key on the same background thread, which calls `didSet`.

<img width="661" alt="Screenshot 2024-07-18 at 00 05 34" src="https://github.com/user-attachments/assets/931ff97d-4f8c-4b0b-9406-b1a8ab6701c3">

I updated TCA to point to main as I thought #3206 would fix this issue however the final fix in that PR did not make the entire `willSet` isolated to the main actor, only the part the updates the current value but as you can see from the backtrace above, the view update is triggered before that (or possibly, IIRC the `update()` function on a `DynamicProperty` is called _before_ the view is about to be recomputed which might be why its crashing when calling `willSet` on the registrar).

I think the entire `didSet` closure needs to be called on the main actor, so `mainActorASAP` should wrap the entire closure contents.

Alternatively (or additionally), would it make more sense to ensure that all notifications are received on the main queue in the first place by passing `.main` to the queue when calling `NotificationCenter.default.addObserver`?

### The Composable Architecture version information

54eb417336fa849270671b8d2b73180835f9975a

### Destination operating system

iOS 17

### Xcode version information

Xcode 15.3

### Swift Compiler version information

```shell
swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0
```

**Comment by lukeredpath** [comment]
This fix worked for me locally: https://github.com/pointfreeco/swift-composable-architecture/compare/main...lukeredpath:swift-composable-architecture:lukeredpath/will-set-crash

**Comment by larryonoff** [comment]
The same issue for me. See screens with the details below.

The problem occurs for `AppStoreKey` when someone updates `UserDefaults` from the thread other than main, so that `_$perceptionRegistrar` is called from the thread other than main.

```swift
          self._$perceptionRegistrar.willSet(self, keyPath: \.value)
          defer { self._$perceptionRegistrar.didSet(self, keyPath: \.value) }
```

<img width="946" alt="Screenshot 2024-08-08 at 12 56 16" src="https://github.com/user-attachments/assets/40fd12ff-c52e-4e97-84ab-09c0a42c0773">
<img width="1169" alt="Screenshot 2024-08-08 at 12 56 35" src="https://github.com/user-attachments/assets/aea874db-8f1b-43d3-a09f-14bb306d0d93">
<img width="1190" alt="Screenshot 2024-08-08 at 12 56 43" src="https://github.com/user-attachments/assets/22907c2f-b9b6-4e23-9396-17803f639c59">

**Comment by stephencelis** [comment]
@lukeredpath With the `mainActorASAP`, is the `.main` queue necessary? I would think we would only need the former.

Also we're definitely down to take a PR for this! Any chance you have time to do so and maybe add a quick test that would have failed before the fix?

**Comment by lukeredpath** [comment]
Yes I will see what I can do. I think only one fix is necessary but I'm not sure which is best.

**Comment by stephencelis** [comment]
I think `mainActorASAP` will avoid a thread hop if already on the main thread, so maybe just that one?

**Comment by larryonoff** [comment]
@lukeredpath Will you be able to proceed with the fix? I can take it, if - not. We still have crashes in production, so It would be great to include the fix in upcoming TCA 1.13.0.

**Comment by larryonoff** [comment]
I decided not to wait and created [PR](https://github.com/pointfreeco/swift-composable-architecture/pull/3285). @stephencelis could you please include the fix in upcoming release.

**Comment by larryonoff** [comment]
@lukeredpath Hope the issue has finally been resolved. It has been in production since we began using Shared.

**Comment by zachwaugh** [comment]
I'm still seeing a crash here in 1.13.1. I'm not seeing anything obvious as a cause but the one thing that did stick out was this was during a fresh install of the app, so I think it's related to the case when the user default doesn't have an existing value.

<img width="1635" alt="Screenshot 2024-08-25 at 2 06 39 PM" src="https://github.com/user-attachments/assets/a508b854-5b7a-4a1c-b3e7-a1d7b012e523">

**Comment by stephencelis** [comment]
@zachwaugh This looks like it's a different issue than the one folks were encountering here. Can you share a repro and more information in a new issue/discussion? For example, it looks like SwiftUI is invoking a precondition in the attribute graph, so I would hope there'd be helpful info printed to the console. Can you report back if so?
