### ISSUE TITLE
ViewStore binding breaks explicit animations from external contexts

### ISSUE THREAD

**Issue by mrackwitz** [pointfreeco/swift-composable-architecture#325]
**Describe the bug**
ViewStore's binding method uses the Binding initializer which receives a value and a transaction. The transaction is used to make an explicit animation via `withAnimation`. This works when the binding is animated via `Binding.animation`, but it breaks when a binding is written to from an external animated context (via `withAnimation`).

**To Reproduce**

```swift
struct MyState {
  var offset: CGFloat
}

enum MyAction {
  case setOffset(CGFloat)
}

struct LoremView: View {
  var store: Store<MyState, MyAction>

  var body: some View {
     WithViewStore(store) { viewStore in
        IpsumView(
          offset: viewStore.binding(state: { $0.offset }, action: { .setOffset($0) })
            //.animation(.spring())   // Variant A
        )
     }
  }
}

struct IpsumView: View {
  @Binding offset: CGFloat = 0

  var body: some View {
    Circle().fill(Color.red)
      .frame(width: 30, height: 30)
      .offset(x: offset, y: 0)
      .onAppear {
        withAnimation(.easeInOut) {
          offset = 10
        }
     }
   }
}
```

**Expected behavior**

I would expect an animation to take place, but it's not taking place. The view changes without animation.

https://github.com/pointfreeco/swift-composable-architecture/blob/c1f88bd8608e8a26fd61ab46c9f11a63b0f4023d/Sources/ComposableArchitecture/ViewStore.swift#L128-L130

An alternative definition like below would not break, but might expose otherwise different behavior and would be a semantic breaking change:

```swift
extension ViewStore {
  public func externallyAnimatedBinding<LocalState>(
    get: @escaping (State) -> LocalState,
    send localStateToViewAction: @escaping (LocalState) -> Action
  ) -> Binding<LocalState> {
    Binding(
      get: { get(self.state) },
      set: { newLocalState in
          self.send(localStateToViewAction(newLocalState))
      })
  }
}
```

Interestingly if I add the line marked as "Variant A" from my code sample, an animation DOES take place - the animation as defined in the outer context. This behavior is exposed for both variants, via `.binding` or `.externallyAnimatedBinding`.
The latter tho does not animate, if the binding is not written in an explicitly wrapped call to `withAnimation`.
It's not clear to me from the rather spare SwiftUI documentation how bindings are supposed to behave.

**Environment**
 - Xcode: 12.1
 - Swift: 5.2.4
 - OS: iOS 13.7

**Comment by stephencelis** [comment]
@mrackwitz I was able to get slightly better behavior with this change:

https://github.com/pointfreeco/swift-composable-architecture/compare/fix-binding-animations

I think this fixes your bug in that `withAnimation` will be performed, but there is something puzzling about it. If you pass a `viewStore.binding(...).animation()` to your view, this animation will take precedence over any animation you pass to the `withAnimation` block. This seems to be the opposite behavior of `@State`-derived bindings, which, even when chained with `.animation()`, will lose this animation in the `withAnimation` block and instead prefer the explicit value passed to `withAnimation`.

Does anyone know if it's possible to grab the "current transaction" at any given time in SwiftUI? If we could do this, I think we could fix this bug _and_ behave in a manner consistent with the constructs SwiftUI ships with.

**Comment by mrackwitz** [comment]
Oh, awesome! Thanks @stephencelis for looking into this!

I've observed behavior consistent with what you describe when it came to animations, but I would have not been able to tell how it's working under which conditions so clearly yet. So the top comment of your PR is super helpful. I would suggest that this could be part of the API documentation for `ViewStore.binding`, even if it's out of scope of TCA.

**Comment by stephencelis** [comment]
For posterity, feedback filed that documents the SwiftUI bug: https://gist.github.com/stephencelis/fddee6ef2420a525e23fe9c07cbcaefb
