### ISSUE TITLE
on Xcode beta 16.1 swift-dependencies will error out due to recent deprecation 

### ISSUE THREAD

**Issue by ckse93** [pointfreeco/swift-composable-architecture#3284]
### Description

`WithDependencies` file errors out due to `@_unsafeInheritExecutor`. error message is `@_unsafeInheritExecutor attribute is deprecated; consider an 'isolated' parameter defaulted to '#isolation' instead`

<img width="904" alt="Screenshot 2024-08-13 at 7 13 00 PM" src="https://github.com/user-attachments/assets/795eec0e-edf4-4492-be72-bfd345646341">

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Steps to reproduce

download latest Xcode beta 16.1. 
run any existing project with `swift-dependencies 1.3.4` as one of the swift packages

### The Composable Architecture version information

swift-dependencies 1.3.4

### Destination operating system

visionOS 2.0

### Xcode version information

Version 16.1 beta (16B5001e)

### Swift Compiler version information

```shell
Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-darwin24.0.0
```

**Comment by stephencelis** [comment]
@ckse93 This was fixed in swift-dependencies a couple weeks ago: https://github.com/pointfreeco/swift-dependencies/releases/tag/1.3.6

TCA does not restrict you from updating, so be sure to bump your dependencies manually to get things to work.
