### ISSUE TITLE
Undefined symbols for architecture x86_64:  "nominal type descriptor for ComposableArchitecture.TestStore"

### ISSUE THREAD

**Issue by ferologics** [pointfreeco/swift-composable-architecture#330]
**Describe the bug**
When I try to run the project test target it wails to compile for x86_64 architecture.

**To Reproduce**
1. Download [Composable_x86_64.zip](https://github.com/pointfreeco/swift-composable-architecture/files/5658683/Composable_x86_64.zip) project
2. Open `Xcode12.xcodeproj`
3. Select the `Xcode12UITests` scheme
4. Select iPhone simulator as active device destination
5. Run `Xcode12UITests` tests (`cmd + u`)

```swift
import ComposableArchitecture
import XCTest

@testable import Xcode12UI

final class Xcode12UITests: XCTestCase {
    func test_example() {
        let store = TestStore(
            initialState: TestState(),
            reducer: testReducer,
            environment: TestEnvironment()
        )

        XCTAssertEqual("Xcode12UI", "Xcode12UI")
    }
}
```

**Expected behavior**
Tests would run successfully.

**Screenshots**
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/5576161/101473763-86641080-394a-11eb-8424-e8383a8e5635.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/5576161/101473758-849a4d00-394a-11eb-8979-1e478b38748c.png">

**Xcode log**
```llvm
Undefined symbols for architecture x86_64:
  "nominal type descriptor for ComposableArchitecture.TestStore", referenced from:
      _symbolic _____y_____AB_____AC_____G 22ComposableArchitecture9TestStoreC 9Xcode12UI0C5StateV AD0C6ActionO AD0C11EnvironmentV in Xcode12UITests.o
  "(extension in ComposableArchitecture):ComposableArchitecture.TestStore< where A == B, C == D>.init(initialState: A, reducer: ComposableArchitecture.Reducer<A, C, E>, environment: E) -> ComposableArchitecture.TestStore<A, A, C, C, E>", referenced from:
      Xcode12UITests.Xcode12UITests.test_example() -> () in Xcode12UITests.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Environment**
 - Xcode `12.3 beta (12C5020f)`
 - Swift Apple Swift version 5.3.2 (swiftlang-1200.0.44.1 clang-1200.0.32.28) Target: x86_64-apple-darwin20.2.0
 - OS (if applicable): iOS 13

**Additional context**
I am using Tuist to generate the Xcode project framework targets.
The trick to avoiding importing a static library multiple times is to have one framework target called `Dependencies` that aggregates all packages, frameworks, etc.

**Comment by ferologics** [comment]
I solved the issue by adding the missing `Dependencies` dependency for the test target.

**Comment by soo941226** [comment]
I've searched the same error description and reached this page. This issue is closed, but I want to share my solution.

I think upper solution is not a radical solution. The problem is the "target" like iOS target, macOS target, etc. What It means to be is the "Unit-test target" can't be built for any arm device.
I think you who search this error description might have changed the target from some iOS target or macOS target to Unit-test target. So, just reverse it. and it will be work.

![무제](https://user-images.githubusercontent.com/83933153/169310679-48a8ed17-a197-4cac-b2a1-079ca52956e9.jpg)
