### ISSUE TITLE
Stack navigation no longer working after migrating to new observation tools (v1.4.0 -> v1.13.0)

### ISSUE THREAD

**Issue by tw0po1nt** [pointfreeco/swift-composable-architecture#3302]
### Description

I migrated an application from TCA 1.4 to 1.13.0. I followed each of the migration guides and have gotten the project building and fixed *most* of the warnings I want to deal with right now. I was also able to set the min iOS version to iOS 17, so I don't need to use the backport of the observation tools. The root navigation of the app is a stack, like so:

```
@Reducer
public struct AppReducer {
    @ObservableState
    public struct State {
        @Presents public var alert: AlertState<Action.Alert>?
        public var path = StackState<Path.State>()
        public var splash = Splash.State()
        // Details elided
    }

    public enum Action {
        case alert(PresentationAction<Alert>)
        case path(StackActionOf<Path>)
        case splash(Splash.Action)
        case initializeSDKSuccess(shouldResetStack: Bool)

        // Details elided

        public enum Alert: Equatable {}
    }

    @Reducer(state: .equatable, action: .equatable)
    public enum Path {
        case about(About)
        case home(Home)
        case welcome(Welcome)
        // Details elided
    }

    public var body: ReducerOf<Self> {
        Scope(state: \.splash, action: \.splash) {
            Splash()
        }

        Reduce { state, action in
            case let .initializeSDKSuccess(shouldResetStack: shouldResetStack):
                if shouldResetStack {
                    state.path = StackState([.home(.init())])
                }
                return .none
            // Details elided
        }
        .ifLet(\.$alert, action: \.alert)
        .forEach(\.path, action: \.path)

        // Other delegate reducers, etc
    }
}
```

The view setup is:
```
public struct AppView: View {
    @Bindable var store: StoreOf<AppReducer>

    public var body: some View {
        NavigationStack(
            path: $store.scope(
                state: \.path,
                action: \.path
            )
        ) {
            SplashView(
                store: store.scope(
                    state: \.splash,
                    action: \.splash
                )
            )
        } destination: { store in
            switch store.case {
                case let .about(store):
                    AboutView(store: store)
                        .toolbarColorScheme(.dark, for: .navigationBar)
                case let .home(store):
                    HomeView(store: store)
                        .navigationTitle("")
                        .toolbar(.hidden, for: .navigationBar)
                case let .welcome(store):
                    WelcomeView(store: store)
                        .navigationTitle("")
                        .toolbar(.hidden, for: .navigationBar)
                // Other views
            }
        }
        .tint(.white)
        .alert(
            $store.scope(
                state: \.alert,
                action: \.alert
            )
        )
    }
}
```

The problem is that the app never continues past the splash screen. I've set a breakpoint in the reducer handler for `initializeSDKSuccess` and it runs, and the stackState gets set, but the navigation never happens. I'm not sure if I missed something in the migration guide or the documentation, but I've read both multiple times and have made sure I set it up properly. Hoping I'm just missing something silly.

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

When setting the path to a new stack state, I expect the UI to push a new view onto the stack

### Actual behavior

No view is pushed to the stack and the app just hangs on the root view of the stack.

### Steps to reproduce

1. Pull the code from [here](https://github.com/nighthawk-apps/nighthawk-ios-wallet/tree/feature/tca-upgrade)
2. Run the app in Xcode
3. See described result

### The Composable Architecture version information

1.13.0

### Destination operating system

iOS 17 and iOS 18

### Xcode version information

15.4

### Swift Compiler version information

```shell
Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-darwin23.6.0
```

**Comment by tw0po1nt** [comment]
Of course immediately after opening this issue, I realize this seems like it is a threading issue, not an issue with my TCA setup, so I am closing until I confirm. If someone sees an obvious issue, please let me know 😅

**Comment by tw0po1nt** [comment]
Threading issue was a red herring. I'm pretty sure it's something with the new observation tools, but I'm not sure what.

**Comment by tw0po1nt** [comment]
CPU is running over 100%, main thread completely choked out.

![Screenshot 2024-08-24 at 4 17 51 PM](https://github.com/user-attachments/assets/3e08b3f3-a573-4ac6-b449-4cbc77a045f3)

**Comment by mbrandonw** [comment]
Hi @tw0po1nt, it’s hard to say with the information provided. It could be any number of things. Can you try reproducing the problem in a small project that you can share?

**Comment by tw0po1nt** [comment]
Getting a repro in a simpler app might be tough. I am honing in on a specific view, so I may have a more precise area of the code to share here shortly. Thanks for the quick response!

**Comment by tw0po1nt** [comment]
@mbrandonw Just as a follow up, I seem to have pinpointed the issue. It had to do with the fact that we were using an older approach to shared state pre `@Shared` property wrapper. Like this:

```swift
var wallet: Wallet.State {
        get {
            var state = walletState
            // Copy over shared fields...
            return state
        }
        
        set {
            self.walletState = newValue
            // Copy over shared fields...
            self.walletEvents = newValue.walletEvents
        }
    }
```

This apparently was not playing nicely with the observation framework, and was resulting in a loop that locked up the main thread.
