### ISSUE TITLE
'Missing Package Product ComposableCoreLocation' after updating to 0.9

### ISSUE THREAD

**Issue by natecraft1** [pointfreeco/swift-composable-architecture#331]
**Describe the bug**
Unable to build with errors 'Missing Package Product ComposableCoreLocation' and 'Missing Package Product ComposableCoreMotion' after updating to 0.9. 

**To Reproduce**
- Updated to 0.9 from 0.8 via SPM
- Tested on Xcode 12.2 and 12.3.
- Tried cleaning build folder, deleting derived data, and resetting package caches

**Comment by RabugenTom** [comment]
Both were extracted as separate packages in [v0.9](https://github.com/pointfreeco/swift-composable-architecture/releases/tag/0.9.0):
https://github.com/pointfreeco/composable-core-location
https://github.com/pointfreeco/composable-core-motion
