### ISSUE TITLE
Crash on background queue `.publisher` effect subscription

### ISSUE THREAD

**Issue by ivopintodasilva** [pointfreeco/swift-composable-architecture#3400]
### Description

A crash is happening in the `CurrentValueRelay.request` function when I have a `.publisher` effect that is subscribed to on a background queue:

```
    var recordingsEffect: Effect<Action> {
        .publisher {
            recordingsService.recordings
                .removeDuplicates()
                .subscribe(on: backgroundQueue)
                .map { _ in
                    // ...
                    [:]
                }
                .receive(on: mainQueue)
                .map(Action.recordingsUpdated)
        }
    }
```

If I remove/comment the `backgroundQueue` subscription, this crash no longer happens.

⚠️ Also worth noting that it only started occurring in **Xcode 16 and TCA v1.15.0** ⚠️ 
- In TCA **v1.15.0** and Xcode **15**, works perfectly ✅ 
- In TCA **v1.14.0** and Xcode **16**, works perfectly ✅ 

I also tried to isolate the issue in a sample project by simply having a `.publisher` effect that does some work in a background queue but there the crash was not reproducible either...

Will keep investigating and provide a barebones sample project with the crash replication as soon as i can.

Also worth sharing that the `recordingsService.recordings` is a TCA store publisher (`store.publisher.recordings.eraseToAnyPublisher()`).

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [x] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

The effect's inner publisher does some work in the background queue and sends an action back to the reducer (in the main queue) without crashing.

### Actual behavior

![image](https://github.com/user-attachments/assets/5a3bfc80-b3fe-4196-a108-48c49ca5e72f)

Here's a [stacktrace](https://github.com/user-attachments/files/17056049/Error.Stacktrace.iOS.txt) that i recovered from our crash reporter.

### Reproducing project

Will append one as soon as I'm able to reproduce the issue in an isolated project.

### The Composable Architecture version information

1.15.0

### Destination operating system

iOS 18

### Xcode version information

Xcode 16.0

### Swift Compiler version information

```shell
swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
Target: arm64-apple-macosx15.0
```

**Comment by ivopintodasilva** [comment]
After going through the commits in the v1.15.0 release, I was able to pin the issue down to commit 7c6fb2670019d61e9040fab448dfce885b56c7fd

```
        // doesn't crash
        .package(
            url: "https://github.com/pointfreeco/swift-composable-architecture",
            revision: "83ed1230412aa30cd84cbe1b5b8a4f298bce23aa"
        ),

        // crashes
        .package(
            url: "https://github.com/pointfreeco/swift-composable-architecture",
            revision: "7c6fb2670019d61e9040fab448dfce885b56c7fd"
        ),
```

**Comment by mbrandonw** [comment]
Hi @ivopintodasilva, thank you very much for investigating this and providing so much information. The stack trace you provided seems quite similar to the problem described [here](https://github.com/swiftlang/swift/issues/75453) in which an isolation invariant is broken. Would you have time to cook up a repro for us to investigate more deeply?

**Comment by stephencelis** [comment]
@ivopintodasilva I'm going to close this for now till we have a repro we can address, but please ping us and we can reopen when you share one! I'm also happy to convert this to a discussion if it turns out to not be a library bug.

**Comment by dk-jlew** [comment]
@stephencelis 
I have a contrived but simple repo of this on 1.22.0.  Essentially, if you try and adapt a store's publisher to an async stream, this crash happens:
```
.task {
            let store = Store(initialState: MyReducer.State()) {
                MyReducer()
            }
            store.send(.initialize)
            _ = await store
                .publisher
                .values
                .first { $0.count > 3 }            
        }
```
We have some unit tests that are doing things like this.  
[TCAApp.zip](https://github.com/user-attachments/files/22045135/TCAApp.zip)

**Comment by dk-jlew** [comment]
We have some unit tests which are doing this.  If you use an extension like this which forces it back onto mainactor, the crash goes away:
```
public extension Publisher where Failure == Never{    
    func asyncFirst() async -> Output {
        await withCheckedContinuation(isolation: MainActor.shared) { continuation in
            var cancellable: AnyCancellable?
            cancellable = first()
                .sink(
                    receiveCompletion: { result in
                        switch result {
                        case .finished:
                            break
                        case let .failure(error):
                            continuation.resume(throwing: error)
                        }
                        cancellable?.cancel()
                        cancellable = nil
                    },
                    receiveValue: { value in
                        continuation.resume(with: .success(value))
                    }
                )
        }
    }
}
```

**Comment by mbrandonw** [comment]
We chatted about this over Slack, but the problem here is mixing publishers and async streams. The publisher vended by the `Store` knows that values are only ever emitted on the main thread, and uses that information in order to access state in the store. Once you do `publisher.values`, that loses the isolation and suddenly values are being requested from background threads.

In general it is just not safe to use the `values` async sequence on a publisher that does extra work to control its threading.

We will discuss possible solutions soon.
