### ISSUE TITLE
Apple Silicon Simulator Support

### ISSUE THREAD

**Issue by nikitaame** [pointfreeco/swift-composable-architecture#344]
**Describe the bug**
I'm able to run a project to device but seeing the following when trying to run to simulator using an Apple Silicon Macbook:
`Could not find module 'ComposableArchitecture' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator`

**To Reproduce**
Run any project with ComposableArchitecture on Apple Silicon.

**Environment**
 - Xcode 12.3
 - Swift 5.3.2
 - OS (if applicable): macOS 11.1

**Additional context**
Seems like this is just a build configuration setting. Saw a [similar issue for RxSwift ](https://github.com/ReactiveX/RxSwift/issues/2261) that had a [straightforward](https://github.com/ReactiveX/RxSwift/pull/2262/files) resolution.

**Comment by nikitaame** [comment]
Going to go ahead and close this issue out. I was able to run some of the sample projects just fine to simulator. 

Think this is something wrong with the project setup or dev environment on my end. Have no idea what it is after trying a handful of different tricks.

Stumped because the compiler warning is telling me that it can't find the module for Intel chipset simulator but can find it for Apple chipset device or simulator. Which is exactly what I want. If anyone has any recommendations, please advise!

**Comment by EmDee** [comment]
@nikitaame Have you found a reason why your dev machine was behaving like that? I'm seeing the same compiler/linking error and don't know why it would even look for that on the M1.

**Comment by nikitaame** [comment]
@EmDee I figured out the behavior after talking to one an Apple engineer who works on CoreSimulater! Advice was:

> Typically what happens is the main target you're trying to build has ARCHS, SUPPORTED_ARCHS, or EXCLUDED_ARCHS overridden rather than set to the default value. That causes it to want to build as x86_64 which can cascade down the line. There is also currently an Xcode issue where SPM always does a "build active arch only" when the config is named Debug. So if other targets in your project disagree you can end up failing to build the slice you aren't even trying to run.
