### ISSUE TITLE
Edits to persisted shared state lost when bunched together

### ISSUE THREAD

**Issue by nshelleyfs** [pointfreeco/swift-composable-architecture#3477]
### Description

When doing multiple edits at a time, sometimes only the first edit is saved while remaining edits in the same block of code get lost.

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Reproducing project

[ComposableTest.zip](https://github.com/user-attachments/files/17620111/ComposableTest.zip)

### The Composable Architecture version information

1.15.2

### Destination operating system

iOS 18

### Xcode version information

Xcode 16.1

**Comment by mbrandonw** [comment]
Hi @nshelleyfs, thanks for the repro! I've just captured this in a failing test (#3479) and we will investigate a fix soon.
