### ISSUE TITLE
Warning in TicTacToe SwiftUI demo: cycle detected through attribute 132648

### ISSUE THREAD

**Issue by ivanmkc** [pointfreeco/swift-composable-architecture#363]
**Describe the bug**
These errors appear in the debug logs for the SwiftUI:

```
=== AttributeGraph: cycle detected through attribute 352280 ===
=== AttributeGraph: cycle detected through attribute 351784 ===
=== AttributeGraph: cycle detected through attribute 351784 ===
=== AttributeGraph: cycle detected through attribute 340792 ===
=== AttributeGraph: cycle detected through attribute 340792 ===
```

**To Reproduce**
1. Clone the repo. I used "commit 11f215c3b6923dfcccec6d1de6a672963a0d3c6e"
2. Open `TicTacToe.xcodeproj`
3. Run the demo
4. On Login screen, type in anything to `email` and `password` and tap `Log in` button.
5. Filter Xcode debug input for `cycle`

**Expected behavior**
No warning.

**Screenshots**
N/A

**Environment**
 - Xcode Version 12.3 (12C33)
 - Simulator: iPod touch (7th generation), which is what I tested. Shouldn't matter which simulator though.

**Comment by mbrandonw** [comment]
Hi @ivanmkc, thanks for the report.

This appears to be a SwiftUI bug :/ I was able to track it down to this one single line:

https://github.com/pointfreeco/swift-composable-architecture/blob/11f215c3b6923dfcccec6d1de6a672963a0d3c6e/Examples/TicTacToe/Sources/Views-SwiftUI/LoginSwiftView.swift#L83

Commenting that out avoids "cycle" logs. This line's purpose is to disable the enter login form while the login API request is in flight. It appears that messing with a `NavigationLink`'s enabled/disabled state is problematic.

I'm inclined to leave the code in as-is, and perhaps try create a minimal repro case to file with Apple. Let me know if you're able to get such a minimal example.

**Comment by mbrandonw** [comment]
I'm going to close this issue but let us know if you have any other questions.

**Comment by mywristbands** [comment]
I think this bug might have something to do with disabling the TextField before resigning it as first responder. I posted about this issue in this [stackoverflow article](https://stackoverflow.com/questions/69653554/get-attributegraph-cycle-detected-error-when-changing-disabled-state-of-text/69653555#69653555).
