### ISSUE TITLE
Inconsistent semantics of `IdentifiedArray`

### ISSUE THREAD

**Issue by vadimtrifonov** [pointfreeco/swift-composable-architecture#366]
**Describe the bug**
Mutation of `IdentifiedArray` reveals inconsistent semantics (in some cases it acts as `Array`, in other as `Dictionary`)

**To Reproduce**
These two tests show that it behaves as `Array`, allowing to insert a new record with the duplicate key. However, the internal dictionary becomes inconsistent.

```swift
func test1() {
    var array: IdentifiedArray = [User(id: 1, name: "Blob")]
    
    array.insert(User(id: 1, name: "Blob Jr."), at: 0)
    
    XCTAssertEqual(array, [User(id: 1, name: "Blob Jr."), User(id: 1, name: "Blob Jr.")])
    
    array[1] = User(id: 99, name: "Blob 99")
    
    XCTAssertEqual(Array(array), [User(id: 99, name: "Blob 99"), User(id: 99, name: "Blob 99")])
   
    // Fails due to internal inconsistency
    XCTAssertEqual(array, [User(id: 99, name: "Blob 99"), User(id: 99, name: "Blob 99")])
}

func test2() {
    var array: IdentifiedArray = [User(id: 1, name: "Blob")]
    
    array.insert(User(id: 1, name: "Blob Jr."), at: 0)
    array[id: 1] = User(id: 99, name: "Blob 99")
    
    XCTAssertEqual(Array(array), [User(id: 99, name: "Blob 99"), User(id: 99, name: "Blob 99")])
    
    // Fails due to internal inconsistency
    XCTAssertEqual(array, [User(id: 99, name: "Blob 99"), User(id: 99, name: "Blob 99")])
}
```

![345cb889-7bc3-4a11-b4ee-b35ba00d612b](https://user-images.githubusercontent.com/1075070/106405448-56d50e80-648a-11eb-8c56-eb3e281a6e80.png)

This test shows that the existing value is not updated when inserting a new value with the same key.

```swift
func test3() {
    var array: IdentifiedArray = [User(id: 1, name: "Blob 1"), User(id: 2, name: "Blob 2"), User(id: 3, name: "Blob 3")]
    
    array[2] = User(id: 1, name: "Blob 0001")
    
    XCTAssertEqual(Array(array), [User(id: 1, name: "Blob 1"), User(id: 2, name: "Blob 2"), User(id: 1, name: "Blob 0001")])
    XCTAssertEqual(array, [User(id: 1, name: "Blob 1"), User(id: 2, name: "Blob 2"), User(id: 1, name: "Blob 0001")])
}
```

This test shows that it behaves as `Dictionary` when removing a record with the duplicate key at a certain index.

```swift
func test4() {
    var array: IdentifiedArray = [User(id: 1, name: "Blob")]
    
    array.insert(User(id: 1, name: "Blob Jr."), at: 0)    
    array.remove(at: 0)
    
    XCTAssertEqual(Array(array), [])
    XCTAssertEqual(array, [])
}
```

**Expected behavior**
If `IdentifiedArray` is `Array` then it should allow duplicates and update the existing records when a new record with the same key is inserted. If `IdentifiedArray` is a variant of `OrderedDictionary` then it cannot conform to `MutableCollection` due to the following restriction:
> A value stored into a subscript of a MutableCollection instance must subsequently be accessible at that same position.

**Comment by stephencelis** [comment]
@vadimtrifonov Thanks for bringing this up!

> If `IdentifiedArray` is `Array` then it should allow duplicates and update the existing records when a new record with the same key is inserted. If `IdentifiedArray` is a variant of `OrderedDictionary` then it cannot conform to `MutableCollection` due to the following restriction:
> 
> > A value stored into a subscript of a MutableCollection instance must subsequently be accessible at that same position.

We introduced `IdentifiedArray` for the purpose of interfacing with SwiftUI's `ForEach` view, which renders a view for each identifiable element. But notably, if you pass 2 items with the same `id` but properties that otherwise would render differently, it will potentially render the same item twice, so we are already in the neighborhood of undefined behavior here.

Reassigning an element with the wrong identifier at a specific identifier should almost certainly be considered a programmer error, so we should probably add a precondition here. Let me know if you have a use case, though!

**Comment by vadimtrifonov** [comment]
@stephencelis Thanks for addressing the issue. However, #368 doesn't affect these tests that use index-based subscript (from `MutableCollection` protocol):

```swift
func test1() {
    var array: IdentifiedArray = [User(id: 1, name: "Blob")]
    
    array.insert(User(id: 1, name: "Blob Jr."), at: 0)
    
    XCTAssertEqual(array, [User(id: 1, name: "Blob Jr."), User(id: 1, name: "Blob Jr.")])
    
    array[1] = User(id: 99, name: "Blob 99")
    
    XCTAssertEqual(Array(array), [User(id: 99, name: "Blob 99"), User(id: 99, name: "Blob 99")])
   
    // Fails due to internal inconsistency
    XCTAssertEqual(array, [User(id: 99, name: "Blob 99"), User(id: 99, name: "Blob 99")])
}
```

```swift
func test3() {
    var array: IdentifiedArray = [User(id: 1, name: "Blob 1"), User(id: 2, name: "Blob 2"), User(id: 3, name: "Blob 3")]
    
    array[2] = User(id: 1, name: "Blob 0001")
    
    XCTAssertEqual(Array(array), [User(id: 1, name: "Blob 1"), User(id: 2, name: "Blob 2"), User(id: 1, name: "Blob 0001")])
    XCTAssertEqual(array, [User(id: 1, name: "Blob 1"), User(id: 2, name: "Blob 2"), User(id: 1, name: "Blob 0001")])
}
```

```swift
func test4() {
    var array: IdentifiedArray = [User(id: 1, name: "Blob")]
    
    array.insert(User(id: 1, name: "Blob Jr."), at: 0)    
    array.remove(at: 0)
    
    XCTAssertEqual(Array(array), [])
    XCTAssertEqual(array, [])
}
```

One way to address them is to assert that the key of a record being inserted is not present in the array already. However, as index-based subscript (`subscript(position: Int) -> Element`) definition comes from `MutableCollection` it can have unintended consequences, if some synthesized extension implementation will try to use it without being aware of such assertion.
