### ISSUE TITLE
Fails to build with Xcode 12.5 beta1

### ISSUE THREAD

**Issue by stinger** [pointfreeco/swift-composable-architecture#373]
`WithViewStore.swift` fails to build with the following message:

_Invalid redeclaration of synthesized implementation for protocol requirement 'Body'_

**Comment by stephencelis** [comment]
This should be fixed in [0.13.0](https://github.com/pointfreeco/swift-composable-architecture/releases/tag/0.13.0). Can you try with that release?

**Comment by stinger** [comment]
Ah, that's correct! I was using 0.11.0. Sorry for the noise :)
