### ISSUE TITLE
"Missing package product CasePaths" after update to 0.13.0

### ISSUE THREAD

**Issue by innoreq** [pointfreeco/swift-composable-architecture#375]
**Describe the bug**
After Xcode "Update to latest package versions", version 0.13.0 is shown, but build throws error "Package loading: Missing package product 'CasePaths', Package resolution errors must be fixed before building"

**Expected behavior**
Build should be possible.

**Screenshots**
<img width="464" alt="Bildschirmfoto 2021-02-02 um 08 52 11" src="https://user-images.githubusercontent.com/43679379/106568986-4da07c00-6534-11eb-8bcd-34813d1c4f27.png">

I**Environment**
 - Xcode 12.3 (12C33)
 - Swift 5
 - iOS Scheme Build

**Additional context**
Reset package cache does not fix the problem.
Removing the package completely and reinstalling it seems to help.

**Comment by stephencelis** [comment]
@innoreq We've noticed that Xcode's SPM integration can be a bit flaky, and sometimes you need to "update to latest versions" or "reset package cache" multiple times. These errors can also show up intermittently before a build but can go away after a successful build. If you have something that's reproducible, though, can you attach a project to this issue? I'm not able to reproduce this manually.

**Comment by stephencelis** [comment]
@innoreq We're still unable to repro this. Were you able to resolve things?

**Comment by innoreq** [comment]
I got it working, as I wrote under "Additional context" the full removal and reinstallation helped.

**Comment by stephencelis** [comment]
@innoreq Ah gotcha, this sounds like an Xcode bug then. Glad you got situated!
