### ISSUE TITLE
Unify Name: "ComposableArchitecture" vs "swift-composable-architecture"

### ISSUE THREAD

**Issue by innoreq** [pointfreeco/swift-composable-architecture#394]
**Describe the bug**
Currently, using Tuist and in some other situations, there are problems to build, as Xcode throws this error:

xcodebuild: error: Could not resolve package dependencies:
  declared name 'ComposableArchitecture' for package dependency 'https://github.com/pointfreeco/swift-composable-architecture' does not match the actual package name 'swift-composable-architecture'

To resolve this, an SPM .package declaration must use the "name:" argument, which is not available yet in Tuist. Therefore, the project cannot taken under Tuist control, if it uses TCA.

**Expected behavior**
To avoid this: why not give the package the name "ComposableArchitecture", instead of "swift-composable-architecture"?

**Comment by stephencelis** [comment]
@innoreq Thanks for taking the time to file this. We definitely find this aspect of package management to be confusing. We try to follow Apple's conventions here, though. Most of their open source libraries, like NIO, use `swift-\(package-name)` for the overall name, and `\(PackageName)` for any primary module: https://github.com/apple/swift-nio/blob/main/Package.swift#L85-L87

Were you able to get things working by adding `name:` to the dependency? If you're having issues, please paste in any `ComposableArchitecture`-related lines and we'll try to help you debug!

**Comment by stephencelis** [comment]
@innoreq I'm doing some spring cleaning, so going to close this out. If you'd like to continue the discussion, though, let me know! Any chance Tuist has this on their roadmap to fix? SPM requires explicit `name:` arguments as of package tools version 5.3.
