### ISSUE TITLE
Not sure if this a bug or a problem with how I've done things

### ISSUE THREAD

**Issue by grangej** [pointfreeco/swift-composable-architecture#398]
I am going around in circles and not sure if this is behaving the way it should be:

- I have a fairly complex app and some but lets simplify as the following:

[AppReducer]
[tab1Reducer, tab2Reducer , tab3Reducer, tab4Reducer]
[tab1Presented]
[tab1PresentedPresented]

On tab1PresentedPresented I have a search field that is to filter some results. the problem is that it seems to trigger a complete refresh of the entire app structure. All tabs are refreshed. This causes tab1PresentedPresented to be reconstructed and is dismissing the keyboard / causing crash when embedded in a NavigationView. 

The only state that was manipulated was tab1PresentedPresented, no other states were changed.

If I don't have tab1Presented combine tab1PresnetedPresented reducer the problem goes away but of course state for tab1PresentedPresented doesn't update since the reducer is not actually created / held onto. 

---

- Some other notes, tab4 also has a navigationLink to a similar search / filter view. This works without issue :( 
- I attempted to re-create this with native swiftui code (observableObject / stateObject) but was not able to reproduce the problem. The search works the updates still happen based on the search.

**Comment by siejkowski** [comment]
If possible, provide the source code (or at least a subset of it) so we could help with spotting the problem :)

Without the source code, my best guess is that if the entire app structure is recreated, the most probable explanation is that you're observing the whole app state everywhere.

In other words, you are using either `WithViewStore` or `@ObservedObject var viewStore` created from the whole `AppStore`. However, you most probably do not need to have all your app refreshed on any change.

You can control what views are refreshed by scoping the `AppStore` to only a subset of state and actions that the particular view needs. Then this view is refreshed only when the subset of state changes.

Please consult the https://github.com/pointfreeco/swift-composable-architecture/blob/main/Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Composition-TwoCounters.swift to see the basics of how to scope the app store to smaller stores so that the views are refreshed independently.

**Comment by grangej** [comment]
First, thank you for your response :D 

I will try to provide the relevant source here, and if needed perhaps offline?

I have included the views, all reducers are combined all the way up to the main app reducer (as I thought was expected?) All sub views are scoped I believe correctly. 

Main App 
```
....
    let appStore: Store<AppState, AppAction> = Store(initialState: AppState(), reducer: appReducer, environment: AppEnvironment.live)

    var body: some Scene {
        WindowGroup {
            WithViewStore(self.appStore) { viewStore in
                if viewStore.signInStatus.isSignedIn {
                    MainAppView(store: appStore).environmentObject(sheetManager)
                } else {
                    LandingView(store: appStore).environmentObject(sheetManager)
                }
            }
        }
    }
```

```
struct MainAppView: View {

    let store: Store<AppState, AppAction>

    var body: some View {
        WithViewStore(self.store) { viewStore in
            TabView {
                NavigationView {
                    CompetitionsListView(store: self.store.scope(state: { $0._competitionsListViewState }, action: AppAction.competitionsListAction))
                }.tabItem { Image(systemName: "house.fill") }
                NavigationView {
                    Tab2View(store: self.store.scope(
                        state: { $0._tab2State },
                        action: AppAction.tab2ViewAction
                      ))
                }.tabItem { Image(systemName: "arrow.clockwise") }
                NavigationView {
                    Text("Notifications")
                }.tabItem { Image(systemName: "bell.fill") }
                NavigationView {
                    IfLetStore(self.store.scope(state: { $0._profileState}, action: AppAction.profileAction), then: ProfileView.init(store:))
                }.tabItem { Image(systemName: "gearshape") }
            }.addPartialSheet()
        }
    }
}
````


````
/// CompetionListView
                   WithViewStore(store) { viewStore in ...
                    ....
                    case .create:
                        NavigationView {
                            IfLetStore(
                                self.store.scope( state: { $0.createCompetitionState}, action: CompetitionsListAction.createCompetitionAction ),
                                then: CreateCompetitionView.init(store:)
                            )
                        }.addPartialSheet(style: .minimalStyle()).environmentObject(partialSheetManager)
                    }
```

```
      /// CompetitionCreateView
               WithViewStore(store) { viewStore in ...
                case .inviteFriends:
                    NavigationView {
                        IfLetStore(self.store.scope(state: { $0.inviteFriendsState}, action: CreateCompetitionAction.inviteFriendsAction), then: InviteFriendsView.init(store:))
                    }
```

```
/// This is where the problem happens, when tapping a key in the search view it will cause everything to refresh even though only the InviteFriendsState is changed (no other state in the app is changed per the debug output.
struct InviteFriendsView: View {
    let store: Store<InviteFriendsState, InviteFriendsAction>

    public init(store: Store<InviteFriendsState, InviteFriendsAction>) {
        self.store = store
    }

    public var body: some View {
        WithViewStore(store) { viewStore in

            ScrollView {
                LazyVStack(alignment: /*@START_MENU_TOKEN@*/.center/*@END_MENU_TOKEN@*/, spacing: 20, pinnedViews:
                            [
                                .sectionHeaders
                            ],
                           content: {
                            Section(header: SearchView(text: viewStore.binding(get: { $0.searchText }, send: InviteFriendsAction.searchTextDidChange))) {
                                ForEachStore(self.store.scope(state: { $0.results },
                                                              action: InviteFriendsAction.friendItemAction(id:action:)),
                                             content: InviteFriendsItemView.init(store:))
                            }

                           }).padding()
            }.navigationBarItems(trailing:
                Button(action: {
                    viewStore.send(.savePressed)
                }, label: {
                    Text("Save")
                })
            )

            .navigationTitle(viewStore.title).onAppear(perform: {
                viewStore.send(.onAppear)
            })
        }
    }
}
```

**Comment by grangej** [comment]
To be clear , or perhaps I don't understand something , if AppState is not changed it should not cause a refresh of anything ? body of withViewStore should only be refreshed when the appropriate state for that view store is changed yes?

**Comment by mbrandonw** [comment]
As @siejkowski pointed out, this is an issue with observing more state than you actually need, and it's a problem that plagues vanilla SwiftUI applications as much as TCA applications.

Any time you use `WithViewStore` you are observing the entirety of the state that the store holds onto. You can use this as an opportunity to chisel away at the unneeded state and only leave behind what you actually use. For example, you first `WithViewStore` usage could be simplified to this:

```swift
            WithViewStore(self.appStore.scope(state: \.signInStatus)) { viewStore in
                if viewStore.isSignedIn {
                    MainAppView(store: appStore).environmentObject(sheetManager)
                } else {
                    LandingView(store: appStore).environmentObject(sheetManager)
                }
            }
```

That would guarantee that this view code is re-evaluated only when the `signInStatus` changes.

Further, the usage of `WithViewStore` in `InviteFriendsView` can also be simplified by introducing a `ViewState` that holds onto only the data needed for the view:

```swift
struct InviteFriendsView: View {
  ...
  struct ViewState: Equatable {
    let searchText: String
    let title: String
    init(state: InviteFriendsState) {
      self.searchText = state.searchText
      self.title = state.title
    }
  }

  public var body: some View {
    WithViewStore(store.scope(state: ViewState.init)) { viewStore in
    }
  }
}
```

This will prevent the view from being re-evaluated until either `searchText` or `title` mutate.

It's also worth mentioning that this problem definitely does affect vanilla SwiftUI views, including using `@ObservedObject` and `@StateObject`. Just paste the code below into a fresh project and see that the `ContentView`'s body property is recomputed after every little state mutation, even if it is just happening in a single tab:

```swift
class VM: ObservableObject {
  @Published var searchText: String = ""
  @Published var tabIndex = 0
}

struct ContentView: View {
  @ObservedObject var vm: VM

  var body: some View {
    let _ = print("ContentView")
    TabView.init(selection: self.$vm.tabIndex) {
      NavigationView {
        let _ = print("Tab 0")
        Tab0View(text: self.$vm.searchText)
      }
      .tabItem { Text("One") }
      .tag(0)

      NavigationView {
        let _ = print("Tab 1")
        Text("Tab 1")
      }
      .tabItem { Text("Two") }
      .tag(1)

      NavigationView {
        let _ = print("Tab 2")
        Text("Tab 2")
      }
      .tabItem { Text("Three") }
      .tag(2)
    }
  }
}

struct Tab0View: View {
  @Binding var text: String

  var body: some View {
    Form {
      Text("Tab 0")
      TextField("Test", text: self.$text)
    }
  }
}
```

**Comment by mbrandonw** [comment]
Also I’m going to transfer this issue to the discussions tab of the repo because I think it’ll be more appropriate there.
