### ISSUE TITLE
Unable to map local BindingAction to global BindingAction

### ISSUE THREAD

**Issue by lukeredpath** [pointfreeco/swift-composable-architecture#403]
### Describe the bug

I have encountered a problem trying to map some local, view-specific action to a more global feature-specific action.

For example, given the following feature state/action:

```swift
struct FeatureState: Equatable {
  var firstName: String = ""
  var lastName: String = ""
}

enum FeatureAction: Equatable {
  case binding(BindingAction<FeatureState>)
}
```

This feature has state and actions that aren't relevant to some views, so I want to use the pattern of creating some very local view state and action and scoping the feature store down to a more localised store:

```swift
struct SomeView: View {
  var body: some View { }
}

extension SomeView {
  struct State: Equatable {
    let firstName: String
    let lastName: String
  }

  enum Action: Equatable {
    case binding(Binding<State>)
  }
}
```

We should be able to scope a `Store<FeatureState, FeatureAction>` to `Store<SomeView.State, SomeView.Action>`:

```swift
let store = featureStore.scope(
  state: SomeView.State.init(fromFeatureState:),
  action: FeatureAction.init(fromViewAction:)
)
```

`SomeView.State.init(fromFeatureState:)` is not important here, but I want to focus on the mapping of `SomeView.Action` to `FeatureAction`:

```swift
extension FeatureAction {
    init(fromViewAction someViewAction: SomeView.Action) {
        switch someViewAction {
        case let .binding(.set(\. firstName, firstName)):
            self = .binding(.set(\. firstName, firstName))
        case let .binding(.set(\. lastName, lastName)):
            self = .binding(.set(\. lastName, lastName))
        }
    }
}
```

This does not compile - it fails with the error:

```
Pattern variable binding cannot appear in an expression
```

### Expected behavior

I would expect the above code to work however it does not, presumably because `BindingAction` is in fact a struct, not an enum, and `.set` is a static function on that struct.

To work around this, I've had to introduce non-binding actions in my `SomeView.Action`, e.g. `.firstNameChanged(String)` and `.lastNameChanged(String)` that I can pattern match over and map back to the appropriate binding action. I'm still getting some advantages from `BindingAction` because its still removing a lot of boilerplate from my feature action and reducer, but it feels like I'm having to add more boilerplate than necessary in my view.

In this case, how can I concisely map the local action to the global action?

**Comment by stephencelis** [comment]
Hey @lukeredpath! This is not documented super well right now, but `BindingAction` has a `pullback` method for just this: https://github.com/pointfreeco/swift-composable-architecture/blob/86d6e3551437a88ecd73a789753fd2151761b17d/Sources/ComposableArchitecture/SwiftUI/Binding.swift#L153-L167

This requires more working parts than typical view state, since you need a writable key path on the global state that can expose that view state. Something like:

```swift
extension FeatureState {
  var view: SomeView.State {
    get { .init(firstName: firstName, lastName: lastName) }
    set { (self.firstName, self.lastName) = (newValue.firstName, newValue.lastName)
  }
}
```

And `BindingAction` requires writable paths, too, so you'll want to change those `let`s to `var`s:

```swift
extension SomeView {
  struct State: Equatable {
    var firstName: String
    var lastName: String
  }
}
```

Then I think it's just a matter of invoking `pullback` in the `action` transformation of `scope`. We really should document this, and add an advanced case study, though!

**Comment by lukeredpath** [comment]
@stephencelis thanks for the super-fast response! I totally missed the `.pullback` function. Its a shame that this requires a `WriteableKeyPath` given that this should just be a read-only projection of the feature state. I'll give it a try tomorrow and see how it compares to using explicit view actions.

**Comment by stephencelis** [comment]
@lukeredpath Here's a quick look at what it takes to update the TicTacToe example's login form (which uses view state) to use `BindingAction`: https://github.com/pointfreeco/swift-composable-architecture/commit/be132a0b65596b886c9fccad8e29edd3291278fd

Pullback is used to transform the action domain here: https://github.com/pointfreeco/swift-composable-architecture/commit/be132a0b65596b886c9fccad8e29edd3291278fd#diff-e932f7e8d2a38a3a35197f8e8c88a51068cb543524d33be266107288e8ce9107R119

**Comment by stephencelis** [comment]
@lukeredpath I'm doing some spring cleaning and noticed this was still open. Any chance we can close it out? Or did you encounter any issues?

**Comment by lukeredpath** [comment]
@stephencelis thanks for the reminder. Happy to close it, we got it all figured out and I'm now a binding pullback expert. 🤣
