### ISSUE TITLE
Password in TicTacToe seems to be "password" rather than "PASSWORD"

### ISSUE THREAD

**Issue by khirsh** [pointfreeco/swift-composable-architecture#406]
**Describe the bug**
Testing the TicTacToe example, it seems to me that the password is "password" rather than "PASSWORD"?

**To Reproduce**
Try to Login to the TicTacToe example.  Note that the instructions suggest the password is "PASSWORD" but this doesn't seem to work.  "password" does work.  I suppose this is the result of using all caps in the instructions?

**Screenshots**
<img width="382" alt="Screen Shot 2021-03-02 at 3 00 13 PM" src="https://user-images.githubusercontent.com/181685/109707316-04aa0a80-7b68-11eb-9d2f-52723ecf330c.png">

**Comment by stephencelis** [comment]
Haha, hey @khirsh! That's a styling change that happened between iOS versions where everything became uppercase. We think we have a workaround, though, so thanks for the heads-up!
