### ISSUE TITLE
API for EnvironmentLess Stores

### ISSUE THREAD

**Issue by natemann** [pointfreeco/swift-composable-architecture#47]
Following along with creating Stateless and Actionless viewStores in [#43 ](https://github.com/pointfreeco/swift-composable-architecture/issues/43), what are the thoughts on extending `Store` and `Reducer` with functions where `Environment` is Void? I am finding that for most stores, I don't need an `Environment` object.

I think it would be nice to have, but could bloat TCA quite a bit as you would have extensions for 3 possible scenarios:
- Environment is Void
- LocalEnvironment is void (for scopes)
-GlobalEnvironment is void (for pullbacks)

**Comment by stephencelis** [comment]
This is worth having a discussion about. Thanks @natemann!

Early on we played with some helpers for `Void` environments, but in practice we found that these `Void` environments almost always became struct environments with dependencies, and that the work to make this happen was less cumbersome if we started with empty struct environments to begin with:

- Fewer places to rename `Void` to `XyEnvironment` (a type alias can help here, but that's even more work you have to undo)
- Fewer things to change in `pullback` transformations and similar

This is why all of the examples in the repo define struct environments, _even_ if they don't have any dependencies.

Of course, these are just the trade-offs we've currently landed at, and depending on how someone builds an application and how much they modularize, I can see some applications having a _lot_ of small reducers with no dependencies benefitting from using `Void` for their environments.

One more helper is a reducer initializer that doesn't need to return `Effect.none`:

- `Reducer.init(_: (inout State, Action) -> Void) where Environment == Void`

**Comment by natemann** [comment]
@stephencelis. I see your point. 

I was not really thinking about a reducer that does not have to return `Effect.none`. I have a few reducers that don't have an environment, but still return an `Effect`. Mostly just the `fireAndForget` kind.

Secondly, I feel that we can still have an `Environment` , but have a reducer that does not return an `Effect`. I'm thinking of something like Environment.currentDate that just returns the current time. 

I know this is a little off topic, but your last comment intrigued me. My thoughts on `Environment == Void` was to not have to write `environment: { _ in () }` in pullbacks and scopes.

**Comment by stephencelis** [comment]
> I have a few reducers that don't have an environment, but still return an `Effect`. Mostly just the `fireAndForget` kind.

Worth noting that you'll still want to introduce an environment to supply this work if you want to write tests for those actions. We have a few examples of these kinds of tests in the demo apps. Voice Memos, for one, has some fire-and-forget effects in its audio recorder and audio player dependencies.

> My thoughts on `Environment == Void` was to not have to write `environment: { _ in () }` in pullbacks and scopes.

Yup! I think those versions of `pullback` are definitely handy for reducers with `Void` environments.

**Comment by stephencelis** [comment]
@natemann We just got a [Swift forum](https://forums.swift.org/c/related-projects/swift-composable-architecture) for discussions like this so that we can tighten the GitHub issues focus on bugs. Would you like to move the discussion there?

**Comment by natemann** [comment]
Sure thing.
