### ISSUE TITLE
How to coalesce shared object changes from two child states into a global property?

### ISSUE THREAD

**Issue by pcolton** [pointfreeco/swift-composable-architecture#49]
Let's say you have a global feature state that aggregates two other child states. Those child states are sharing some objects, let's say they can both show some of the same todo items. When the top level feature state is pulled back and assigned, the order of changes is lost (which child's change to the same object comes first?).

Here's some pseudocode, 3 items where one is shared between two lists:

```swift
let item1, item2, item3
let masterList = [item1, item2, item3]
let someListOfSharedItems = [item1, item2]
let anotherListOfSharedItems = [item1, item3]
```

the global state property of the feature:

```swift
var someFeature: SomeFeatureState {
    get {
        SomeFeatureState(firstList: someListOfSharedItems,
                         secondList: anotherListOfSharedItems)
    }
    set {
        let list1 = newValue.someListOfSharedItems
        let lsit2 = newValue.anotherListOfSharedItems
        
        // which list goes first into the global???
        self.masterList = updateFromList(list1)
        self.masterList = updateFromList(list2)
    }
}
```

That is, the 'setter' of the feature state won't know which of the two children made the change, and potentially one could overwrite the other as it is being assigned to some global property.

Is there a best practice here for when children share state objects that are coalesced at a top level state property?

**Comment by pcolton** [comment]
I'll propose my own answer, but still happy to hear alternatives...

The easiest answer is to push 'masterList' (in this example) down to the child and let it manage the filtering of the two lists, then upon pullback there's no bifurcation of state.

So `SomeFeatureState` would just use masterList and pullback the two child arrays itself, therefore it would know which is being mutated based on its own reducer.

**Comment by boudavid** [comment]
I think you can achieve this by handling the children actions in the parent reducer. Something like this :

```swift
struct Item {}

struct ParentState {
    var item1 = Item()
    var item2 = Item()
    var item3 = Item()
    var list = [item1, item2, item3]
    var childOneState = ChildOneState(items: [
        item1,
        item2
    ])
    var childTwoState = ChildTwoState(items: [
        item1,
        item3
    ])
}

struct ChildOneState {
    var items: [Item] = []

    init(items: [Item]) {
        self.items = items
    }
}

struct ChildTwoState {
    var items: [Item] = []

    init(items: [Item]) {
        self.items = items
    }
}

enum ParentAction {
    case childOneAction(ChildOneAction)
    case childTwoAction(ChildTwoAction)
}

enum ChildOneAction {
    case updatedItems([Item])
}

enum ChildTwoAction {
    case updatedItems([Item])
}

let parentReducer = Reducer.combine(
    Reducer<ParentState, ParentAction, ParentEnvironment> { state, action, environment in
        switch action {
        case let .childOneAction(.updatedItems(items)):
            // Do what you need to do with the updated items from child one
            return .none
        case let .childTwoAction(.updatedItems(items)):
            // Do what you need to do with the updated items from child two
            return .none
        }
    },
    childOneReducer.pullback(
        state: \.childOneState,
        action: /ParentAction.childOneAction,
        environment: { ChildOneEnvironment() }
    ),
    childTwoReducer.pullback(
        state: \.childTwoState,
        action: /ParentAction.childTwoAction,
        environment: { ChildTwoEnvironment() }
    )
}
```

And in the children reducers, you would just `return .none` for the `updateItems` action.

**Comment by boudavid** [comment]
The TicTacToe demo has a similar case where the AppReducer handles the the TwoFactor success response action which is nested in the Login action.

https://github.com/pointfreeco/swift-composable-architecture/blob/13ad378da204bd4ec96eed5ac1832ac67048f6b3/Examples/TicTacToe/Sources/Core/AppCore.swift#L35

**Comment by pcolton** [comment]
Thanks. When possible, I'm trying to avoid having a global action 'intercept' child actions to do work/update state, as it means the parent views have to be more intimately aware of how children might be mutating state.

One thing I'm trying to do is to see how an IdentifiedArray might be used to then have the forEach reducer 'do the right thing' and pullback each modified value back into the parent state automatically.

Todo example does some of this already, but I'd like to get it working more deeply nested.
