### ISSUE TITLE
Should we reopen issues here?

### ISSUE THREAD

**Issue by opsb** [pointfreeco/swift-composable-architecture#5]
There's a bunch of ongoing conversations on the original repo, do you want folks to just reopen them here? (perhaps with a link to the original)

**Comment by stephencelis** [comment]
We've archived the preview repo so unresolved conversations can definitely be re-opened here! We're keeping things pre-1.0 for a lil longer to allow for more API refinement, but it won't be quite as fast/loose these days 😄

**Comment by pteasima** [comment]
@opsb, just noticed this, I already stole one of your former issues https://github.com/pointfreeco/swift-composable-architecture/issues/16 😀

**Comment by stephencelis** [comment]
@opsb Cool to close this issue or do you have any other questions?

**Comment by opsb** [comment]
I left it open in case other people were wondering the same, I’ll close now though
