### ISSUE TITLE
AlertState docs have a typo

### ISSUE THREAD

**Issue by simme** [pointfreeco/swift-composable-architecture#518]
[This line](https://github.com/pointfreeco/swift-composable-architecture/blob/e1bd51b1761c9f7ab4001928c73f357c9116f807/Sources/ComposableArchitecture/SwiftUI/Alert.swift#L28)
```swift
var alert = AlertState<AppAction>?
```

Should probably be:
```swift
var alert: AlertState<AppAction>?
```

Sorry for not submitting a PR with the fix. Figured it was minor enough for someone with the repo already forked and checked out to quickly fix :)

**Comment by mbrandonw** [comment]
yup good find! will fix...
