### ISSUE TITLE
ComposableArchitectureTest package is missing while adding it from url

### ISSUE THREAD

**Issue by jmgawecki** [pointfreeco/swift-composable-architecture#539]
**Describe the bug**
Following https://www.pointfree.co/collections/composable-architecture/a-tour-of-the-composable-architecture/ep100-a-tour-of-the-composable-architecture-part-1 . When adding Composable Architecture, I fail to see ComposableArchitectureTest

<img width="672" alt="Screenshot 2021-05-10 at 11 57 32" src="https://user-images.githubusercontent.com/71930261/117649027-e9bace80-b186-11eb-9357-2b6aa9a668e3.png">

**To Reproduce**
Project -> Swift Packages -> Choose package repository -> https://github.com/pointfreeco/swift-composable-architecture -> Next -> Rules: Up to next major 0.18.0

**Expected behavior**
Screenshot from the pointfree.co tutorial:
<img width="484" alt="Screenshot 2021-05-10 at 11 59 49" src="https://user-images.githubusercontent.com/71930261/117649270-3dc5b300-b187-11eb-9803-de1e2b8ccd2d.png">

My actual project:
<img width="672" alt="Screenshot 2021-05-10 at 11 57 32" src="https://user-images.githubusercontent.com/71930261/117649027-e9bace80-b186-11eb-9357-2b6aa9a668e3.png">

**Environment**
 - Xcode [e.g. 12.5]
 - MacOS [e.g. 11.3, M1 chip]

**Additional context**
I am very new to the whole process so please forgive me if the answer to that problem is quite obvious. Thank You for the help.

**Comment by rhysm94** [comment]
ComposableArchitectureTest is no longer needed. You can just import ComposableArchitecture into your tests without the need for a separate library.

**Comment by jmgawecki** [comment]
Thank you!
