### ISSUE TITLE
Saving store?

### ISSUE THREAD

**Issue by yixe** [pointfreeco/swift-composable-architecture#54]
Would it be possible to keep the data in a store when you leave the view and come back?
Say I have a custom nav that switches between different screen of the app, every nav screen has its own Store() initiated in its main view. I send an Action on appear and save that data, but when you switch to a different screen/nav and come back the Store() is reinstated and the saved data is gone. Whats the best way to get around this issue? Thanks!

**Comment by tarjamorgado** [comment]
Hi @yixe,

> every nav screen has its own Store() initiated in its main view

You should be able to create a setter and a getter to take advantage of Global to Local and Local to Global state changes by computing your local state from the global state, with a computed property:

```swift
struct GlobalState {
    var some = ""
    // See here
    var localState: LocalState {
        get {
            LocalState(some: some)
        }
        set {
            some = newValue.some
        }
    }
}

enum GlobalAction {
    case localView(LocalAction)
}
```
Then when presenting the local view, any changes made to that localStore will be propagated back to the Global Store, retaining those changes in the Global State.

```swift
LocalView(
    store: self.store.scope(
        state: { $0.localState },
        action: {.localView($0) }
    )
)
```

Does this help? I hope I'm not far too off, I'm also still getting a grip of most things CA..

**Comment by yixe** [comment]
Thanks Tarja! didn't know about the scope property. I need to keep the properties in the GlobalState? the way I was doing it (without saving the state of each tab) is: 
```
struct GlobalState: Equatable {
    var active: Tab = .home
    enum Tab {
        case home
        case one
        case two
        case three
    }
}
```
Then in the main ContentView I switch over `active` and display the according view
```
switch viewStore.active {
     case .home: return HomeView()
     case .one: return One()
     ...
}
```
Then each view would look something like this
```
struct Home: View {
   var store = Store<HomeState, HomeAction>(initialState: HomeState(), reducer: homeReducer, environment: HomeEnvironment())
   var body: some View {
   ...
   .onAppear { viewStore.send(.loadTodos)} // api call
}
```
`HomeState` holds many properties that get populated onAppear so when you're switching tabs it happens again and again. So do I keep those in the GlobalState and pass it using the .scope() method you mentioned? I didn't want to make the GlobalState crowded

**Comment by boudavid** [comment]
I think you can do something similar to the TicTacToe demo where the AppState has properties for its children states like this :

```swift
public struct AppState: Equatable {
  // The states probably don't need to be optional in your case
  public var login: LoginState? = LoginState()
  public var newGame: NewGameState? = nil

  public init() {}
}
```
[Source](https://github.com/pointfreeco/swift-composable-architecture/blob/master/Examples/TicTacToe/Sources/Core/AppCore.swift)

And like @tarjamorgado said, you can scope down in the children views.

```swift

let store: Store<AppState, AppAction>

// When you need to present a child view
LoginView(
    store: self.store.scope(
        state: \.login,
        action: /AppAction.login
    )
)

struct LoginView: View {
  let store: Store<LoginState, LoginAction>

  var body: some View {
    // ...
  }

  init(store: Store<LoginState, LoginAction>) {
    self.store = store
  }
}
```
