### ISSUE TITLE
AnySchedulerOf<DispatchQueue> has no member main

### ISSUE THREAD

**Issue by toddwbates** [pointfreeco/swift-composable-architecture#548]
**Describe the bug**
Unable to run any of the example projects from TCA or isowords. All projects give this error.

.../swift-composable-architecture/Examples/TicTacToe/Sources/Views-SwiftUI/LoginSwiftView.swift:133:25: Type 'AnySchedulerOf<DispatchQueue>' (aka 'AnyScheduler<DispatchQueue.SchedulerTimeType, DispatchQueue.SchedulerOptions>') has no member 'main'

Also not able to run unit tests for ComposableArchitecture target. Similar error:
swift-composable-architecture/Tests/ComposableArchitectureTests/ComposableArchitectureTests.swift:40:35: error: type 'DispatchQueue' has no member 'test'
    let scheduler = DispatchQueue.test

**To Reproduce**
Clone project and try to run any demo project. Running on M1 Air (8GB) and Xcode 12.5.

**Expected behavior**
Should be able to run demo program.

**Screenshots**

**Environment**
 - Xcode 12.5
 - Swift [e.g. 5.2.2]
 - OS (if applicable): 11.3.1 

**Additional context**
I recently upgraded my machine to M1 and latest Xcode. These worked flawlessly on old machine.

**Comment by mbrandonw** [comment]
It seems that Xcode is not picking up the newest combine-schedulers code for some reason. Go to File > Swift Packages > Update to Latest Package Versions to force Xcode to update.

**Comment by toddwbates** [comment]
Thanks, that worked for the demo apps. Updated to version 5.0. Isowords still does not update. I noticed that the version is marked as 'iso' rather than 5.0. 
![Untitled](https://user-images.githubusercontent.com/1163646/118178585-fc344280-b3e8-11eb-9a24-1aeb1136757f.jpg)

**Comment by mbrandonw** [comment]
Yeah, we are currently running combine-schedulers off an experimental branch for isowords. I don't know why Xcode is struggling to update the packages. Perhaps you need to reset package caches and then try resolving :/

**Comment by mbrandonw** [comment]
Going to close this for now, but let us know if you have any more questions.

**Comment by toddwbates** [comment]
Thanks, clearing cache didn't work for isowords but that doesn't block me.
