### ISSUE TITLE
Sorting an IdentifiedArray returns an Element array, not IdentifiedArrayOf<Element>

### ISSUE THREAD

**Issue by pcolton** [pointfreeco/swift-composable-architecture#55]
I'm needing to use .sorted() on an IdentifiedArray, but it returns an array of the underlying Element, not an IdentifiedArrayOf<Element>.

**Comment by stephencelis** [comment]
@pcolton I believe this is the behavior of the standard library: any collection that you call `sorted` on will produce an array (_e.g._ `Set` and `Dictionary` are not ordered but _are_ collections and can still be `sorted`).

If this identified array is in state and state is mutable, can you call `sort` on it instead and sort it in-place? This should also be a memory win since it won't allocate another collection.

**Comment by pcolton** [comment]
I wanted to post here my colleagues quick 'hack' for our needs. This isn't a "correct" implementation, but worked for our needs, in case someone else needs it.

Also note we added an initializer to pass in a Slice, which happens when your .prefix() an array.

```swift
extension IdentifiedArray {
    public func sorted(by areInIncreasingOrder: (Element, Element) -> Bool) -> Self {
        let ids = self.ids.sorted { a, b in
            areInIncreasingOrder(
                self[a]!,
                self[b]!
            )
        }
        
        return Self(ids.map { self[$0]! }, id: self.id)
    }
    
    public init(_ slice: Slice<IdentifiedArray>) {
        self.init(Array(slice), id: slice.base.id)
    }
}
```

**Comment by stephencelis** [comment]
@pcolton Can you explain a bit more as to why you can't use the mutating `sort` method instead?

You could also leverage this with a couple imperative lines:

```swift
var sortedArray = identifiedArray
sortedArray.sort() // or .sort(by: { ... })
```

**Comment by pcolton** [comment]
I am returning a filtered, sorted, prefix'd result, and was just composing it. You are right, I can do it imperatively as well, it's just more code. For example, if I then need to .prefix the sorted result, it's more code yet.

**Comment by stephencelis** [comment]
@pcolton You can also manage filtering and prefixing with `remove*` methods:

```swift
.filter { ... }
// becomes:
.removeAll(where: { !... })

.sorted { ... }
// becomes:
.sort { ... }

.prefix(3)
// becomes
.removeSubrange(3...)
```

This will take the most advantage of `inout` performance. (I like the feeling of chaining `filter.sorted.prefix`, as well, but for mutating state over time it probably makes sense to stay imperative here.)
