### ISSUE TITLE
CocoaPods Support / Podspec

### ISSUE THREAD

**Issue by chrisballinger** [pointfreeco/swift-composable-architecture#557]
It would be great if there were alternative packaging options like CocoaPods for people hitting issues with Swift Package Manager. I'm willing to contribute a podspec, but I noticed the following 3 dependencies will also need CocoaPods support:

* https://github.com/pointfreeco/xctest-dynamic-overlay
* https://github.com/pointfreeco/swift-case-paths
* https://github.com/pointfreeco/combine-schedulers

Is this something you would consider merging?

Thanks!

**Comment by mbrandonw** [comment]
Hi @chrisballinger, sorry but we have chosen not to support cocoapods. The burden of maintenance is too high to do for all of our open source projects. If it's definitely necessary for your situation then you could maintain a fork of the repo that adds a podspec.

I'm going to close this issue now, but if you want to discuss further, or ask the community how they work around SPM bugs please do open a [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions) in the repo.

**Comment by chrisballinger** [comment]
No worries, I find it a pain to maintain podspecs as well. For anyone else who needs CocoaPods support, we have some initial working podspecs that you can add to your `Podfile` here:

```ruby
pod 'XCTestDynamicOverlay', :git => 'https://github.com/Rightpoint/xctest-dynamic-overlay.git', :branch => 'cocoapods-podspec'
pod 'CasePaths', :git => 'https://github.com/Rightpoint/swift-case-paths.git', :branch => 'cocoapods-podspec'
pod 'CombineSchedulers', :git => 'https://github.com/Rightpoint/combine-schedulers.git', :branch => 'cocoapods-podspec'
pod 'ComposableArchitecture', :git => 'https://github.com/Rightpoint/swift-composable-architecture.git', :branch => 'cocoapods-podspec'
```

I can confirm that ditching SPM and using these podspecs fixed the issue I was having in #556. Will probably need to file a radar with Apple for that one.

**Comment by cooler333** [comment]
how can i use it in cocoapods submodules in big enterprise app which use modules? we can't rewrite all app to SPM, and just then use TCA. It's sad :(

**Comment by cooler333** [comment]
I add cocoapods support for the latest TCA framework
 
```ruby
pod 'CasePaths', :git => 'https://github.com/cooler333/swift-case-paths.git', :branch => 'cocoapods-support'
pod 'CombineSchedulers', :git => 'https://github.com/cooler333/combine-schedulers.git', :branch => 'cocoapods-support'
pod 'ComposableArchitecture', :git => 'https://github.com/cooler333/swift-composable-architecture.git', :branch => 'cocoapods-support'
pod 'CustomDump', :git => 'https://github.com/cooler333/swift-custom-dump.git', :branch => 'cocoapods-support'
pod 'XCTestDynamicOverlay', :git => 'https://github.com/cooler333/xctest-dynamic-overlay.git', :branch => 'cocoapods-support'
pod 'IdentifiedCollections', :git => 'https://github.com/cooler333/swift-identified-collections.git', :branch => 'cocoapods-support'
pod 'OrderedCollections', :git => 'https://github.com/cooler333/swift-collections.git', :branch => 'cocoapods-support'
```

**Comment by lordzsolt** [comment]
Based on @cooler333 's implementation, I set up a custom podspec repo, so you can use it in your Podfile.

All you need to do is:

```
source 'https://github.com/lordzsolt/swift-composable-architecture-podspecs.git'

target 'YOUR_TARGET' do
  use_frameworks!

  pod 'ComposableArchitecture'
end
```

Considering the only thing that needs to be done is to change the version number and push a new version from time to time, I'll try to keep it up to date with TCA.

**Comment by 20120608** [comment]
#if !COCOAPODS
import ComposableArchitecture
#endif
希望能帮到你
