### ISSUE TITLE
Recommendations for handling a user object or other object that is needed throughout the app

### ISSUE THREAD

**Issue by grangej** [pointfreeco/swift-composable-architecture#577]
I am looking for some best practices on how to handle user object that is mutable / updatable (such as profile changes, etc).

I have an app that has multiple tabs and other nested structure and I am curious how to handle pushing update of a user object throughout the app? 

This is what I have so far
- AppState holds on to the user object 
- I have UserStore that is responsible for updating caching the user object. 
- I have views "pull" from the UserStore onAppear 

What is a good way to have AppState push the user object to all nested views? In vanilla SwiftUI this would be a perfect case for an environment object. How can I replicate global state like environment object in TCA ?

**Comment by mluisbrown** [comment]
> How can I replicate global state like environment object in TCA ?

I asked a similar question a little while back and the [answer](https://github.com/pointfreeco/swift-composable-architecture/discussions/505#discussioncomment-647373) is that you can use the TCA `Environment` for this.

**Comment by mbrandonw** [comment]
Transferring this to a discussion since it’s not an issue with the library.
