### ISSUE TITLE
Timer leaking on `02-Effects-Timers` example

### ISSUE THREAD

**Issue by txaiwieser** [pointfreeco/swift-composable-architecture#586]
On the file `02-Effects-Timers` at the examples projects I notice the timer keeps running after exiting the screen.

I can fix-it adding a onDisappear and cancelling if its not the intended behaviour.

We should at least add a comment explaining that in a real use it needs to be cancelled

```
let timersReducer = Reducer<TimersState, TimersAction, TimersEnvironment> {
  state, action, environment in
  struct TimerId: Hashable {}

  switch action {
  case .timerTicked:
    state.secondsElapsed += 1
    return .none

  case .toggleTimerButtonTapped:
    state.isTimerActive.toggle()
    return state.isTimerActive
      ? Effect.timer(
        id: TimerId(),
        every: 1,
        tolerance: .zero,
        on: environment.mainQueue.animation(.interpolatingSpring(stiffness: 3000, damping: 40))
      )
      .map { _ in TimersAction.timerTicked }
      : Effect.cancel(id: TimerId())
  }
}
```

**Comment by stephencelis** [comment]
@txaiwieser Ah yeah, good catch! We worked on each case study in full isolation so didn't really think about them being embedded in the "root" case studies feature. We'd be happy to take a PR to fix!

**Comment by stephencelis** [comment]
Revisiting this I think we probably don't consider this a "leak" since it's not a memory issue that shows up in the debugger. If anything it shows that the feature can still "run" after you've popped to the root. Since it works as we think it should, I'm going to close this out, but thanks for taking the time to report it to us!
