### ISSUE TITLE
Bug with explicitly defining LibraryType as 'dynamic'

### ISSUE THREAD

**Issue by natemann** [pointfreeco/swift-composable-architecture#60]
**Describe the bug**
When including ComposableArchitecture in an existing SPM, tests are not able to run. The following error is given: 

```The bundle <TestFramework> couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.```

```Library not loaded: @rpath/ComposableArchitecture.framework/ComposableArchitecture```

I am able to eliminate this bug by removing the `type: .dynamic,` from both frameworks in the package.swift file. However, if I do this, the example projects do not build

**To Reproduce**
[Todo.zip](https://github.com/pointfreeco/swift-composable-architecture/files/4604623/Todo.zip)
**Environment**
 - Xcode [e.g. 11.4.1 & 11.3]
 - Swift [e.g. 5.2.2 & 5.1]

**Comment by stephencelis** [comment]
(Related to #57 and #52.)

**Comment by stephencelis** [comment]
As noted in #57, `type: .dynamic` was a workaround for certain issues around modularity and testing, so removing it causes its own problems 😞

We may end up having to move ComposableArchitectureTestSupport to its own repo to avoid these SPM problems, but if anyone figures out a better fix we'd love to know!

**Comment by mbrandonw** [comment]
We're working on fixing this in #70, which has consolidated everything we know about the issue. Gonna close this in favor of tracking that one!

**Comment by stephencelis** [comment]
@natemann Can you give this branch a spin and see if that fixes things for you? https://github.com/pointfreeco/swift-composable-architecture/pull/71

Note that TicTacToe now depends on the static library once in the TicTacToeCommon module, which is a little extra work, but also how Apple suggests static SPM library dependencies should be consumed by a modularized app.

**Comment by natemann** [comment]
@stephencelis, this seems to be working for me now. Thank you so much.
