### ISSUE TITLE
swapAt breaks IdentifiedArray's state invariant

### ISSUE THREAD

**Issue by elfenlaid** [pointfreeco/swift-composable-architecture#606]
**Describe the bug**

`swapAt` breaks` IdentifiedArray`'s state invariant, so that two "identical" `IdentifiedArray` are no longer equal

**To Reproduce**

Copy-paste the provided test to `IdentifiedArrayTests.swift` file:

```swift
    func testSwap() {
        struct User: Equatable, Identifiable {
            let id: Int
            var name: String
        }

        var swapped = IdentifiedArrayOf<User>([
            User(id: 0, name: "Blob"),
            User(id: 1, name: "Blob Jr."),
        ])

        swapped.swapAt(0, 1)

        let recreated = IdentifiedArrayOf<User>([
            User(id: 1, name: "Blob Jr."),
            User(id: 0, name: "Blob"),
        ])

        XCTAssertEqual(swapped, recreated)
        XCTAssertEqual(swapped.ids, recreated.ids)
    }
```

**Expected behavior**
`IdentifiedArray`s should be equal

**Environment**
 - Xcode 13 / 12.5
 - Swift 5.5 / 5.4
 - OS iOS 15 / macOS 11.4

**Additional context**

`XCTAssertEqual failed: ("[0, 1]") is not equal to ("[1, 0]")` in logs states that `ids` are out of order.

Internal [`func swapAt` | swift/MutableCollection.swift](https://github.com/apple/swift/blob/main/stdlib/public/core/MutableCollection.swift#L264-L270) updates values via index subscripts:

```swift
@inlinable
public mutating func swapAt(_ i: Index, _ j: Index) {
  guard i != j else { return }
  let tmp = self[i]
  self[i] = self[j]
  self[j] = tmp
}
```

And the [current subscript implementation | IdentifiedArray.swift](https://github.com/pointfreeco/swift-composable-architecture/blob/main/Sources/ComposableArchitecture/SwiftUI/IdentifiedArray.swift#L93-L97) never updates the `ids` after modification: 

```swift
  public subscript(position: Int) -> Element {
    // NB: `_read` crashes Xcode Preview compilation.
    get { self.dictionary[self.ids[position]]! }
    _modify { yield &self.dictionary[self.ids[position]]! }
  }
```

I wonder what is the proper fix here? Possibilities that instantly come to mind are:

- provide a custom `swapAt` function
- update the `ids` field after each `_modify`

Maybe it would be nice to migrate to `OrderedDictionary` under the hood in the long term run?

**Comment by iampatbrown** [comment]
A custom swapAt function seems like a decent choice.

```swift
 public mutating func swapAt(_ i: Index, _ j: Index) {
    self.ids.swapAt(i, j)
  }
```
I have created a PR #644 if needed

**Comment by elfenlaid** [comment]
> A custom swapAt function seems like a decent choice.

Thanks, that's is a great start for sure! :)

**Comment by stephencelis** [comment]
We've extracted `IdentifiedArray` to its own repo: https://github.com/pointfreeco/swift-identified-collections

It's now a thin wrapper around [Swift Collections](https://github.com/apple/swift-collections)' `OrderedDictionary` type, which should hopefully prevent bugs like this (and others). Thanks for reporting, and for your patience as we worked on the fix 😄
