### ISSUE TITLE
ComposableArchitecture.xcworkspace does not show up in list of recents

### ISSUE THREAD

**Issue by mbrandonw** [pointfreeco/swift-composable-architecture#62]
**Describe the bug**

ComposableArchitecture.xcworkspace does not show up in list of recents.

Would love to know if there's something weird with our workspace or if there is a workaround.

**To Reproduce**

If you open ComposableArchitecture.xcworkspace and close it, you will see that it does not show up in the list of recent projects in Xcode's initial screen or in File > Open Recent.

**Expected behavior**

ComposableArchitecture.xcworkspace should show up in list of recents.

**Environment**
 - Xcode [e.g. 11.4.1]

**Comment by pcolton** [comment]
@mbrandonw It seems related to the fact that the workspace is -inside- the package. If I move it out (see the image below), then it starts showing up in the recents. 

<img width="362" alt="image" src="https://user-images.githubusercontent.com/92073/81487327-819e7900-9210-11ea-9a3a-31087521bc9f.png">

**Comment by mbrandonw** [comment]
Nice! Thanks for that tip.

I think that means we can put the `ComposableArchitecture.xcworkspace` inside the `Examples` directory to work around this issue.

I'm giving it a shot right now...

**Comment by pcolton** [comment]
FYI, @mbrandonw It seems Xcode takes the name of the Swift Package the workspace is in, and opens that instead.  If there's a package definition defined, then that becomes the name that shows up in recents, not the actual workspace. I suspect the only 'fix' is to have the workspace be -not- in a swift package folder.

<img width="348" alt="image" src="https://user-images.githubusercontent.com/92073/81487908-3471d580-9217-11ea-9e1b-389ecb7e99c4.png">

**Comment by mbrandonw** [comment]
Oh huh. Do you _also_ see ComposableArchitecture.xcworkspace show up there? Or just Examples?

We don't want to pull the workspace out of the package directory because then that means everything would need to be nested another level.

**Comment by pcolton** [comment]
Unfortunately I only see the examples and not the workspace

-Paul

**Comment by mbrandonw** [comment]
Dang ok. I think it was working for me for a brief moment because I created a blank ComposableArchitecture.xcworkspace and then added everything back to it. That must have gotten it in my recents temporarily :/

I'm tempted to revert this now, but will think about it a little bit longer.

**Comment by pcolton** [comment]
A potential workaround is to rename the examples package to compostable architecture examples so at least that’s in the list, because right now the only thing that’s in the recent list is the compostable architecture library package itself

-Paul

**Comment by mbrandonw** [comment]
Yeahhh gonna revert and re-open this issue :/

**Comment by stephencelis** [comment]
I filed FB7700969 ("Xcode doesn’t remember workspace as a recent project") with Apple.

**Comment by mycroftcanner** [comment]
Here is a way to do it:

1. Create a blank SwiftComposableArchitecture project
2. Add a dummy swift-composable-architecture module
3. Close xcode
4. move the SwiftComposableArchitecture.proj to a clone of swift-composable-architecture
5. edit the project file and change the path of the swift-composable-architecture to '.'
6. open *proj
7. open manage scheme and add the two targets
8. convert project to workspace
9. add case study projects, etc to the workspace

TCA can be accessed from recent, playgrounds can be easily added, etc.

**Comment by stephencelis** [comment]
@mycroftcanner Awesome find if this works! Would you like to submit a PR?

**Comment by mbrandonw** [comment]
Gonna close this out for now since there hasn't been much activity!
