### ISSUE TITLE
SwitchStore - change AppState from child

### ISSUE THREAD

**Issue by danielhorv** [pointfreeco/swift-composable-architecture#631]
Hey!

I'm not sure, it's a bug or I'm trying to do something in the wrong way... I created an example project to demonstrate my issues:

1.  I have to change the TestAppState from the child (ConfigView) which was presented with the `fullScreenCover` function. I just do the following in the testAppReducer
```swift
            case .onboarding(.config(.finished)):
                state = .main(.init())
                return .none
```

If I click the finish button, the TestAppState will be changed, but after that, the reducer receives some actions from the childs -> may be related to this: https://github.com/pointfreeco/swift-composable-architecture/issues/625

---
[TCAExample.zip](https://github.com/pointfreeco/swift-composable-architecture/files/6768800/TCAExample.zip)

Xcode 12.5 (but same for Xcode 13 beta)
ComposableArchitecture 0.20.0

**Comment by iampatbrown** [comment]
@stephencelis has changing breakpointOnNil to accept a closure been discussed in the past? 
```swift
// Before
breakpointOnNil: Bool = true
// After
breakpointOnNil: @escaping (Action) -> Bool = { _ in true }
```
eg. [swift-composable-architecture/pullback-nil](https://github.com/iampatbrown/swift-composable-architecture/tree/pullback-nil)

I know there has been a fair bit of discussion on this topic but not sure what the current consensus is. 
in @danielhorv's example it would look something like this:
```swift
...
onboardingReducer
      .pullback(
        state: /TestAppState.onboarding,
        action: /TestAppAction.onboarding,
        environment: { _ in OnboardingEnvironment() },
        breakpointOnNil: { action in action != .setConfigSheet(presented: false) }
      ),
...
```

**Comment by danielhorv** [comment]
https://github.com/pointfreeco/swift-composable-architecture/pull/667 also fixed this problem, so I close the issue.
