### ISSUE TITLE
Effect.timer looses the tolerance after some time

### ISSUE THREAD

**Issue by rurza** [pointfreeco/swift-composable-architecture#636]
**Describe the bug**

I have a very simple reducer that should "tick" every second:

```
let lastFmTimerReducer = Reducer<LastFmTimerState, LastFmTimerAction, SystemEnvironment<LastFmEnvironment>> { state, action, environment in
    
    struct TimerId: Hashable { }
    
    switch action {
    case .invalidate:
        state.isTimerActive = false
        state.secondsElapsed = 0
        return .cancel(id: TimerId())
    case .timerTicked:
        print("Date: \(Date())")
        state.secondsElapsed += 1
        return .none
    case .start:
        guard !state.isTimerActive else { return .none }
        state.isTimerActive = true
        return Effect
            .timer(id: TimerId(),
                   every: .milliseconds(1000),
                   tolerance: .zero,
                   on: environment.mainQueue)
            .map { _ in .timerTicked }
    case .pause:
        state.isTimerActive = false
        return .cancel(id: TimerId())
    }
}
.debug("⏰")
```

I noticed that after cancelling it and starting again it looses the tolerance, a lot:

```
Date: 2021-07-07 18:24:49 +0000
⏰: received action:
  LastFmTimerAction.timerTicked
  LastFmTimerState(
    isTimerActive: true,
−   secondsElapsed: 58
+   secondsElapsed: 59
  )

Date: 2021-07-07 18:24:51 +0000
⏰: received action:
  LastFmTimerAction.timerTicked
  LastFmTimerState(
    isTimerActive: true,
−   secondsElapsed: 59
+   secondsElapsed: 60
  )

Date: 2021-07-07 18:24:55 +0000
⏰: received action:
  LastFmTimerAction.timerTicked
  LastFmTimerState(
    isTimerActive: true,
−   secondsElapsed: 60
+   secondsElapsed: 61
  )

Date: 2021-07-07 18:25:03 +0000
⏰: received action:
  LastFmTimerAction.timerTicked
  LastFmTimerState(
    isTimerActive: true,
−   secondsElapsed: 61
+   secondsElapsed: 62
  )
```

Any idea what can be the cause?

**Environment**
  - swift-composable-architecture 0.20.0
  - Xcode 12.5
  - Swift 5.4
  - OS: macOS 11.4

**Comment by stephencelis** [comment]
@rurza Can you attach a project that exhibits this problem?

The repo comes with a case study that tests just this: https://github.com/pointfreeco/swift-composable-architecture/blob/main/Examples/CaseStudies/SwiftUICaseStudies/02-Effects-Timers.swift#L38-L48

But I'm seeing no discrepancy between how the timer performs before and after cancelling it a bunch of times.

**Comment by rurza** [comment]
I'm still figuring out the exact way to reproduce it. Right now it just happens randomly (but it happens always, sooner or later). 
I'll provide more info I'll find the cause/answer. I was hoping that some genius will have a look at the code and say that I'm doing something wrong :D

**Comment by stephencelis** [comment]
Looks pretty straightforward to me, basically the same as our timer case study.

You can drop this in to try to measure any "drift", which should print to the console: https://gist.github.com/stephencelis/6d3a3dd7c35458eff02ab17718cd48fb

I've toggled the timer a bunch and then left it running for 10 minutes or so, but no drift so far.

If you do have a project that can reliably reproduce the problem, please do attach it!

**Comment by rurza** [comment]
@stephencelis 
https://github.com/rurza/EffectTimer
Try this one :)
Run the app, leave it for some time and check the interval :(

I'm seeing this:
```
Date: 2021-07-07 19:16:46 +0000
⏰: received action:
  TimerAction.timerTicked
  TimerState(
    isTimerActive: true,
−   secondsElapsed: 5
+   secondsElapsed: 6
  )

Date: 2021-07-07 19:16:51 +0000
⏰: received action:
  TimerAction.timerTicked
  TimerState(
    isTimerActive: true,
−   secondsElapsed: 6
+   secondsElapsed: 7
  )

Date: 2021-07-07 19:16:51 +0000
⏰: received action:
  TimerAction.timerTicked
  TimerState(
    isTimerActive: true,
−   secondsElapsed: 7
+   secondsElapsed: 8
  )
```

**Comment by rurza** [comment]
I'm doing something similar in my own app – I have a reducer that deals with some shared state (including the timer state) and returns the Effect that invalidates the timer if some conditions are met.

**Comment by stephencelis** [comment]
@rurza I still can't repro. Been running this code awhile and it seems to work fine. Under the hood we are merely calling to the same code that Apple provides:

https://github.com/apple/swift-corelibs-foundation/blob/eec4b26deee34edb7664ddd9c1222492a399d122/Darwin/Foundation-swiftoverlay/Publishers%2BTimer.swift

I have a couple ideas:

- Can you try adding a `runLoop` to your environment and use that for the timer instead? I'm wondering if using a dispatch queue for timing isn't working as well.

- Can you try replacing your timer code with Foundation's `Timer.publisher` to see if you encounter the same issue?

    ```swift
          return Timer.publish(
            every: 1,
            tolerance: .zero,
            on: .main,
            in: .default
          )
            .autoconnect()
            .eraseToEffect()
            .cancellable(id: TimerId(), cancelInFlight: true)
            .map { _ in .timerTicked }
```

It uses a run loop and not a scheduler/queue, so that'd be one difference.

And if that works, can you try using an `AnySchedulerOf<RunLoop>` with `Effect.timer`?

**Comment by rurza** [comment]
Nah, doesn't help :( I tried with the both runloop and Combine's publisher, on two different machines (and I even restarted the OS), even with the release configuration :(

**Comment by stephencelis** [comment]
@rurza Are you saying you're seeing the same problem with both of alternatives? If so, it sounds like this isn't a TCA bug, but a bug with Apple.

**Comment by iampatbrown** [comment]
I was able to reproduce something similar using SwiftUI and Timer.publish 
```swift
struct ContentView: View {
  let tick = Timer.publish(
    every: 1,
    tolerance: .zero,
    on: .main,
    in: .default
  )
  .autoconnect()

  var body: some View {
    Text("Hello, rurza!")
      .padding()
      .onReceive(tick) {   print("tock: \($0)")   }
  }
}
```
I couldn't really get it consistent but it would involve either opening a bunch of other windows or causing high cpu usage. Eventually the print statements would stagger and sometimes stop until i brought the app back to the foreground. Could this be related?

@rurza Are you doing anything else when the issue occurs

@stephencelis it does sound like more for a bug or an OS/Xcode thing. I can look into it a bit later. Just thought id confirm that it most likely isn't related to the Effect implementation.

**Comment by stephencelis** [comment]
@rurza I think you're experiencing expected `Timer` behavior. From the documentation:

> A timer is not a real-time mechanism. If a timer’s firing time occurs during a long run loop callout or while the run loop is in a mode that isn't monitoring the timer, the timer doesn't fire until the next time the run loop checks the timer. Therefore, the actual time at which a timer fires can be significantly later. See also [Timer Tolerance](https://developer.apple.com/documentation/foundation/timer#1667624).

—https://developer.apple.com/documentation/foundation/timer

If you're relying on precise timing, or measuring a growing interval, you may want to poll more frequently and rely on a more absolute source of truth, like `Date()`, where you hold onto the `startDate` in state, and calculate the interval in `timerTicked` by comparing it to the current date.

**Comment by rurza** [comment]
> @rurza Are you doing anything else when the issue occurs
No, but it's possible that some long running effect will trigger an action. But nothing heavy that requires a lot of CPU time.

@stephencelis I think about 2 workarounds, but I don't think it's the tolerance.   
I'm already using good old NSTimer in the version 1.x of the app (maybe its implementation differs from the Timer), where the first release was targeting OS X 10.10 with the tolerance already in the Foundation, and it never, ever failed me. And I don't care about the 100ms difference (which is what I understand as the `not a real-time mechanism`. Right now I'm loosing sometimes more than 50% of expected "ticks". Please notice, that docs say 
> For repeating timers, the next fire date is calculated from the original fire date regardless of tolerance applied at individual fire times, to avoid drift. 

So this doesn't explain why the timer isn't firing for 10 or more seconds. And the app doesn't do anything at the time, so the run loop or the main queue isn't blocked.  

Anyway, I really, really appreciate your help, folks :) I'll close the issue and if I'll find any solution (and I will) I'll post it here.

**Comment by mbrandonw** [comment]
One thing to keep in mind is that `Effect.timer` is actually powered by [`Publishers.Timer`](https://github.com/pointfreeco/combine-schedulers/blob/e02082cd2dbb9e3453a380fceebec8d2b63ef8a7/Sources/CombineSchedulers/Timer.swift#L41-L81) that we created for our [`CombineSchedulers`](https://github.com/pointfreeco/combine-schedulers) library. We do this because the only timer publisher that comes with Foundation is `Timer.publisher`, which only works with `RunLoop` and therefore is not testable since a `TestScheduler` cannot be used to control the timer for tests.

Since you are using `environment.mainQueue` to construct your `Effect.timer` it means that technically under the hood it is using `DispatchQueue`'s interval scheduler, as seen here:

https://github.com/pointfreeco/combine-schedulers/blob/e02082cd2dbb9e3453a380fceebec8d2b63ef8a7/Sources/CombineSchedulers/Timer.swift#L294-L301

So, it's not actually Foundation's `Timer` that is running at all in your effect. It's `DispatchQueue`. I don't know if that actually makes a difference, but I would be curious what happens if you swap out your `mainQueue: AnySchedulerOf<DispatchQueue>` with a `mainRunLoop: AnySchedulerOf<RunLoop>`. Maybe run loops can be better at correcting for drift than dispatch queues can?

**Comment by rurza** [comment]
I have the same problem with the RunLoop

**Comment by mbrandonw** [comment]
Very strange. I wonder if `RunLoop.main.schedule` with an interval doesn't secretly use a `Timer` under the hood.

Another option is to implement your own timer effect using `Timer`, but in such a way that you can still test it with `TestScheduler`. It's definitely possible, just a bummer that that must be done :/

**Comment by rurza** [comment]
I just checked my old code and it seems that it's not the same use case – I was setting the interval for the non repeatable timer upfront (with the exact value when it should fire, but with the support for pausing). In worst case I'll modify the code to work it in the same way.  But still – I'd expect that for 1s interval, that after 100 seconds I'd get 99-101 hits, not 30 :/

**Comment by rurza** [comment]
And I can confirm that Foundation's Timer stop firing after some time as well (in both SwiftUI and AppKit based apps), so maybe indeed it's the expected behavior 🥲

Case closed.

**Comment by iampatbrown** [comment]
Thanks for the updates @rurza definitely a good thing to be aware of.
