### ISSUE TITLE
ViewStore.publisher doesn't seem to work as expected in 0.21.0

### ISSUE THREAD

**Issue by lukeredpath** [pointfreeco/swift-composable-architecture#651]
**Describe the bug**
I can see from the release notes that 0.21.0 changes the behaviour of ViewStore.publisher but I can't see how it is causing the issue I'm seeing. For some reason it seems to publish just a single change even though I know the state is changing.

We have some integration tests that need to log the user in to our app - we do this by creating a `ViewStore` around a real store with some live dependencies and sending actions that simulate the process of a user logging in. We then sink on the `ViewStore.publisher` around our root App Store to wait for the necessary state change that would indicate that the user is logged in. This worked fine with 0.20.0 and no longer works with 0.21.0.

**To Reproduce**
A simplified representation of our app state:

```swift
struct AppState: Equatable {
  var session: SessionState
}

enum SessionState: Equatable {
  case loggedOut(LoggedOutState)
  case loggedIn(LoggedInState)
}
```

The login functionality is managed inside the `LoggedOut` domain. Our integration test code does something similar to this:

```swift
let loggedOutStore = app.appStore.scope(
  state: { extract(case: SessionState.loggedOut, from: $0.session)! },
  action: { AppAction.session(.loggedOut($0)) }
)

let viewStore = ViewStore(loggedOutStore)

// send a bunch of actions to viewStore that simulate the user entering their login details and
// hitting the login button. Tapping the login button will start a bunch of async effects that make
// various API requests.

// Now wait for the `AppState.session` to flip from `.loggedOut` to `.loggedIn`:

ViewStore(store)
  .publisher
  .compactMap { extract(case: SessionState.loggedIn, from: $0.session) }
  .prefix(1)
  .sink(receiveValue: callback) // callback is passed into the helper function that encapsulates this behaviour
  .store(in: &cancellables)
```

**Expected behavior**
In 0.20.0, when the login completes the session state changes to `.loggedIn` and this triggers the `callback` function above to be executed. In 0.21.0 this never happens. In fact, if I simplify the above to:

```swift
ViewStore(store)
  .publisher
  .sink { print($0) }
  .store(in: &cancellables)
```

Then the `.sink` is only called once - I don't see any intermediate state changes (and there should be quite a few changes within the `loggedOutState` while the login process happens).

**Environment**
  - TCA 0.21.0
  - Xcode 12.5.1
  - OS: iOS 14.

**Comment by stephencelis** [comment]
@lukeredpath Is it possible for you to cook up a failing test case? Without having a fuller picture of your setup it's hard to know what the exact problem may be.

The associated change from 0.20.0 to 0.21.0 is from this pull request: https://github.com/pointfreeco/swift-composable-architecture/pull/624/files

Does anything in that diff stand out to you?

**Comment by lukeredpath** [comment]
Nothing is immediately jumping out. I think I've managed to get a failing test case in an example project though.

[TCABugTestProject.zip](https://github.com/pointfreeco/swift-composable-architecture/files/6802474/TCABugTestProject.zip)

I'm using `.debug()` on the reducer and you can see in the console output that the state does indeed change to `.loggedIn` after a second but the `.sink` is never called and the expectation is not fulfilled.

**Comment by lukeredpath** [comment]
Right - I managed to figure this out. The problem is that the `ViewStore` is being deallocated. If I assign `ViewStore(store)` to a local variable in that test first, then it passes. This appears to be the same problem in my actual app.

I'm curious as to why this worked before - it seems like previously something in the previous publisher implementation was retaining a strong reference to the `ViewStore` and it no longer does. I wonder if this has the potential to break anything else.

**Comment by stephencelis** [comment]
@lukeredpath Ah interesting! This makes sense as previously the publisher had an independent lifecycle, but in order to minimize extra calls to `removeDuplicates` it is now a dependency of the view store. We're open to ideas of how to restore this functionality, but want to avoid introducing a retain cycle.

**Comment by stephencelis** [comment]
(@mbrandonw and I have been chatting about this for awhile, but we think sharing `ViewStore` across SwiftUI and UIKit has been a bit of a bumpy ride, and this is just another example. We think there may be something to having separate concepts in the future.)

**Comment by lukeredpath** [comment]
IMO I think its fine (and arguably more correct) for the API contract to specify that the caller needs to retain a reference to a `ViewStore` if they intend to do things like sinking on the `.publisher`, it would be good to call this out in the documentation though so it's clear.

**Comment by stephencelis** [comment]
@lukeredpath We think ownership should be pushed to the "leaves" of the system, which is why a view store holds onto its parent store, and so we think a store publisher should somehow hold onto its view store. @mbrandonw and I are working on a fix now.
