### ISSUE TITLE
Extraneous View Redrawing

### ISSUE THREAD

**Issue by eliotfowler** [pointfreeco/swift-composable-architecture#67]
_Note: This could be an issue with SwiftUI and not TCA, but most likely it's my fault!_

I'm seeing an issue where ViewStore updates to child views are causing unnecessary re-renders of parent views. It seems to compound the deeper I nest. The issue this is causing is when I type into a text field that is nested and type quickly (or backspace quickly) it seems to drop characters. I notice that this issue does not exist in any of your Examples so it must be something I'm doing wrong.

Are there any debugging tools within TCA or that you've used while working on it that might help me figure out why I'm getting view renders in parent views whose state is not changing.

The output when I add debug logs to `WithViewStore` shows that when simply incrementing the counter on the child view, it does 3 view renders:

```
received action:
  AppAction.modalFlow(
    ModalFlowAction.incr
  )
  AppState(
    modalFlow: ModalFlowState(
−     counter: 0,
+     counter: 1,
      text: ""
    )
  )

ModalFlowView: Evaluating WithViewStore<ModalFlowState, ModalFlowAction, ...>.body
AppView: Evaluating WithViewStore<AppState, AppAction, ...>.body
ModalFlowView: Evaluating WithViewStore<ModalFlowState, ModalFlowAction, ...>.body
```

[Zip](https://github.com/pointfreeco/swift-composable-architecture/files/4606824/TCATest.zip) of the runnable sample app.

<details>
  <summary>The code for the small sample app is here:</summary>

**AppCore.swift**

```swift
struct AppState: Equatable {
  var modalFlow: ModalFlowState?
}

enum AppAction: Equatable {
  case flowDismissed
  case modalFlow(ModalFlowAction)
  case tapStartFlow
}

struct AppEnvironment {}

let appReducer: Reducer<AppState, AppAction, AppEnvironment> = Reducer.combine(
  Reducer { state, action, environment in
    switch action {
    case .flowDismissed:
      state.modalFlow = nil
      return .none

    case .modalFlow:
      return .none

    case .tapStartFlow:
      state.modalFlow = ModalFlowState()
      return .none
    }
  },

  modalFlowReducer.optional.pullback(
    state: \.modalFlow,
    action: /AppAction.modalFlow,
    environment: { _ in ModalFlowEnvironment() }
  )
)
```

**AppView.swift**

```swift
struct AppView: View {
  let store: Store<AppState, AppAction>

  init(store: Store<AppState, AppAction>) {
    self.store = store
  }

  var body: some View {
    WithViewStore(store) { viewStore in
      NavigationView {
        VStack {
          NavigationLink(
            destination: IfLetStore(
              self.store.scope(state: \.modalFlow, action: AppAction.modalFlow),
              then: ModalFlowView.init(store:)
            ),
            isActive: viewStore.binding(
              get: { $0.modalFlow != nil },
              send: { $0 ? .tapStartFlow : .flowDismissed }
            )
          ) {
            Text("Start flow")
          }
        }
      }
    }.debug(prefix: "RootView")
  }
}
```

**ModalFlowCore.swift**

```swift
struct ModalFlowState: Equatable {
  var counter = 0
  var text = ""
}

enum ModalFlowAction: Equatable {
  case incr
  case textChanged(String)
}

struct ModalFlowEnvironment {}

let modalFlowReducer = Reducer<
  ModalFlowState, ModalFlowAction, ModalFlowEnvironment
> { state, action, environment in
  switch action {
  case .incr:
    state.counter += 1
    return .none
  case let .textChanged(newText):
    state.text = newText
    return .none
  }
}
```

**ModalFlowView.swift**

```swift
struct ModalFlowView: View {
  let store: Store<ModalFlowState, ModalFlowAction>

  init(store: Store<ModalFlowState, ModalFlowAction>) {
    self.store = store
  }

  var body: some View {
    WithViewStore(store) {
      viewStore in
      VStack {
        Text("Counter: \(viewStore.counter)")
        Button("Incr") { viewStore.send(.incr) }
        TextField("Text", text: viewStore.binding(get: \.text, send: ModalFlowAction.textChanged))
          .padding()
      }
    }.debug(prefix: "CounterView")
  }
}
```
</details>

A demo of the app/issue (I type lots of characters into the text field and then just hold down on backspace):
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/1241943/81511438-68f49880-92ce-11ea-8abc-3c6369b59491.gif)

**Comment by mbrandonw** [comment]
Hey @eliotfowler, this is a good question and something we probably don't have enough information/documentation on.

The key is in this line:

```swift
WithViewStore(store) { viewStore in 
}
```

This is your chance to whittle away the state to the bare essentials for your view to do its job. This allows you to cut down renders and to expose a more domain specific version of your state so that your view can be as logicless as possible.

In particular, this view only needs access to the fact that `modalFlow` is or isn't `nil`. And so if you scope the store to just that information you will only render the view when performing the navigation:

```swift
WithViewStore(store.scope(state: { $0.modalFlow != nil })) { viewStore in
  ...
  viewStore.binding(
    get: { $0 },
    send: { $0 ? .tapStartFlow : .flowDismissed }
  )
  ...
}
```

If the logic in `store.scope(state: { })` starts to get complicated you can also pull that out into its own little `ViewState` struct with an initializer to do the work:

```swift
struct AppView: View {
  struct ViewState {
  }

WithViewStore(store.scope(state: { $0.modalFlow != nil })) { viewStore in

```

**Comment by eliotfowler** [comment]
Thanks for the speedy reply, Brandon!

Indeed that solved the issue. Strange thing is, I had a ViewState with a `isFlowShowing` property, mapped to `modelFlow != nil` and pared it away in my effort to find the smallest sample app that would reproduce the issue. I'm not sure why that wasn't working, but given that the sample app seems to be working now, I'm hopeful I can retrace my steps to figure out what went wrong.

Thanks again for the help!

**Comment by eliotfowler** [comment]
Just to close the loop on this, I reverted my changes that I made to minimize the size of the sample app to see what my local ViewState had and it was: 

```swift
struct ViewState: Equatable {
    let modalFlow: ModalFlowState?
    let isSheetPresented: Bool
  }
```

I was including the whole child state thinking I needed it to pass it to the child view. But since we do `store.scope` instead of `viewStore.scope`, I don't need to hold on to that in the parent's ViewState.

**Comment by mbrandonw** [comment]
Awesome, glad you caught that!
