### ISSUE TITLE
Animation doesn't work for actions sent to view stores inside bindings

### ISSUE THREAD

**Issue by mathieutozer** [pointfreeco/swift-composable-architecture#68]
**Describe the bug**
I am animating a state transition by sending actions to a store inside a binding (in a toggle)

**To Reproduce**
Both controls toggle the state and the view changes. Only the action sent by the button causes the change to be animated.

```swift
          Button(action: {
            withAnimation(.interactiveSpring(response: 0.25, dampingFraction: 0.1)) {
              viewStore.send(.surface(.bigMap))
            }
          }) {
            Text("Toggle")
          }
          Toggle(isOn: viewStore.binding(
            get: \.surfaceState.bigMap,
            send: {  _ in
              withAnimation(.interactiveSpring(response: 0.25, dampingFraction: 0.1)) {
                .surface(.bigMap)
              }
          }), label: {
            Text("Big Map")
          })
```

**Expected behavior**
Both actions should animate changes.

**Comment by mbrandonw** [comment]
Hey @mathieutozer, thanks for the report!

This is a good find, and it's not something the `viewStore.binding` helper supports right now. It's easy enough to add, we just need to think through the API a bit.

In the meantime you can easily work around this by constructing the `Binding` from scratch yourself, and then you can do the animation stuff quite easily:

```swift
Binding(
  get: { viewStore.toggle },
  set: { toggle in
    withAnimation(.interactiveSpring(response: 0.25, dampingFraction: 0.1)) {
      viewStore.send(.toggle(toggle))
    }
})
```

This is basically what `viewStore.binding` is doing under the hood anyway.

Let me know if that works!

**Comment by stephencelis** [comment]
`Binding` has an `animate` API that can also be used. Try this out!

``` swift
Toggle(
  isOn: viewStore
    .binding(get: \.surfaceState.bigMap,  send: .surface(.bigMap))
    .animate(.interactiveSpring(response: 0.25, dampingFraction: 0.1))
) {
  Text("Big Map")
}
```

**Comment by stephencelis** [comment]
@mathieutozer Closing this out with some documentation alongside the animations case study: #79

Thanks for bringing this to our attention!
