### ISSUE TITLE
ViewStore sometimes replays previous state values to subscribers

### ISSUE THREAD

**Issue by adamastern** [pointfreeco/swift-composable-architecture#697]
**Describe the bug**

`ViewStore` publisher appears to sometimes replay its previous state value after publishing the latest, correct value.

**To Reproduce**

The scenario that produces this behavior is:

1) Send a `ViewStore` action which updates "Property A" on state.
2) Have a subscription on the same view store listening to "Property A". When the subscription receives the updated value from the `.send` above, synchronously dispatch another action which mutates "Property B".
3) Have a subscription on the view store listening to "Property B".
4) I would expect that the "Property B" subscriber receives two values. (1) for the initial value of B, and (2) the new value set in step 2.

Sometimes, the "Property B" subscriber receives a third, final update with the store's initial value for "Property B", after having received the value set in step 2.

The bug only repros ~50% of the time. The following test may need to run a number of times before this repros:

[TcaWithTestCase.zip](https://github.com/pointfreeco/swift-composable-architecture/files/6941543/TcaWithTestCase.zip)

```swift

  var cancellables: Set<AnyCancellable> = []

  func testOldStateReplaysInViewStoreSubscriber() {
    struct State: Equatable {
      var city: String
      var country: String
    }

    enum Action: Equatable {
      case updateCity(String)
      case updateCountry(String)
    }

    let reducer = Reducer<State, Action, Void> { state, action, _ in
      switch action {
      case let .updateCity(city):
        state.city = city
        return .none
      case let .updateCountry(country):
        state.country = country
        return .none
      }
    }

    let store = Store(
      initialState: .init(city: "New York", country: "USA"),
      reducer: reducer,
      environment: ()
    )
    let viewStore = ViewStore(store)

    viewStore.publisher.city
      .sink { city in
        // After we get the first update, let's update the country to "UK"
        if city == "London" {
          viewStore.send(.updateCountry("UK"))
        }
      }
      .store(in: &cancellables)

    var seenCountries = [String]()
    viewStore.publisher.country
      .sink { country in
        seenCountries.append(country)
      }
      .store(in: &cancellables)

    // Send the initial update to make city "London"
    viewStore.send(.updateCity("London"))

    // Test that we only see two updates:
    // 1) "USA"
    // 2) "UK"
    // Sometimes, we get a third update with "USA" again...

    XCTAssertEqual(seenCountries, ["USA", "UK"])
  }
```

**Expected behavior**

`ViewStore` shouldn't replay previous state value

**Screenshots**

n/a

**Environment**
  - swift-composable-architecture version 0.23.0
  - Xcode 12.5.1
  - Swift 5.4
  - OS: MacOS 11.12.3

**Comment by iampatbrown** [comment]
Thanks for providing a good example. I can confirm the same result on my end and am trying to get a better idea of the issue. 

Is there a particular reason you're not putting the update country logic inside the reducer? My guess is that sending .updateCountry via sink is causing a race condition.

**Comment by krzysztofzablocki** [comment]
@iampatbrown note that if you also subscribe to the `viewStore.publisher` you'll see it always get 3 state updates and the difference between failed and successful run is the order being inconsistent.

UIKit / AppKit apps tend to use publisher observation a lot and this situations is likely to happen in bigger apps, causes weird to track down bugs.

**Comment by iampatbrown** [comment]
@kaandedeoglu this is more to do with how combine works though right? You would probably have to send the action using `DispatchQueue.main.asyc` or use the `publisher.receive(on:)`
For example the same issue occurs using the below
```swift
func testCombine() {
  var cancellables: Set<AnyCancellable> = []

  struct State: Equatable {
    var city: String
    var country: String
  }

  let state = CurrentValueSubject<State, Never>(.init(city: "New York", country: "USA"))

  state.map(\.city)
    .removeDuplicates()
    .filter { $0 == "London" }
    .sink { _ in state.value.country = "UK" }
    .store(in: &cancellables)

  var seenCountries = [String]()
  state.map(\.country)
    .removeDuplicates()
    .sink { seenCountries.append($0) }
    .store(in: &cancellables)

  state.value.city = "London"

  XCTAssertEqual(seenCountries, ["USA", "UK"])
}

```

**Comment by krzysztofzablocki** [comment]
when I was debugging TCA internals I didn't really notice anything wrong or inconsistent between failure / success cases on the side of library itself, so definitely feels like combine thing.

If there is no workaround for this kind of scenario probably worth adding a note in doc / sample

**Comment by mbrandonw** [comment]
There is some non-determinism in Combine that you are seeing here. It seems that the order of subscriptions isn't guaranteed. Running this in a playground you will see that sometimes it crashes and sometimes it doesn't:

```swift
var cancellables: Set<AnyCancellable> = []

let subject = CurrentValueSubject<Int, Never>(1)

var value = 0
subject.sink { value = $0 }
  .store(in: &cancellables)

subject.sink { assert($0 == value) }
  .store(in: &cancellables)

subject.send(1)
```

For this reason you probably should only do truly independent tasks inside `.publisher.sink` closures. So sending an action in one `.sink { }` that needs to be properly observed in another `.sink { }` is probably not going to work out well.
