### ISSUE TITLE
Installation section is a link to the repository?

### ISSUE THREAD

**Issue by pwightman** [pointfreeco/swift-composable-architecture#7]
I expected the installation section to detail some ways to install, but it just has a link to the repository? Are installation details coming later? Found this confusing is all, I don't necessarily have specific expectations of what should be here.

**Comment by stephencelis** [comment]
Good point! It can be done using Xcode's SPM integration (by pasting the quoted repo URL into Xcode's interface), but it would be nice to have some step-by-step instructions.
