### ISSUE TITLE
Using Composable Architecture in viewless Swift executable

### ISSUE THREAD

**Issue by andrewayres** [pointfreeco/swift-composable-architecture#703]
I used the readme example ```AppState```, ```AppAction```, ```ApiError```, ```AppEnvironment```, ```appReducer``` and ```store``` code in a viewless Swift executable.

How do I send actions to the store, or read from app state, when there's no ViewStore or any other view?

Using,
```store.send(.someAppAction)```

is resulting in the error: ```'send' is inaccessible due to 'internal' protection level```, even if I make  all the structs and enums public.

Example code in main.swift of the Swift executable;

```swift
import Foundation
import ComposableArchitecture

public struct AppState: Equatable {
  var count = 0
}

public enum AppAction: Equatable {
  case incrementCounter
}

public struct ApiError: Error, Equatable {}

public struct AppEnvironment {
}

let appReducer = Reducer<AppState, AppAction, AppEnvironment> { state, action, environment in
  switch action {

  case .incrementCounter:
    state.count += 1
    return .none
  }
}

let store = Store(
    initialState: AppState(),
    reducer: appReducer,
    environment: AppEnvironment()
  )

store.send(.incrementCounter) // results in error: 'send' is inaccessible due to 'internal' protection level
```

Sorry if I'm doing something obviously wrong. I plan to convert the viewless swift executable to a SwiftUI app at some point.

**Comment by iampatbrown** [comment]
A ViewStore does not necessarily have to be inside a SwiftUI/UIKit View.

> A ViewStore is an object that can observe state changes and send actions. They are most commonly used in views, such as SwiftUI views, UIView or UIViewController, but they can be used anywhere it makes sense to observe state and send actions.

So in the above example you can do this:

```swift
...

let viewStore = ViewStore(store)

viewStore.send(.incrementCounter)
```
I like to think of it more as a View into the Store instead of a Store that is in a View. 

Also, you can include code blocks in posts by placing triple backticks ` ``` ` at the start and end of your code. You can also add syntax highlighting like so:
````swift
```swift
let store = Store(
  initialState: AppState(),
  reducer: appReducer,
  environment: AppEnvironment()
)
```
````
See [here](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) for more info.

**Comment by andrewayres** [comment]
Thank you! It now works. Thanks for explaining ViewStore as a 'view into the store', it makes sense now. Also, thanks for the markdown tip, I've edited my original post and added code blocks.
