### ISSUE TITLE
0.25 - Fails to build for Any iOS Device (arm64)

### ISSUE THREAD

**Issue by mikolaj92** [pointfreeco/swift-composable-architecture#737]
**Describe the bug**
On version 0.25 I'm unable to build the app for `Any iOS Device (arm64)`
The issue lies with the new dependency https://github.com/pointfreeco/swift-custom-dump

**To Reproduce**
[TestApp.zip](https://github.com/pointfreeco/swift-composable-architecture/files/7030468/TestApp.zip)

**Expected behaviour**
The app should build for `Any iOS Device (arm64)`

**Screenshots**
![screenshot 2021-08-23 at 10 45 20](https://user-images.githubusercontent.com/7442637/130418007-91676302-ae73-4df2-ab1d-be10167e27de.png)

**Environment**
  - swift-composable-architecture version [0.25]
  - Xcode [12.5.1]
  - Swift [5.4]
  - OS: [iOS 14]

**Comment by stephencelis** [comment]
@mikolaj92 We released a 0.1.1 of Custom Dump that should address the problem. Can you update your packages to pull that in and try again?

**Comment by mikolaj92** [comment]
Everything started working correctly on both my local machine and the CI server. 
Thanks @stephencelis for the fix and fast reaction 👍
