### ISSUE TITLE
Store documentation

### ISSUE THREAD

**Issue by kgrigsby59** [pointfreeco/swift-composable-architecture#745]
I'm new to TCA and was reading over Store.swift. In the documentation around lines 48-50 shouldn't the associated values be actions and not state?

case activity(ActivityState) -> case activity(ActivityAction)

**Comment by mbrandonw** [comment]
😬 You are totally right. These should all be actions:

https://github.com/pointfreeco/swift-composable-architecture/blob/7fec6a4df76a4cabcacfc424507ac4d9becb97e0/Sources/ComposableArchitecture/Store.swift#L47-L50

Interested in sending a PR? If not we can take care of it.

Thanks for catching this! Can't believe we went this long without seeing it 😁
