### ISSUE TITLE
0.1.3 is no longer dynamic? (my project breaks)

### ISSUE THREAD

**Issue by pcolton** [pointfreeco/swift-composable-architecture#77]
I just updated to 0.1.3 and my project won't compile any more:

`Swift package product 'ComposableArchitecture' is linked as a static library by 'Library' and 5 other targets. This will result in duplication of library code.
`

I've been following the comments about changes required for testing, so is making the main package no longer dynamic part of that fix? It means I now have to wrap the package in a framework again, correct?

**Comment by stephencelis** [comment]
@pcolton You're exactly right, sorry about that! We note the change in the second item of the release notes now here: https://github.com/pointfreeco/swift-composable-architecture/releases/tag/0.1.3

We're moving a bit more fast/loose with pre-1.0 releases but will try to keep these breakages to a minimum in the future.

**Comment by pcolton** [comment]
No worries, just wanted to make sure before pushing my own fix.
