### ISSUE TITLE
HypertextApplicationLanguageTests/Fixtures

### ISSUE THREAD

**Issue by saroar** [pointfreeco/swift-composable-architecture#775]
Showing All Messages  HypertextApplicationLanguage Invalid Exclude '/Users/alif/Library/Developer/Xcode/DerivedData/Addame-biwqafsqwbkxfaakpgvfcpnddibd/SourcePackages/checkouts/HypertextApplicationLanguage/Sources/HypertextApplicationLanguage/Tests/HypertextApplicationLanguageTests/Fixtures': File not found.
<img width="909" alt="Screenshot 2021-09-07 at 17 49 55" src="https://user-images.githubusercontent.com/8770772/132365779-aefc60ee-3385-45b2-a629-ea568c5c3f85.png">

will it be fixed it was hanging(warning inside ios app project) a long time ago or it only me having warning 

Thanks

**Comment by stephencelis** [comment]
@saroar Did you mean to report this here? It looks like that warning comes from https://github.com/swift-aws/HypertextApplicationLanguage

**Comment by stephencelis** [comment]
@saroar I'm going to close this out since it seems to be unrelated to the Composable Architecture, but let us know if you meant to report something different!

**Comment by saroar** [comment]
@stephencelis I am so sorry I thought it was from Composable Architecture.
