### ISSUE TITLE
Expose Store via ViewStore

### ISSUE THREAD

**Issue by alexito4** [pointfreeco/swift-composable-architecture#78]
Given the issues with `ViewStore` and `GeometryReader` as explained [here](https://github.com/pointfreeco/swift-composable-architecture/blob/d2240d0e76c1a758dbadbf737ceefc888b2e807c/Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift#L7-L18) I'm finding myself keeping around the viewStore manually via a struct init.

```swift
    @ObservedObject var viewStore: ViewStore<State, Action>
    
    init(store: Store<State, Action>) {
        self.viewStore = ViewStore(store)
    }
```

This is actually a simple change because the init and the automatic memberwise init of the struct match so external users of the view don't have to change anything.

The problem comes when later (and quite often) I need to scope the store to pass it to another view.

```swift
        .sheet(
          isPresented: self.viewStore.binding(
            get: { ... },
            send: ...
          )
        ) {
          IfLetStore(
            self.store.scope(
                state: { .... },
                action: ...
            ),
            then: ...,
            else: EmptyView()
          )
        }
```

The `viewStore` let's us get a binding so the first part is alright. But for the scoping to the child view you need a `Store` type so you are forced now to keep it around just for this.

```swift
    private let store: Store<...>
    @ObservedObject var viewStore: ViewStore<State, Action>
    
    init(store: Store<State, Action>) {
        self.store = store
        self.viewStore = ViewStore(store)
    }
```

I'm finding myself having to deal with the workaround often enough that I would like to avoid this.

Two solutions come to mind:

1. Expose the Store API from ViewStore (we probably don't want this)
2. Expose the original store via ViewStore.

Option two would allow me to only keep the viewStore and simplify the init.

**Comment by stephencelis** [comment]
Hey @alexito4! Thanks for starting this discussion.

> Given the issues with `ViewStore` and `GeometryReader` as explained [here](https://github.com/pointfreeco/swift-composable-architecture/blob/d2240d0e76c1a758dbadbf737ceefc888b2e807c/Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift#L7-L18) I'm finding myself keeping around the viewStore manually via a struct init.

For views that merely need a view store, can you avoid the initializer by passing a view store directly?

```swift
struct MyView: View {
  @ObservedObject var viewStore: ViewStore<State, Action>
  var body: some View { ... }
}

struct MyParentView: View {
  let store: Store<State, Action>
  var body: some View {
    MyView(viewStore: ViewStore(self.Store))
  }
}
```

> The problem comes when later (and quite often) I need to scope the store to pass it to another view.
> [...]
> I'm finding myself having to deal with the workaround often enough that I would like to avoid this.
> 
> Two solutions come to mind:
> 
> 1. Expose the Store API from ViewStore (we probably don't want this)
> 2. Expose the original store via ViewStore.
> 
> Option two would allow me to only keep the viewStore and simplify the init.

Definitely worth discussing! My main concern with introducing this kind of escape hatch is that the purpose of `ViewStore` is to whittle state away to the bare essentials of a particular view and this typically means chipping away subview state that doesn't appear in parent view state. I'm working with a smaller sample size, though, so parents that care about child state may be more common than I think. Still, escape hatches can help speed along prototyping and development, so it's worth thinking about regardless. 😄

**Comment by mbrandonw** [comment]
I think my biggest apprehension comes from the fact that this is clearly a workaround for a SwiftUI bug, and once we open the escape hatch it will be hard to close.

We could think about this a little longer and see if some of these things get fixed soonish by Apple.

**Comment by stephencelis** [comment]
@alexito4 We've got a fresh [Swift forum](https://forums.swift.org/c/related-projects/swift-composable-architecture/61) provisioned for us today for discussions like these so that we can keep GitHub issues focussed on bugs. Would you mind moving the discussion there for more input so that we can close this out?

**Comment by alexito4** [comment]
I just saw the forum, nice!

I think we can close this really, if somebody else has similar tougths we can reopen the topic. I totally agree that you shouldn't commit to a public API when it's just to workaround SwiftUI bugs. 

Because is not blocking anything, it's just mere convenience, I vote for closing the issue and keeping an eye to next month announcements ^^ hopefully is fixed, and if not I will reopen on the forums 😉
