### ISSUE TITLE
Main thread checks on iOS 15 - unexpected result

### ISSUE THREAD

**Issue by lukeredpath** [pointfreeco/swift-composable-architecture#788]
**Describe the bug**
I'm currently doing some smoke testing of our app on iOS 15 using the latest Xcode beta (beta 5) in preparation for the forthcoming final release.

We're using TCA 0.27 and it looks like the recently added main thread checks aren't working as expected, I'm getting output like this:

```
Warning:

The store was interacted with on a thread that is different from the thread the store was created on:

"ViewStore.send([redacted action])" was called on the wrong thread. Make sure that "ViewStore.send" is always called on the initial thread.

  Initial thread: <NSThread: 0x600000162680>{number = 29, name = main}
  Current thread: <_NSMainThread: 0x6000001b40b0>{number = 1, name = main}

The "Store" class is not thread-safe, and so all interactions with an instance of "Store" (including all of its scopes and derived view stores) must be done on the same thread.
---

Caught debug breakpoint. Type "continue" ("c") to resume execution.
```

The weird thing here is I know that the first action sent to my store would have been on the main thread because we fire an action in `application(_:didFinishLaunching)` so I don't know how the initial thread is _not_ the main thread (although strangely it has the name "main").

**To Reproduce**
If I can put together a reproducer I will uploaded it here.

**Expected behavior**
When the first action in the app is sent on the main thread, other actions sent from the main thread should not trigger this breakpoint.

**Environment**
  - TCA 0..27
  - Xcode 13b5
  - iOS 15.

**Comment by lukeredpath** [comment]
Hmm, interesting. So our root store is created by a coordinator object that is initialised as a singleton, (e.g. `static let liveCoordinator = Coordinator()`) - the store is created in the `Coordinator`'s init.

We first reference this live coordinator in the `application(_:didFinishLaunching)` method although due to the static I'm not 100% of the lifecycle.

IIRC, "thread 29" appeared to be owned by `NSURLConnection` - I don't know if that provides a clue. We do reference our app coordinator in `application(_:handleEventsForBackgroundSession:completionHandler:)` too but I'd be surprised if this method was even called in my very limited simulator smoke testing (I hadn't even backgrounded the app). Very odd that this thread had the name "main" though. I've always assumed the main thread is *always* Thread 1.

I will keep an eye on this and see if it happens again as we continue to test. It doesn't help that we are still running a more than month old beta. 🤞🏻 for an updated Xcode this week.

**Comment by mbrandonw** [comment]
One thing you could try is to temporarily change the `static let liveCoordinator` to be a `static var` computed property so that you can get a breakpoint in there and confirm the thread.

**Comment by tgrapperon** [comment]
@lukeredpath Is the app using an "old" `UIApplicationDelegate`? Are you using some kind of logging/crash reporting framework? I've seen these things mess with `NSObject.load()` in the past, so I can imagine them creating additional threads and bootstrapping the store by mistake.

**Comment by lukeredpath** [comment]
@tgrapperon we've actually just converted our app over to the SwiftUI app lifecycle but we are still using `@UIApplicationDelegateAdaptor` and our old app delegate class.

We do have a few analytics/crash reporting tools too that could potentially be messing with this. I'll give Brandon's suggestion a try, but most of the time it seems to work OK.

**Comment by stephencelis** [comment]
@lukeredpath Have you managed to find the root of the problem? Was the store somehow being initialized on a background thread? We'd love to know if this is an issue with our thread checking code or not 😄

**Comment by lukeredpath** [comment]
@stephencelis not yet - we'll be running our app on iOS 15 more extensively over the next week now the Xcode RC has dropped, if this wasn't a one-off issue I'm sure we'll see it again, so I'll keep an eye out. I'm 99.9% certain that our store is not being created on a background thread though.

**Comment by lukeredpath** [comment]
No sooner had I posted, another member of my team just experienced this bug - except this was on Xcode 12.5.1 on iOS 14.8.

```
Make sure that "ViewStore.send" is always called on the initial thread.

  Initial thread: <NSThread: 0x281df7880>{number = 10, name = main}
  Current thread: <NSThread: 0x281dac9c0>{number = 1, name = main}

The "Store" class is not thread-safe, and so all interactions with an instance of "Store" (including all of its scopes and derived view stores) must be done on the same thread.
```

Hmm....

**Comment by tgrapperon** [comment]
@lukeredpath If you create a dedicated init for `Store` and use it for your root store in your Coordinator, you can easily check which thread is running this code.

**Comment by lukeredpath** [comment]
I'm going with this for now, in the function that creates our root store:

```swift
if !Thread.isMainThread {
  assertionFailure("The main TCA store must be created on the main thread.")
}
```

If that never asserts and we still hit this issue, then there must be something else going on here.

**Comment by lukeredpath** [comment]
Right, looks like we can still hit this problem without the above assertion being hit which points to the underlying `Thread` object that represents the main thread changing - I'm just going to pair with my colleague and see if we can get more info.

**Comment by tgrapperon** [comment]
Are you sure `isMainThread` isn't merely checking if the name of the thread is `"main"`? What happens if you dump the thread where you assert?

**Comment by mbrandonw** [comment]
I'd be interested in seeing what `Thread.isMainThread` prints when the store is created and when the warning breakpoint is triggered. I'm wondering if thread identity can't be relied on for the main thread, but maybe `isMainThread` can be relied on.

We're also experimenting with using thread variables to detect this situation. I would hope that even if there are two different references for the main thread that they would at least still share the same thread variables.

**Comment by mbrandonw** [comment]
@lukeredpath Could you point your project to this branch and see if you can reproduce?

https://github.com/pointfreeco/swift-composable-architecture/tree/thread-identity

**Comment by lukeredpath** [comment]
Right, I think we've tracked down the problem - we were creating a scoped store on a background thread. We have a feature where we prompt for access to the user's contacts and the API for requesting permission calls back on a non-main thread - this is where we were initialising a scoped store to inject into our view.

So the bug was in our code after all (phew) but its very strange that it is being printed with a name `main`.

We set a breakpoint on the code that calls `.scope` and verified that we were on a background thread (one of the Dispatch global queues in fact):

```
(lldb) po Thread.current
<NSThread: 0x2835cd800>{number = 5, name = (null)}
```

The weird thing is that when TCA prints its warning message, the name has changed:

```
  Initial thread: <NSThread: 0x2835cd800>{number = 5, name = main}
  Current thread: <NSThread: 0x2835c8680>{number = 1, name = main}
```

Anyway, I think we can close this but I do wonder if TCA could also surface a similar warning/breakpoint if you try to call `.scope` on a Store from a different thread to the parent store's initial thread. WDYT?

**Comment by mbrandonw** [comment]
Ah glad you tracked it down! Thanks for digging into all of that.

> Anyway, I think we can close this but I do wonder if TCA could also surface a similar warning/breakpoint if you try to call .scope on a Store from a different thread to the parent store's initial thread. WDYT?

Totally agree, we'll PR something soon.

**Comment by tgrapperon** [comment]
Maybe TCA could ship with a Main Thread locked subclass of `Store`? If this class is put on the Main Actor, we would furthermore get compile time checks that calls are realized on one unique thread. I don't know if `Effect`s could be localized too.

**Comment by mbrandonw** [comment]
Also I'm going to convert this to a discussion for now. May help others in the future.
