### ISSUE TITLE
Fails to build for mac on XCode13 RC (no MacOS 12 sdk support yet)

### ISSUE THREAD

**Issue by sphilipakis** [pointfreeco/swift-composable-architecture#796]
**Describe the bug**
fails to build for MacOS with XCode13 RC

**To Reproduce**
open the project with XCode13 RC, build for mac.

**Expected behavior**
framework should build successfully

**Screenshots**
<img width="842" alt="Screen Shot 2021-09-14 at 4 21 01 PM" src="https://user-images.githubusercontent.com/380192/133346375-a2b22bce-30a1-4089-9283-e74b40712de4.png">

**Environment**
  - swift-composable-architecture main branch
  - Xcode 13 RC (13A233)
  - Swift 5.5
  - OS: Big Sur 11.6

**Additional context**
XCode13 RC does not ship with MacOS12 SDK yet.

**Comment by stephencelis** [comment]
@sphilipakis Can you give #797 a try?

**Comment by sphilipakis** [comment]
#797 is fixes it. Thanks!
