### ISSUE TITLE
ForEach in LocalReducer needs more context

### ISSUE THREAD

**Issue by Viranchee** [pointfreeco/swift-composable-architecture#81]
**ForEach on Local Reducer error: Type of expression is ambiguous without more context**

**To Reproduce**
Below code:

```swift
import ComposableArchitecture
import Contacts

typealias Contact = CNContact

extension Contact: Identifiable {} // So that ForEach, ForEachStore work

enum ContactAction: Equatable {
  case contactTapped
  case starTapped
}

struct ContactEnvironment {}

let contactReducer = Reducer<Contact, ContactAction, ContactEnvironment>.init { contact, action, environment in
    return .none
}

struct AppState: Equatable {
  var contacts: IdentifiedArrayOf<Contact> = []
  var editMode: EditMode = .inactive
}

enum AppAction: Equatable {
  case addContactTapped
  case contact(id: Int, action: ContactAction)
  case delete(IndexSet)
}

struct AppEnvironment {
  var newContact: () -> Contact
}

let appReducer = Reducer<AppState, AppAction, AppEnvironment>.combine(
  
  Reducer { state, action, environment in
    switch action {
    case .addContactTapped:
      state.contacts.insert(environment.newContact(), at: 0)
      return .none
    case .contact(id: let id, action: let action):
      return .none
    case .delete(let index):
      state.contacts.remove(atOffsets: index)
      return .none
    }
  }
//   FIXME: - LocalReducer is not able to TypeCheck! does not compile, ambiguous reference
  ,
  contactReducer.forEach(
    state: \AppState.contacts,
    action: /AppAction.contact(id:action:),
    environment: { _ in ContactEnvironment() }
  )
).debug()

```

**Expected behavior**
Give a clear and concise description of what you expected to happen.

**Environment**
 - Xcode  11.4.1
 - Swift 5.2

**Comment by pcolton** [comment]
You have a blank Identifiable, it should probably be:

```swift
extension Contact: Identifiable {
    public var id: String { self.identifier }
} // So that ForEach, ForEachStore work
```

And then you use an Int as the contact id, which should probably be a String:

```swift
  case contact(id: String, action: ContactAction)
```

That should at least get it all compiling.

**Comment by pcolton** [comment]
The confusion may come from the fact that you are using an `IdentifiedArray` which can key off a hashable identifier, hence the use of 'id', but if you use a normal array:

```swift
struct AppState: Equatable {
  var contacts: [Contact] = []
  var editMode: EditMode = .inactive
}
```

then your action should probably have used an index into the array: 

```swift
case contact(index: Int, action: ContactAction)
```

then your reducer would also work like this:

```swift
contactReducer.forEach(
    state: \AppState.contacts,
    action: /AppAction.contact(index:action:),
    environment: { _ in ContactEnvironment() }
  )
```

**Comment by Viranchee** [comment]
Yeah that did help and compiled!

I have an issue with `ForEachStore` on compiling

``` swift
struct ContentView: View {
  
  let store: Store<AppState, AppAction>
  
  var body: some View {
    WithViewStore(self.store) { viewStore in
      List {
        ForEachStore(self.store.scope(state: \AppState.contacts, action: /AppAction.contact(index:action:))) { contactStore in
          EmptyView()
        }.onDelete(perform: { viewStore.send(.delete($0))})
      }
    }
  }
}

```

**Comment by stephencelis** [comment]
@Viranchee `ForEachStore` takes a transform function for `action`, not a case path. You should be able to remove the `/` and get things building:

```diff
-ForEachStore(self.store.scope(state: \AppState.contacts, action: /AppAction.contact(index:action:))) { contactStore in
+ForEachStore(self.store.scope(state: \AppState.contacts, action: AppAction.contact(index:action:))) { contactStore in
```

**Comment by Viranchee** [comment]
One of the worst errors
> error: /Users/virancheel/Library/Developer/Xcode/DerivedData/TempContacts-aougvvxkcrjatxausktixjsbllgi/Build/Products/Debug-iphonesimulator/ComposableArchitecture: No such file or directory (in target 'TempContacts' from project 'TempContacts')

Might try adding and removing the library

**Comment by Viranchee** [comment]
<img width="728" alt="Screenshot 2020-05-13 at 12 02 24 AM" src="https://user-images.githubusercontent.com/9246095/81731757-086f8200-94ad-11ea-8b36-1bc197c018f6.png">

**Comment by pcolton** [comment]
Drop the 'AppState' from your state: line...

```swift
 ForEachStore(self.store.scope(
            state: \.contacts,
            action: AppAction.contact(index:action:))) { contactStore in
```

**Comment by Viranchee** [comment]
It worked! Thank you

**Comment by Viranchee** [comment]
I need to watch the recent video again!

**Comment by Viranchee** [comment]
I am not getting code completion, is this normal?

**Comment by stephencelis** [comment]
@Viranchee That's normal in Swift/SwiftUI in general, unfortunately. The team's been working hard to improve type checking, and hopefully we'll see more improvements with WWDC! If you can, I'm sure it would be helpful to file feedback with Apple or bugs on the Swift tracker. In the meantime you can sometimes improve code completion by quitting and reopening, breaking your views down into smaller views that get pieced together, or relying less on type inference by specifying types explicitly.

**Comment by stephencelis** [comment]
@Viranchee Now that you've gotten things working, is it OK if I close this issue out? We also just got a [Swift forum](https://forums.swift.org/c/related-projects/swift-composable-architecture) for general questions about the architecture, which should serve better than GitHub issues, which we'd like to use for bug tracking.

**Comment by Viranchee** [comment]
Yes we can close this issue
