### ISSUE TITLE
0101-swift-composable-architecture-tour-pt2

### ISSUE THREAD

**Issue by kdeda** [pointfreeco/swift-composable-architecture#84]
**Describe the bug**
Fails to copy the ComposableArchitecture framework because it is not build

**To Reproduce**
empty ~/Library/Developer
git clone https://github.com/pointfreeco/episode-code-samples.git
Open 0101-swift-composable-architecture-tour-pt2/Todos/Todos.xcodeproj
Run the target (pick any iOS simulator)
 
**Expected behavior**
0100-swift-composable-architecture-tour-pt1 checks out builds and runs fine

**Environment**
 - Xcode [e.g. 11.4.1]
 - Swift [e.g. 5.2.2]
 - OS (if applicable): [e.g. iOS 13]

**Additional context**
Add any more context about the problem here.

**Comment by stephencelis** [comment]
Oh ha, that's because the episode used an earlier version. I've pushed a fix to the episode-code-samples repo here: https://github.com/pointfreeco/episode-code-samples/commit/5c5003e1f76c7e515898e633a57dcb65c99b3db7

Thanks for letting us know!

**Comment by kdeda** [comment]
confirmed, thanks
