### ISSUE TITLE
Only first value published when using Effect.merge() and .cancellable()

### ISSUE THREAD

**Issue by aroben** [pointfreeco/swift-composable-architecture#946]
**Describe the bug**
I've found that using `Effect.merge()` and `.cancellable()` together can in some situations cause an effect to end after its first value is published, rather than waiting for all values to be published. Here's a reduced test case, with a couple of variations that do not fail as well:

**To Reproduce**

```swift
import Combine 
import ComposableArchitecture 
import XCTest 

class MergeCancelTest: XCTestCase { 
  var cancellables: Set<AnyCancellable> = []

  func testNestedMergeCancellation() {
    // The test passes if you change this to Effect.concatenate
    let effect = Effect<Int, Never>.merge(
      (1...2).publisher
        // The test passes if you add .receive(on: testScheduler) and advance the scheduler before XCTAssertEqual
        .eraseToEffect()
        // The test passes if you remove this .cancellable() call
        .cancellable(id: 1)
    )
    // The test passes if you remove this .cancellable() call
    .cancellable(id: 2)
     
    var output: [Int] = []
    effect
      .sink { output.append($0) }
      .store(in: &cancellables)
     
    XCTAssertEqual(output, [1, 2])
  }
} 
```

I've wrapped this up in a test project which shows the failing case plus the multiple variations mentioned in the comments: [MergeCancel.zip](https://github.com/pointfreeco/swift-composable-architecture/files/7809799/MergeCancel.zip)

**Expected behavior**
Both values (1 and 2) should be passed to the `.sink` closure and the test should pass. Instead it fails with this error:

``` 
MergeCancelTests/MergeCancelTests.swift:32: error: -[MergeCancelTests.MergeCancelTest testNestedMergeCancellation] : XCTAssertEqual failed: ("[1]") is not equal to ("[1, 2]")
``` 

As the comments indicate, I know of three ways to make this test pass: 

1. Change `Effect.merge` to `Effect.concatenate`
2. Change the inner publisher to use a non-immediate scheduler
3. Remove either (or both) of the `.cancellable(id:)` calls

(In my current project I've chosen option 2 to get my tests passing, but it makes the tests more complicated than necessary.)

I'm pretty sure the bug is related to `Effect.cancellable` using a `PassthroughSubject` internally, and subscribing that subject to the publisher before the subject has been connected to any downstream subscribers. But I don't understand it fully, because clearly that works just fine in most cases.

**Environment**
  - swift-composable-architecture version 0.32.0
  - Xcode 13.0
  - Swift 5.5
  - OS: macOS 12.0

**Comment by mbrandonw** [comment]
This is a strange one :/ Weirdly if you replace `Effect.merge` with `Effect.concatenate` it will pass.

**Comment by aroben** [comment]
Right, that's the first variant I mentioned. Lots of ways to make this test "pass", but none of them are what I want 😄

**Comment by mbrandonw** [comment]
Oh oops, sorry didn't see that comment! We'll poke around at this and let you know what we find.

**Comment by stephencelis** [comment]
@aroben I was able to reproduce the bug outside of TCA with simple Combine operators:

```swift
class MergeManyTests: XCTestCase {
  func testNestedMergeMany() {
    var cancellables: Set<AnyCancellable> = []
    let p1 = (1...2).publisher
    let p2 = Deferred { () -> PassthroughSubject<Int, Never> in
      let subject = PassthroughSubject<Int, Never>()
      p1.subscribe(subject).store(in: &cancellables)
      return subject
    }
    let p3 = Publishers.MergeMany(p2)
    let p4 = Deferred { () -> PassthroughSubject<Int, Never> in
      let subject = PassthroughSubject<Int, Never>()
      p3.subscribe(subject).store(in: &cancellables)
      return subject
    }
    var output: [Int] = []
    p4
      .sink { output.append($0) }
      .store(in: &cancellables)
    XCTAssertEqual(output, [1, 2])
  }
}
```

Removing a single operator from the above chain gets things passing, strangely enough. And using `Publisher.merge(with: Empty())` instead of `Publishers.MergeMany` has the same problem.

Hopefully we can work around the bug in Combine by relying on different tools to achieve the same thing!

**Comment by stephencelis** [comment]
(FB9833083)
