### ISSUE TITLE
Crash with new runtime warning 

### ISSUE THREAD

**Issue by AlexisQapa** [pointfreeco/swift-composable-architecture#958]
**Describe the bug**
I hit a crash when running an optional reducer with nil state on iOS 13.7 on device. I'm building a minimal reproducible example and checking which version are affected.
Right now this works as expected on my iOS 15 device.

**Expected behavior**
This should not crash

**Screenshots**
<img width="993" alt="Screenshot 2022-01-11 at 12 20 05" src="https://user-images.githubusercontent.com/31622518/148933553-bd32bdf6-d153-427b-9f14-3b20cc8f4814.png">

**Environment**
  - swift-composable-architecture version [e.g. 0.33.0]
  - Xcode 13.2.1
  - Swift Apple Swift version 5.5.2
  - OS: iOS 13.7

**Additional context**
I guess the symbol used to search for SwiftUI doesn't exist at the time in iOS 13.

**Comment by stephencelis** [comment]
Luckily this only affects debug builds on iOS 13, but #945 should fix things when we merge it!

**Comment by stephencelis** [comment]
Fixed by #945!
